/* Mochi v4.3.0 — Firebase family progress sync. */
(function(){
'use strict';
const CONFIG_KEY='cubs_sync', META_KEY='mochi_cloud_meta_v1', DEVICE_KEY='mochi_cloud_device_v1', APP='mochi-math-p4-6';
let localSave=null, ready=false, suppress=false, timer=null, syncing=false, lastStatus='Cloud sync not configured.';
const cp=x=>{try{return JSON.parse(JSON.stringify(x));}catch(e){return null;}};
function cfg(){let x=null;try{x=JSON.parse(localStorage.getItem(CONFIG_KEY)||'null');}catch(e){}const url=String(x?.url||'').trim().replace(/\/+$/,''),code=String(x?.code||'').trim();return{url,code,ok:/^https:\/\/[a-z0-9.-]+\.(?:firebasedatabase\.app|firebaseio\.com)$/i.test(url)&&code.length>=6};}
function setCfg(url,code){url=String(url||'').trim().replace(/\/+$/,'');code=String(code||'').trim();if(!/^https:\/\/[a-z0-9.-]+\.(?:firebasedatabase\.app|firebaseio\.com)$/i.test(url))throw Error('Use the Firebase Realtime Database URL ending in firebasedatabase.app or firebaseio.com.');if(code.length<6)throw Error('Family code must be at least 6 characters.');localStorage.setItem(CONFIG_KEY,JSON.stringify({url,code}));}
function endpoint(c=cfg()){return c.ok?`${c.url}/fam/${encodeURIComponent(c.code).replace(/\./g,'%2E')}/mochi.json`:'';}
function meta(){try{return JSON.parse(localStorage.getItem(META_KEY)||'{}')||{};}catch(e){return{};}}
function setMeta(x){try{localStorage.setItem(META_KEY,JSON.stringify({...meta(),...x}));}catch(e){}}
function device(){let x='';try{x=localStorage.getItem(DEVICE_KEY)||'';}catch(e){}if(!x){x=globalThis.crypto?.randomUUID?.()||('d-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));try{localStorage.setItem(DEVICE_KEY,x);}catch(e){}}return x;}
function latest(s){let t=0;for(const group of [s?.learning?.attempts,s?.learning?.notes,s?.science?.attempts,s?.science?.notes,s?.course?.attempts])for(const x of group||[])t=Math.max(t,Number(x?.at)||0);return t;}
function uploadState(s){const x=cp(s)||{};for(const k of ['keys','provider','models','readModels'])delete x[k];return x;}
function mergeList(a,b,key,preferB,limit){const m=new Map();for(const x of a||[]){const k=key(x);if(k)m.set(k,x);}for(const x of b||[]){const k=key(x);if(k&&(!m.has(k)||preferB))m.set(k,x);}return[...m.values()].sort((x,y)=>(+x.at||0)-(+y.at||0)).slice(-limit);}
function mergeLearning(a={},b={},preferB){const out=cp(preferB?b:a)||{};out.version=1;out.attempts=mergeList(a.attempts,b.attempts,x=>String(x?.id||''),preferB,5000);out.notes=mergeList(a.notes,b.notes,x=>`${+x?.at||0}|${String(x?.question||'').slice(0,100)}|${String(x?.text||'').slice(0,100)}`,preferB,200);out.benchmarks=mergeList(a.benchmarks,b.benchmarks,x=>`${x?.date||''}|${String(x?.name||'').slice(0,100)}`,preferB,50);return out;}
function mergeScience(a={},b={},preferB){const out=cp(preferB?b:a)||{};out.version=1;out.attempts=mergeList(a.attempts,b.attempts,x=>`${x?.item||''}|${+x?.at||0}`,preferB,1000);out.notes=mergeList(a.notes,b.notes,x=>`${x?.skill||''}|${+x?.at||0}|${String(x?.text||'').slice(0,100)}`,preferB,100);out.seenAssess=[...new Set([...(a.seenAssess||[]),...(b.seenAssess||[])])];return out;}
function mastery(a={},b={}){const out={};for(const k of new Set([...Object.keys(a),...Object.keys(b)]))out[k]={a:Math.max(+a[k]?.a||0,+b[k]?.a||0),c:Math.max(+a[k]?.c||0,+b[k]?.c||0)};return out;}
function mergeState(local={},remote={},remoteNewer){const out=cp(remoteNewer?remote:local)||{},other=remoteNewer?local:remote;for(const [k,v] of Object.entries(other))if(out[k]===undefined)out[k]=cp(v);out.learning=mergeLearning(local.learning,remote.learning,remoteNewer);if(local.science||remote.science)out.science=mergeScience(local.science,remote.science,remoteNewer);if(window.MochiCourse&&(local.course||remote.course))out.course=MochiCourse.merge(local.course,remote.course);if(window.MochiPlanner&&(local.planner||remote.planner))out.planner=MochiPlanner.merge(local.planner,remote.planner);out.mastery=mastery(local.mastery,remote.mastery);for(const k of ['done','right','best','fed'])out[k]=Math.max(+local[k]||0,+remote[k]||0);if(Array.isArray(local.owned)||Array.isArray(remote.owned))out.owned=[...new Set([...(local.owned||[]),...(remote.owned||[])])];for(const k of ['keys','provider','models','readModels']){if(local[k]!==undefined)out[k]=cp(local[k]);else delete out[k];}return out;}
function normalise(s){if(window.MochiPlanner&&s.planner)s.planner=MochiPlanner.validate(s.planner);if(window.MochiCourse&&s.course)s.course=MochiCourse.validate(s.course);if(typeof MochiLearning!=='undefined')try{MochiLearning.init(s);}catch(e){}if(s.science){s.science.version=1;s.science.attempts=Array.isArray(s.science.attempts)?s.science.attempts.slice(-1000):[];s.science.notes=Array.isArray(s.science.notes)?s.science.notes.slice(-100):[];s.science.seenAssess=Array.isArray(s.science.seenAssess)?s.science.seenAssess:[];}return s;}
function status(text,kind=''){lastStatus=text;const e=document.getElementById('cloudSyncStatus');if(e){e.textContent=text;e.dataset.kind=kind;}}
async function readRemote(){return window.MochiNetwork.request(endpoint(),{cache:'no-store',headers:{Accept:'application/json'}},true);}
async function writeRemote(state,updatedAt){const body={schema:1,app:APP,student:'Euna',updatedAt,deviceId:device(),state:uploadState(state)};const r=await window.MochiNetwork.request(endpoint(),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(`Database write failed (${r.status}).`);setMeta({updatedAt,lastPush:Date.now()});}
function refresh(){try{studyPaint?.();}catch(e){}try{studyParent?.();}catch(e){}document.dispatchEvent(new CustomEvent('mochi:cloud-merged'));}
async function sync(manual=false){const c=cfg();if(!c.ok){status('Cloud sync not configured. Your work is still saved on this device.');return;}if(syncing)return;syncing=true;status(manual?'Syncing now…':'Checking family cloud…');try{const r=await readRemote(),m=meta(),localAt=+m.updatedAt||latest(S)||0;if(!r||r.app!==APP||!r.state){ready=true;const at=Math.max(Date.now(),localAt);await writeRemote(S,at);status('Cloud sync connected · Euna’s Mochi progress uploaded.','ok');paint();return;}const remoteAt=+r.updatedAt||0,merged=normalise(mergeState(S,r.state,remoteAt>localAt));if(JSON.stringify(uploadState(S))!==JSON.stringify(uploadState(merged))){suppress=true;try{S=merged;await localSave(S);}finally{suppress=false;}refresh();}const at=Math.max(Date.now(),localAt,remoteAt);setMeta({updatedAt:at,lastPull:Date.now(),remoteAt});ready=true;await writeRemote(S,at);status('Cloud sync up to date · Euna’s progress is shared across family devices.','ok');paint();}catch(e){ready=true;status('Cloud sync unavailable · '+e.message+' Local progress is safe.','bad');paint();}finally{syncing=false;}}
function schedule(){if(!ready||!cfg().ok||suppress)return;clearTimeout(timer);timer=setTimeout(async()=>{if(syncing)return;syncing=true;status('Saving to family cloud…');try{const at=Date.now();setMeta({updatedAt:at});await writeRemote(S,at);status('Saved to family cloud.','ok');paint();}catch(e){status('Cloud save failed · '+e.message+' Local progress is safe.','bad');}finally{syncing=false;}},900);}
function wrap(){if(localSave||typeof save!=='function')return;localSave=save;save=async function(x){const r=await localSave(x);if(!suppress){setMeta({updatedAt:Date.now()});schedule();}return r;};}
function mount(){if(document.getElementById('cloudSyncDetails'))return;const a=document.getElementById('backupStatus')||document.querySelector('#panel .study-actions');if(!a)return;const d=document.createElement('details');d.id='cloudSyncDetails';d.className='study-details';d.innerHTML=`<summary>Family cloud sync</summary><p class="study-note">Uses the same family Firebase configuration as the other learning apps. Mochi stores its progress separately from Pokémon Academy.</p><label class="study-field">Firebase database URL<input id="cloudDbUrl" type="url" autocomplete="off" placeholder="https://…firebasedatabase.app"></label><label class="study-field">Family code<input id="cloudFamilyCode" type="password" autocomplete="off" minlength="6" placeholder="Same family code used by the other apps"></label><div class="study-actions"><button class="btn quiet" id="cloudSyncSave">Save & sync</button><button class="btn quiet" id="cloudSyncNow">Sync now</button></div><p id="cloudSyncStatus" class="study-status" role="status"></p>`;a.insertAdjacentElement('beforebegin',d);document.getElementById('cloudSyncSave').onclick=async()=>{try{setCfg(document.getElementById('cloudDbUrl').value,document.getElementById('cloudFamilyCode').value);setMeta({updatedAt:latest(S)||Date.now()});await sync(true);}catch(e){status(e.message,'bad');}};document.getElementById('cloudSyncNow').onclick=()=>sync(true);paint();}
function paint(){const c=cfg(),u=document.getElementById('cloudDbUrl'),f=document.getElementById('cloudFamilyCode'),s=document.getElementById('cloudSyncStatus');if(u&&document.activeElement!==u)u.value=c.url||'';if(f&&document.activeElement!==f)f.value=c.code||'';if(s&&!syncing)s.textContent=lastStatus;}
async function init(){wrap();mount();if(cfg().ok)await sync(false);else{ready=true;status('Cloud sync not configured. Enter the same Firebase URL and family code used by the other apps.');}window.addEventListener('online',()=>sync(false));window.addEventListener('focus',()=>{if(Date.now()-(+meta().lastPull||0)>15000)sync(false);});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&Date.now()-(+meta().lastPull||0)>60000)sync(false);});}
if(window.MochiReady)init();else document.addEventListener('mochi:ready',init,{once:true});
})();
