/* Exact, labelled teaching models. Illustrations provide context, not numerical evidence. */
(function(root){
'use strict';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const flow=parts=>'<ol class="course-flow">'+parts.map(x=>'<li>'+escape(x)+'</li>').join('')+'</ol>';
const range=(label,min,max,value,key)=>`<label class="course-slider">${escape(label)} <input type="range" min="${min}" max="${max}" value="${value}" data-value="${key}"></label>`;
const svg=(label,body,w=520,h=230)=>`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${escape(label)}">${body}</svg>`;
const text=(x,y,t)=>`<text x="${x}" y="${y}" text-anchor="middle" fill="#352341" font-family="system-ui" font-size="17">${escape(t)}</text>`;
function model(type,values={}){
 const n=Number(values.n)||3,b=Number(values.b)||4;let controls='',picture='',explanation='';
 if(['fractions','fraction-product','fraction-divide','remainder','percent','ratio','bars'].includes(type)){
  const percent=type==='percent',den=percent?10:b,num=Math.min(n,den);controls=range(percent?'Shaded tenths':'Shaded parts',1,den,num,'n')+(percent?'':range('Equal parts in the whole',2,10,den,'b'));
  picture='<div class="course-parts" style="--parts:'+den+'">'+Array.from({length:den},(_,i)=>'<span class="'+(i<num?'filled':'')+'">'+(i+1)+'</span>').join('')+'</div>';
  explanation=percent?`${num} of 10 equal parts = ${num*10}% of this whole. The unshaded part is ${100-num*10}%.`:type==='fraction-divide'?`${num}/${den} contains ${num} groups of size 1/${den}. Therefore (${num}/${den}) ÷ (1/${den}) = ${num}.`:type==='ratio'?`Shaded : unshaded = ${num} : ${den-num}. Shaded : total = ${num} : ${den}. These compare different quantities.`:type==='fraction-product'?`Each strip part is 1/${den} of this whole. ${num} × (1/${den}) = ${num}/${den}. To model multiplication by a fraction, subdivide each part again.`:`${num}/${den} of one shared whole is shaded; ${den-num}/${den} remains. Equal-sized parts are essential.`;
 }else if(['area','volume','circle','angles','net','place','data','balance','rate','counting'].includes(type)){
  if(type==='balance'){controls=range('Try a value for x',1,8,n,'n');picture=flow([`3 × ${n} + 2 = ${3*n+2}`,'Compare with 14']);explanation=3*n+2===14?'Both sides are 14, so x = 4 satisfies 3x + 2 = 14.':'The sides differ. Undo adding 2, then divide by 3; verify your proposed value.';}
  if(type==='area'||type==='volume'){controls=range('Length / cm',1,8,n,'n')+range('Breadth / cm',1,8,b,'b');picture='<div class="course-parts grid" style="--parts:'+n+'">'+Array.from({length:n*b},()=>'<span class="filled"></span>').join('')+'</div>';explanation=type==='volume'?`One layer contains ${n*b} unit cubes. At a height of 3 cm, three layers contain ${n*b*3} cubes: volume ${n*b*3} cm³. The picture shows the base layer.`:`${b} rows of ${n} unit squares give area ${n*b} cm². The boundary has length 2 × (${n} + ${b}) = ${2*(n+b)} cm.`;}
  if(type==='circle'){controls=range('Radius / cm',1,10,n,'n');picture=svg('Circle with a labelled radius',`<circle cx="260" cy="105" r="78" fill="#eee2f9" stroke="#7848a0" stroke-width="3"/><path d="M260 105h78" stroke="#593475" stroke-width="3"/><circle cx="260" cy="105" r="4" fill="#593475"/>${text(290,94,'r = '+n)}${text(260,213,'Diameter = '+2*n+' cm')}`);explanation=`Circumference = 2 × π × ${n} cm. Area = π × ${n}² cm². The model changes labels; the drawing is not to scale.`;}
  if(type==='angles'){controls=range('First angle / tens of degrees',1,17,Math.min(17,n),'n');const angle=n*10,rad=angle*Math.PI/180,x=260+110*Math.cos(rad),y=180-110*Math.sin(rad);picture=svg('Two adjacent angles on a straight line',`<path d="M80 180h360 M260 180L${x} ${y}" stroke="#77469f" stroke-width="3" fill="none"/>${text(370,210,angle+'°')}${text(140,210,(180-angle)+'°')}`);explanation=`The adjacent angles total 180°. If one is ${angle}°, the other is ${180-angle}°. The labels identify the two regions beside the sloping ray.`;}
  if(type==='net'){const cells=[[0,1],[1,1],[2,1],[3,1],[1,0],[1,2]];picture=svg('Valid six-square cube net: four in a row, one above and one below the second square',cells.map(([x,y],i)=>`<rect x="${140+x*54}" y="${15+y*54}" width="54" height="54" fill="${i===1?'#bd99da':'#eee3f8'}" stroke="#70478d" stroke-width="2"/>${text(167+x*54,49+y*54,String(i+1))}`).join(''));explanation='Six equal squares: a strip of four, with one above and one below its second square. Fold it on paper. Face 2 is opposite face 4; faces 5 and 6 are opposite. This exact net is separate from the decorative artwork.';}
  if(type==='place'){controls=range('Number of tenths',1,20,n,'n');picture='<div class="course-table"><table><caption>Place value</caption><thead><tr><th>Ones</th><th>Tenths</th><th>Value</th></tr></thead><tbody><tr><td>'+Math.floor(n/10)+'</td><td>'+n%10+'</td><td>'+Number(n/10).toFixed(1)+'</td></tr></tbody></table></div>';explanation=`${n} tenths make ${Math.floor(n/10)} whole ones and ${n%10} tenths. The unit changes the numerical description, not the amount.`;}
  if(type==='data'){controls=range('Third value',1,12,n,'n');picture=flow(['4','8',String(n)]);explanation=`Total = ${12+n}. There are 3 values. Average = ${12+n} ÷ 3 = ${((12+n)/3).toFixed(2)}${(12+n)%3?' (rounded to 2 decimal places)':''}. Changing one value affects the total and average.`;}
  if(type==='rate'){controls=range('Number of notebooks',1,8,n,'n');picture=flow([n+' notebooks','$3 per notebook','$'+3*n+' total']);explanation='This model assumes the same price per notebook and no fixed fee or discount. State the constant-rate assumption before scaling.';}
  if(type==='counting'){controls=range('Choices for first step',1,6,n,'n');picture='<div class="course-parts" style="--parts:3">'+Array.from({length:n},(_,i)=>['A','B','C'].map(c=>'<span>'+String(i+1)+c+'</span>').join('')).join('')+'</div>';explanation=`There are ${n} first choices and 3 second choices for each: ${n*3} outcomes. Listing systematically avoids missing or repeating a case. Order matters in these labelled pairs.`;}
 }else{
  const diagrams={
   'life-cycle':['Egg','Larva','Pupa','Adult','New generation of eggs'],
   'flower-cycle':['Pollination: pollen reaches stigma','Fertilisation: reproductive cells fuse','Seeds and fruit develop','Dispersal','Germination under suitable conditions'],
   digestion:['Mouth','Gullet','Stomach','Small intestine: digestion and absorption','Large intestine: water absorption','Anus'],
   transport:['Lungs: oxygen enters blood','Blood carries oxygen to body parts','Carbon dioxide enters blood from body parts','Blood returns it to lungs'],
   photosynthesis:['Light energy + water + carbon dioxide','Photosynthesis in green parts','Food made + oxygen released'],
   'water-cycle':['Liquid water gains heat','Evaporation to water vapour','Water vapour loses heat','Condensation to droplets'],
   states:['Ice (solid)','Gains heat: melting','Liquid water','Loses heat: freezing','Ice'],
   energy:['Battery: chemical potential energy','Electrical energy','Bulb: light and heat'],
   'food-web':['Grass','Grasshopper','Frog'],
   'fair-test':['Choose one factor to change','Choose what to measure','Control other relevant conditions','Repeat and record','Explain the pattern and limits'],
   forces:['Hand applies a push','Block slides on a fixed table','Friction acts against sliding','Motion slows']
  };
  if(diagrams[type]){picture=flow(diagrams[type]);explanation=type==='food-web'?'Here arrows mean transfer of energy from food to eater. This is a specified simple chain, not every relationship in the pond illustration.':type==='digestion'?'Arrows show the route of food contents. Digested substances leave the small intestine by absorption into blood; they do not all continue down this route.':type==='transport'?'This is a functional sequence, not an anatomical map. The heart pumps blood; the lungs exchange gases.':type==='photosynthesis'?'Food-making differs from respiration, which releases energy from food in living cells during both day and night.':type==='life-cycle'?'The adult does not turn back into an egg. Reproduction starts a new generation; stage durations are not shown to scale.':'Read each stage aloud and explain the connection. The arrow means a sequence or conversion here; it does not indicate size, time or measured distance.';}
  if(type==='cooling'){controls=range('Time / minutes',1,6,n,'n');const temps=[60,50,42,36,32,29];picture='<div class="course-table"><table><caption>Illustrative cooling data; room 25°C</caption><tr><th>Time / min</th><th>Temperature / °C</th></tr>'+temps.slice(0,n).map((t,i)=>'<tr><td>'+(i+1)+'</td><td>'+t+'</td></tr>').join('')+'</table></div>';explanation='These invented teaching data show cooling toward room temperature, not measurements from the artwork. Explain why extending a straight line far below 25°C would be inappropriate for this model.';}
  if(type==='shadow'){controls=range('Card distance from source / arbitrary units',2,8,n,'n');const x=60+n*40,k=40,half=k*(460-40)/(x-40);picture=svg('Small light source, opaque card and screen: shadow model',`<circle cx="40" cy="110" r="7" fill="#a672ca"/><path d="M40 110L460 ${110-half} M40 110L460 ${110+half}" stroke="#ab8fc0" stroke-width="2"/><path d="M${x} 70v80" stroke="#4a295f" stroke-width="6"/><path d="M460 0v220" stroke="#d4c8de" stroke-width="4"/><path d="M460 ${110-half}v${2*half}" stroke="#56326f" stroke-width="8"/>${text(65,220,'Source')}${text(x,220,'Card')}${text(455,245,'Screen')}`,520,260);explanation='The source and screen stay fixed; the card keeps its size. Moving the card nearer the source increases the shadow. The screen may show only part of a very large shadow. This idealised model uses a small source.';}
  if(type==='circuit'){controls='<label class="course-slider"><input type="checkbox" data-value="closed" '+(values.closed?'checked':'')+'> Close the switch</label>';const closed=!!values.closed;picture=svg('Simple circuit with battery, switch and bulb',`<path d="M100 150V50H240 M${closed?'240 50H300':'246 28L292 50'} M300 50H420V180H270 M250 180H100V150" fill="none" stroke="#724a92" stroke-width="3"/><path d="M250 158v44 M270 169v22" stroke="#463050" stroke-width="4"/><circle cx="420" cy="115" r="24" fill="${closed?'#f7dc94':'#eee3f8'}" stroke="#724a92" stroke-width="3"/>${text(185,35,'Switch')}${text(350,110,'Bulb')}${text(260,225,'Battery')}`,520,250);explanation=closed?'The switch closes the path through both bulb contacts and the battery. In this simplified model the bulb lights.':'The open switch breaks the conducting path. The bulb is off. Use supervised low-voltage kits only for a physical test.';}
 }
 return {controls,picture,explanation};
}
function mount(host,type,onUse=()=>{}){
 if(!type){host.hidden=true;return;}host.hidden=false;const values={n:type==='shadow'?4:3,b:4,closed:false};
 const draw=()=>{const m=model(type,values);host.innerHTML='<h3>Explore the idea</h3><p>Predict what will change. Then test it and explain why.</p>'+m.controls+'<div class="course-model">'+m.picture+'</div><p class="course-model-result" role="status">'+escape(m.explanation)+'</p>';for(const el of host.querySelectorAll('[data-value]'))el.oninput=()=>{const key=el.dataset.value;values[key]=el.type==='checkbox'?el.checked:Number(el.value);onUse();const updated=model(type,values);host.querySelector('.course-model').innerHTML=updated.picture;host.querySelector('.course-model-result').textContent=updated.explanation;if(key==='b'){const slider=host.querySelector('[data-value=n]');slider.max=values.b;values.n=Math.min(values.n,values.b);slider.value=values.n;}};};draw();
}
root.MochiCourseVisuals={model,mount};if(typeof module!=='undefined')module.exports=root.MochiCourseVisuals;
})(typeof globalThis!=='undefined'?globalThis:this);
