/* Original teaching organised around the supplied commercial DSA preparation benchmark.
   Not an official entrance syllabus, test blueprint or admissions predictor. */
(function(root){
'use strict';
const strands={algebra:'Algebra, Rates & Proportions',geometry:'Geometry & Spatial Reasoning',number:'Counting, Arithmetic & Number Theory',logic:'Logic & Systematic Reasoning'};
const units=[];
function add(id,strand,title,foundation,pages,prerequisites,ideas,check,why){units.push({id,strand,title,foundation,benchmarkPages:pages,prerequisites,ideas,check,why});}
add('relationships','algebra','Turn words into relationships','m-algebra','2–4',[],[
 'An unknown is a quantity whose value we have not found yet. Give it a meaning before giving it a letter: x might be the number of notebooks, not the cost of a notebook. Write the unit beside your working.',
 'An equation says that two descriptions represent the same amount. Keep it balanced: adding, subtracting, multiplying or dividing by the same non-zero number on both sides preserves equality. Check a proposed answer in the original story, not only in your last line.',
 'For a sum and a difference, remove the difference from the total. The remaining total contains two equal smaller quantities. Alternatively, add the difference to get two copies of the larger quantity. A bar model and an equation describe the same relationship.'
],['Two boxes contain 34 counters altogether. One contains 8 more than the other. What does 34 − 8 represent?',['The contents of the smaller box','Twice the contents of the smaller box','The difference between the boxes'],1,'Removing the extra 8 makes the two amounts equal. Divide that remaining total by 2.'], 'The unknown may change from a count to a length or a price. Choose its meaning again rather than copy the last equation.');
add('percent','algebra','Choose the percentage whole','m-percent','5',['relationships'],[
 'A percentage is a fraction with 100 as its denominator. Always name the whole: 10% of the original price and 10% of the reduced price are usually different amounts.',
 'A charge of p% added to an original amount leaves 100% + p%. A discount of p% leaves 100% − p%. Estimate the direction first. An added charge must make a positive price larger; a discount makes it smaller.',
 'To find the original amount, divide the final amount by the fraction that remains. For successive changes, multiply the remaining factors: keeping 80% and then 90% leaves 72% of the original, not 70%. For two groups with different rates, calculate each group separately before adding.'
],['A price includes a 10% charge on its original amount. Which equation finds the original amount x from a final price of $66?',['0.90x = 66','1.10x = 66','x + 10 = 66'],1,'The final amount is 110% of the original. The charge is not a fixed $10.'], 'A new context can ask for the original whole, a combined total or the amount after two changes. Identify the reference whole at every step.');
add('remainders','algebra','Work backwards through changing amounts','m-remainders','6, 8',['percent'],[
 'Draw the stages in order. A fraction of what remains acts on the amount at that stage, not the amount at the start. After spending 1/4, 3/4 remains. Spending 1/3 of that remainder leaves 2/3 of the new amount.',
 'You can work forwards by multiplying the fractions that remain, or backwards by undoing the last operation first. If 18 is 3/4 of an amount, that amount is 18 ÷ 3 × 4 = 24. If a fixed $5 was then spent, add the $5 back before undoing the fraction.',
 'When quantities are transferred between boxes without any being lost, their total stays fixed. Record each stage in a table. Do not replace “a third of the current group” with a third of the original group.'
],['After spending 1/4 of some money, a child spends $6 and has $12 left. Which quantity is 3/4 of the starting amount?',['$12','$18','$6'],1,'Before spending the $6, the child had $18. That is the remainder after the first purchase.'], 'Reverse both fractional and fixed changes in the correct order. Use a forward check to verify every stage.');
add('simultaneous','algebra','Combine two conditions','m-algebra','3–5',['relationships'],[
 'Two unknown quantities often need two independent conditions. A total count and a total cost give different information. An equation that merely repeats the first condition does not give new information.',
 'Try an all-one-type assumption: if every vehicle had two wheels, how many wheels would there be? Each four-wheel vehicle adds two wheels beyond that baseline. The extra wheels therefore reveal the number of four-wheel vehicles. This is elimination expressed without symbols.',
 'You can also multiply one equation so the coefficient of one unknown matches in both equations, then subtract. In an age problem, everyone ages by the same number of years, so the age difference is unchanged. Ratios of ages do change.'
],['There are 12 bicycles and tricycles altogether, with 29 wheels. What does 29 − 2 × 12 count?',['The number of tricycles','The number of bicycles','The number of all vehicles'],0,'Each tricycle contributes one wheel beyond the all-bicycles baseline.'], 'In a new setting, identify the shared baseline or term to eliminate instead of guessing which numbers to subtract.');
add('ratios','algebra','Ratios with a fixed quantity','m-ratio','2, 5–6',['relationships','remainders'],[
 'A ratio compares quantities using equal-sized units. The unit size is not automatically the same in a before-and-after ratio. First identify what stays fixed: one group, the total or a difference.',
 'If the red counters stay unchanged, match the red parts in both ratios before comparing the blue parts. If counters move between two boxes, the total stays unchanged; express the amount in one box as a fraction of the total before and after.',
 'Equal sharing offers an inverse relationship. If the same stock gives 12 each to one group or 18 each to another, the group sizes are stock/12 and stock/18. Adding the group sizes and dividing the stock by that total finds the share when both groups join.'
],['Counters are moved from A to B without loss. What is unchanged?',['The number in A','The combined total','The ratio A:B'],1,'Moving counters changes the separate amounts but not their combined total.'], 'State the invariant explicitly. A before-and-after ratio is not solved by subtracting ratio numbers unless their units are aligned.');
add('rates','algebra','Combine rates, not completion times','m-rate','7, 9',['relationships','remainders'],[
 'A rate measures output per unit of time. If a machine completes one job in 6 hours, its rate is 1/6 job per hour. Work = rate × time, so time = work ÷ rate.',
 'For workers producing the same kind of output independently at constant rates, add their rates. A drain or a leak subtracts from an inflow rate. Adding two completion times does not describe working together.',
 'Some problems include a starting stock and a quantity that grows or flows in while it is consumed. Use starting stock + growth × time = consumption × time. State the constant-rate assumption. Do not count the growth twice when combining measurements.'
],['One pump fills 1/6 of a tank each hour and another fills 1/3. What is their combined hourly rate?',['1/9 tank','1/2 tank','9 tanks'],1,'Add 1/6 + 1/3 = 1/2 tank per hour. The times 6 and 3 are not the rates.'], 'Identify the common unit before combining data. A changing stock needs a net rate, not just a ratio of completion times.');
add('motion','algebra','Relative motion and average speed','m-rate','3, 5, 7',['rates'],[
 'For objects moving towards each other along one line, the gap closes at the sum of their speeds. For a faster object catching a slower object moving in the same direction, the gap closes at their speed difference. Draw a line and arrows before choosing.',
 'Average speed is total distance divided by total time. For equal distances at different speeds, the slower leg takes longer. The arithmetic mean of the speeds is therefore not generally the journey’s average speed.',
 'When a messenger travels back and forth until two walkers meet, first find the time until the meeting. Multiply that time by the messenger’s constant speed. There is no need to add an endless list of shorter journeys. For moving walkways, add or subtract the walkway speed from the walking speed as appropriate.'
],['Two runners move in the same direction at 8 m/s and 5 m/s. At what rate does the faster runner close a gap?',['13 m/s','3 m/s','40 m/s'],1,'Both advance along the track. The faster runner gains 8 − 5 = 3 metres each second.'], 'Use the diagram to determine direction, and convert all times and distances into compatible units before calculating.');
add('capacity','algebra','Equivalent capacity and whole objects','m-ratio','6',['ratios','simultaneous'],[
 'A shelf that holds 12 large boxes or 20 small boxes has one fixed capacity. Each large box uses 1/12 of the shelf and each small box uses 1/20. The fractions occupied by a mixture add.',
 'You can avoid fractions by measuring in a common small unit: use a capacity divisible by both 12 and 20. A capacity of 60 units makes a large box 5 units and a small box 3 units.',
 'An answer about complete objects must be a whole number. If the available space is 17 units and each object takes 5, only 3 fit; the remaining 2 units cannot hold a fraction of a complete object. Check that the proposed mixture does not exceed capacity.'
],['A shelf fits 10 large books or 25 small books. What fraction of the shelf do 2 large books use?',['2/25','2/10','10/25'],1,'Use the capacity for the same book size: each large book uses 1/10 of the shelf.'], 'Convert different sizes to the same capacity unit, then account for the requirement to fit complete objects.');
add('area','geometry','Compare areas using shared heights','m-area','11, 15',[],[
 'The area of a triangle is half its base times its perpendicular height. A sloping side is not usually the height. Choose a base and identify the perpendicular distance from the opposite vertex to its line.',
 'Triangles whose bases lie along the same straight line and whose opposite vertex is the same have equal heights. Their areas are therefore in the same ratio as their bases. This remains true even when the vertex is not directly above a base segment.',
 'A median joins a triangle’s vertex to the midpoint of the opposite side. It makes two triangles with equal bases and a shared height, so their areas are equal. The triangles need not look alike. To verify, explain which base and height you compared.'
],['Two triangles share a vertex and have bases of 3 cm and 5 cm on the same line. What is the ratio of their areas?',['9:25','3:5','1:1'],1,'They have the same perpendicular height. Only the bases differ.'], 'Look for shared perpendicular distances, including in rotated or subdivided diagrams. Do not measure the picture.');
add('decomposition','geometry','See the hidden area relationship','m-area','11, 15',['area'],[
 'An unfamiliar shaded region can be easier to find by subtracting unshaded pieces from a familiar whole. Write a complete accounting equation before calculating: whole = shaded + unshaded, with no overlaps counted twice.',
 'In a rectangle, a quadrilateral with its top and bottom vertices directly aligned can be divided along that vertical segment. The two resulting triangles have the rectangle’s height as their shared base. Their horizontal heights add to the rectangle’s width, so together they occupy half the rectangle.',
 'For overlapping figures, adding all areas counts their shared region twice. Subtract the overlap once. For a figure made by connecting corners to division points, use consistent equal triangles or scaled coordinates to justify the fraction, rather than trusting visual symmetry alone.'
],['Two squares overlap. Which expression gives their combined covered area?',['Area 1 + area 2','Area 1 + area 2 − overlap','Area 1 + area 2 − twice the overlap'],1,'The overlap was counted twice in the sum, but must appear once in the covered area.'], 'Introduce an auxiliary line only when you can explain what relationship it reveals. The examination figure does not supply every helpful line.');
add('circles','geometry','Curved boundaries and area ratios','m-circles','12–13, 16',['area','decomposition'],[
 'A circle of radius r has circumference 2πr and area πr². A semicircular arc is half a circumference; a semicircle’s full perimeter also includes its straight diameter. Trace the boundary with your finger to decide what is included.',
 'For several semicircular arcs, their total curved length is π/2 times the sum of their diameters. Keep π in the expression until the question asks for a decimal. Internal shared edges are not part of the outside perimeter.',
 'If one circle’s radius is k times another’s, its area is k² times as large. Similar lengths scale once, but areas scale twice. For a shaded square-and-circle region, subtract the full areas using the correct radius: a circle inscribed in a square has diameter equal to the square’s side.'
],['A circle’s radius doubles. What happens to its area?',['It doubles','It becomes four times as large','It is unchanged'],1,'Both factors of r in π × r × r double.'], 'Distinguish a requested curved length from a whole perimeter, and a radius ratio from an area ratio.');
add('angles','geometry','Build an angle argument','m-angles','12, 14',['area'],[
 'Useful starting facts are angles on a straight line (180°), angles around a point (360°), and the angle sum of a triangle (180°). Mark only relationships supported by the words or standard diagram marks.',
 'An equilateral triangle has three 60° angles; a square has 90° corners and a diagonal that bisects a corner. An isosceles triangle has equal base angles. These facts often connect an unfamiliar composite picture to a few small triangles.',
 'For a polygon or a star, trace one continuous route and track how much it turns. Ordinary convex polygon exterior turns total 360°. A five-point star traced by skipping one vertex each time turns through 720°, so its five tip angles total 5 × 180° − 720° = 180°. Explain the route: not every pointed shape has this property.'
],['A triangle has two equal angles and a third angle of 40°. What is each equal angle?',['40°','70°','140°'],1,'The equal angles share 180° − 40° = 140°, so each is 70°.'], 'Rotation, reflection and an extra line change appearance without changing the justified angle relationships.');
add('spatial','geometry','Fold nets and compare cube views','m-solids','17',[],[
 'Opposite faces of a cube never share an edge. In a net, follow a sequence of quarter-turn folds; faces that are far apart on the page are not necessarily opposite after folding.',
 'Keep one face as an anchor. Label its four neighbours in order as you fold the strip. The remaining face closes the cube opposite the anchor. Rotating a whole cube changes the view, not which faces are neighbours or opposites.',
 'When two views show the same numbered face, list the distinct faces seen next to it. If all four neighbours have been identified, the remaining sixth face is opposite it. With fewer neighbours, there may be insufficient information; do not guess a unique answer unless the views determine it.'
],['Four different faces are each seen sharing an edge with face 3. Where is the one remaining face?',['Opposite face 3','Also next to face 3','It depends on the font'],0,'A cube face has exactly four adjacent faces and one opposite face.'], 'Some view questions require orientation as well as adjacency. This unit checks opposite-face reasoning, not every possible decorated-net orientation.');
add('volume','geometry','From cube edges to exposed faces','m-volume','17; spatial extension',[],[
 'A cube with edge e contains e × e × e unit cubes when e is a whole number. To recover an edge from a volume, find the number whose product with itself three times gives that volume. Dividing the volume by 3 does not undo cubing.',
 'Surface area counts exposed square faces, not solid blocks. A cuboid of lengths a, b and c has pairs of faces with areas ab, ac and bc. A cut can remove outside faces and expose new inside faces.',
 'For a solid built from unit cubes, start with six faces per cube and remove two faces for every joined pair: one face from each cube is hidden at the join. For a tunnel or cavity, count all exposed internal faces as well as the outside. Draw layers to keep track.'
],['A cube has volume 64 cm³. Which equation tests whether its edge is 4 cm?',['4 + 4 + 4 = 64','4 × 3 = 64','4 × 4 × 4 = 64'],2,'Volume multiplies three lengths. 4 × 4 × 4 = 64.'], 'The volume bridge supports cube reasoning. Internal exposed-face tasks are supplementary spatial enrichment, not a claimed official DSA requirement.');
add('factors','number','Prime factors and complete factor counts','m-factors','25–26',[],[
 'A factor divides a whole number with no remainder. Pair factors: if a × b = N, both a and b are factors. In a perfect square the middle pair repeats the same number and must be counted only once.',
 'Prime factorisation writes a positive integer as a product of primes. Every factor chooses how many copies of each prime to use. For 2³ × 3², there are 4 choices for the exponent of 2 (0 to 3) and 3 for the exponent of 3 (0 to 2), giving 12 positive factors.',
 'The highest common factor uses the smaller exponent of each common prime. The lowest common multiple uses the larger exponent of every prime present. Include 1 in a count of positive factors; it chooses zero copies of every prime.'
],['Why does 2³ contribute four choices when counting factors?',['Because 2 + 3 = 5','Because the exponent can be 0, 1, 2 or 3','Because 2 is even'],1,'The zero exponent matters: a factor may contain no copies of 2.'], 'Explain the choices in the factor count rather than memorising a formula detached from its meaning.');
add('cycles','number','Remainders, cycles and near-multiples','m-factors','25',['factors'],[
 'A remainder is what is left after making as many complete equal groups as possible. It is at least zero and smaller than the divisor. A remainder equal to the divisor means another complete group can be made.',
 'A number leaving one less than the divisor when divided by several numbers is one less than a common multiple of them. Add one to simplify all conditions at once. For other remainder conditions, list candidates systematically and check every condition.',
 'Repeated multiplication may produce a cycle of remainders. List the first few, identify a return to the starting state, and locate a distant term by dividing its position by the cycle length. A position divisible by the cycle length uses the last position, not the first.'
],['A number leaves remainders 2, 3 and 4 when divided by 3, 4 and 5. What is true of the number plus 1?',['It is divisible by 3, 4 and 5','It is prime','It is divisible by 2 only'],0,'Adding 1 completes the next group for each divisor.'], 'First establish the cycle, then map the term number to it. The base and divisor can change.');
add('counting','number','Count systematically without duplicates','m-proof','20–26; counting bridge',[],[
 'Decide what counts as one object. A handshake between A and B is the same handshake as B and A. A two-digit number 24 is different from 42. Whether order matters changes the count.',
 'For one pair from n people, person 1 contributes n − 1 new pairs, person 2 contributes n − 2, and so on. Counting every person’s partners instead gives n(n − 1), but counts each pair twice. Divide by 2 only because you have explained that duplication.',
 'A rectangle in a complete grid is determined by two vertical boundaries and two horizontal boundaries. Count choices of each pair, then multiply. For restrictions, such as pairs only between two clubs, count permitted cases directly rather than applying an unrestricted formula.'
],['Five people each play every other person once. Why is 5 × 4 not the match total?',['It counts each match twice','It forgets one player','It counts each match four times'],0,'A match appears in each participant’s list.'], 'Test your method on a small case and account for every restriction. A change from unordered pairs to ordered positions changes the model.');
add('digits','number','Place-value patterns and palindromes','m-number','18, 26',['counting'],[
 'Write a two-digit number with tens digit a and units digit b as 10a + b. Reversing it gives 10b + a, so the difference is 9(a − b). Leading digits cannot be zero.',
 'In a palindrome, later digits are fixed by earlier digits. A four-digit palindrome has the form abba: 9 choices for a and 10 for b. A divisibility restriction links those choices; they are no longer independent.',
 'For divisibility by 3 or 9, use the digit sum. In a three-digit palindrome aba, the sum is 2a + b. List possible b values for each a and do not exclude 0 from an internal digit. Keep cases complete and disjoint.'
],['How many digits can be freely chosen in a four-digit palindrome abba?',['One','Two','Four'],1,'Once a and b are chosen, the last two digits are fixed. The first digit a cannot be zero.'], 'A new restriction needs new casework. Do not carry an unrestricted count into a divisible-palindrome question.');
add('sums','number','Group terms before calculating','m-number','20–21, 27',[],[
 'Look for terms that pair to the same total. In an arithmetic sequence, the first plus last equals the second plus second-last. The total is number of terms × (first + last) ÷ 2.',
 'Count inclusive endpoints carefully: the integers from 8 to 17 contain 17 − 8 + 1 = 10 terms. For alternating signs, group complete pairs and then account for any unpaired term.',
 'The difference of two squares factors as a² − b² = (a − b)(a + b). This can turn long multiplication into a short product. A sum of square numbers does not obey the ordinary arithmetic-sequence formula; use a justified square-sum identity or a separate construction.'
],['How many whole-number terms are there from 14 to 23 inclusive?',['9','10','11'],1,'Both endpoints count: 23 − 14 + 1 = 10.'], 'Choose a grouping that follows the signs and term pattern, then check a short version before extending it.');
add('patterns','number','Build and test a general rule','m-proof','22',['sums'],[
 'Record a few small cases with their construction rule. If a new square shares one complete side with the previous square, it adds three matchsticks, not four. Start with the first figure, then count the additions.',
 'A rule should explain the construction, not merely fit the first three numbers. A linear pattern has a constant first difference; a growing difference needs a different model. A few numbers without a stated rule can have many possible continuations.',
 'For blocks of increasing sizes, cumulative totals locate a distant position. Complete blocks of sizes 1, 2, …, k use k(k + 1)/2 places. Find the largest completed block, then count only the required part of the next block.'
],['A row starts with one square of 4 sticks. Every additional square shares one side. Why is the count for n squares 4 + 3(n − 1)?',['There are n − 1 additions after the first square','Every square uses 3 sticks','There are n additions'],0,'The first figure is already counted. Only later additions share a side.'], 'The rule is stated in each question so an answer is mathematically determined rather than based on guessing the intended next term.');
add('spirals','number','Track a spiral by complete turns','m-proof','23–24',['sums','patterns'],[
 'A square spiral can be built with right, up, left and down movements. Its segment lengths are 1, 1, 2, 2, 3, 3, … . Record direction and length together. Mixing up a turn can change the sign of a coordinate.',
 'To locate a number, count the steps from 1 to it: the number N is N − 1 steps from the centre. Group complete pairs of segments or complete rings, then track only the unfinished part.',
 'For a drawn spiral with a fixed total length, find the total of complete segments before locating the final partial segment. The length of the last full segment and the length actually drawn on the unfinished segment are not necessarily equal.'
],['In a spiral beginning with number 1 at the centre, how many unit moves are needed to reach number 10?',['10','9','11'],1,'The starting cell already contains 1, so reaching 10 requires 9 moves.'], 'Our spiral questions specify the starting direction and turn order. Use those conventions, not a remembered picture.');
add('cases','logic','Use every condition and test cases','m-proof','18',[],[
 'In a logic problem, a plausible answer is not enough: it must satisfy every condition at the same time. List the possible cases, then mark each statement true or false within each case.',
 '“Exactly one statement is true” is a count of true statements, not a direction to believe the first speaker. Reject cases with zero or two true statements. If more than one case survives, more information is needed.',
 'In a column-addition puzzle, carry values link neighbouring columns. Work from a constrained column and keep a record of used digits. Different letters mean different digits only when the question states it; a leading digit must not be zero.'
],['Exactly one of three statements is true. A proposed case makes two statements true. What should you do?',['Keep it because at least one is true','Reject that case','Ignore the second statement'],1,'Exactly one excludes cases with two true statements.'], 'Record a short reason for rejecting each alternative. This is stronger evidence than trying answer choices until one is accepted.');
add('invariants','logic','What stays unchanged?','m-proof','26; reasoning extension',['counting','factors'],[
 'An invariant is a property that a permitted move does not change. Adding or subtracting an even number preserves whether a whole number is odd or even. An impossible parity can rule out a target before a long search.',
 'A switch numbered n is flipped once for every positive factor of n. Factors usually come in different pairs, producing an even number of flips. A perfect square has one unpaired middle factor, so it receives an odd number of flips.',
 'To guarantee a repeated category, consider the worst case first. With c categories, you might choose one of each before any repetition. A guarantee of two in the same category therefore needs c + 1 choices, assuming every category is available.'
],['Starting from an even integer, every move adds 6 or subtracts 4. Can an odd integer be reached?',['Yes','No','Only after 10 moves'],1,'Both changes are even, so parity remains even.'], 'Use an invariant to prove impossibility; a failed short search alone does not prove there is no solution.');
add('bounds','logic','Prove a maximum or minimum','m-proof','18; optimisation extension',['cases','relationships'],[
 'An optimisation answer needs two parts: a bound that no valid case can beat, and a valid construction that achieves it. Finding one attractive example proves only that the example is possible.',
 'When buying complete packs within a budget, list the possible numbers of the larger pack. For each, use the remaining budget to buy the greatest possible number of smaller packs. Rounding matters: the lowest unit price need not give the best affordable combination.',
 'For overlapping groups in a fixed population, use a total-count equation. A lower bound comes from considering the greatest possible overlap or the least possible overlap, then checking that all remaining group sizes are non-negative integers.'
],['You found an affordable pack combination giving 18 items. What is still needed to prove 18 is the maximum?',['Show that no allowed combination gives more','Try the same combination again','Round its cost'],0,'A construction proves attainability; a complete comparison or upper bound proves optimality.'], 'An exhaustive search must have justified limits. Explain why the list covers all valid possibilities.');
units.find(u=>u.id==='counting').ideas.push('For regions made by lines, a new line crossing j earlier lines at distinct points is split into j + 1 pieces, creating j + 1 new regions. Start with 1 region and add the gains. Parallel lines remove intersections; three lines meeting together also reduce the count.');
units.find(u=>u.id==='sums').ideas.push('For consecutive squares, write S(n) = 1² + 2² + … + n² = n(n+1)(2n+1)/6. One justification adds (k+1)³ − k³ = 3k² + 3k + 1 for k from 1 to n: the left side collapses, and the ordinary sum 1 + … + n is already known. To sum squares from a to b, calculate S(b) − S(a−1), not S(b−a+1).');
units.find(u=>u.id==='decomposition').ideas.push('An algebraic method for corner-to-side constructions is to scale a square to side 1. With top-left (0,0), top-right (1,0), bottom-right (1,1), a line from (0,0) to (1,t) has y = tx. The adjacent line from (1,0) to (1−t,1) has x = 1−ty. Solve both together. A quarter-turn about the centre gives the next intersection; the differences in the two coordinates give the sides of a right triangle whose hypotenuse is the central square’s side. Its squared length is (1−t)²/(1+t²). Scaling back multiplies the area by the original side squared. This is an optional algebraic route; a justified area decomposition is equally valid.');
const stages=[{until:'2026-11',title:'Repair and build',detail:'Secure the reference whole, equations, cube meaning and systematic counting.'},{until:'2027-02',title:'Connect methods',detail:'Develop rates, number theory, geometry and unfamiliar transfer.'},{until:'2027-04',title:'Choose independently',detail:'Mix methods without topic labels and revisit ideas after delays.'},{until:'2027-06',title:'Practise full papers',detail:'Use reserved papers, review reasoning, and verify with external unseen work.'}];
root.MochiEntranceData={version:1,goalMonth:'2027-06',target:85,strands,units,stages,scope:'Working benchmark: the supplied PD STEM Education NUS High DSA preparation booklet (2024), not an official entrance paper. Original lessons and figures; some explicitly labelled foundation bridges and extensions. June 2027 is a preparation goal, not an announced test date.'};
if(typeof module!=='undefined')module.exports=root.MochiEntranceData;
})(typeof globalThis!=='undefined'?globalThis:this);
