/* DSA-benchmarked learning path. All teaching, marking, diagrams and ink work offline. */
(function(root){
'use strict';
const E=root.MochiEntrance,F=root.MochiEntranceFigures,$=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let view={kind:'home'},host=null,paused=false,pen=false,pointer=null,strokes=[],message='',exampleForm=0,lastParent='';
const data=()=>E.init(S),visible=()=>!!host&&!host.hidden;
function drawing(ink){return `<svg viewBox="0 0 800 320" class="ep-saved-ink" aria-label="Saved handwritten working">${(ink||[]).map(s=>`<polyline points="${s.map(([x,y])=>`${x*800},${y*320}`).join(' ')}" fill="none" stroke="#29232f" stroke-width="2.4" stroke-linecap="round"/>`).join('')}</svg>`;}
function capture(persist=false){
 if(paused||!visible())return;
 if(view.kind==='practice'&&data().draft&&$('epAnswer')){E.touchDraft(data(),{answer:$('epAnswer').value,working:$('epWorking').value,strokes,guess:$('epGuess')?.checked});const a=data().attempts.find(x=>x.id===data().draft.id);if(a?.correct&&$('epWorking').value!==(a.responses.at(-1).working||'')){a.reflection=$('epWorking').value.slice(0,6000);a.reflectionInk=E.ink(strokes);a.reflectionAt=Date.now();}}
 if(view.kind==='paper'&&$('epAnswer')){const p=data().papers[view.paper];if(p&&!p.submittedAt)E.savePaperAnswer(data(),p.id,p.index,{answer:$('epAnswer').value,working:$('epWorking').value,strokes});}
 if(view.kind==='lesson'&&$('epLessonNotes')){const l=E.lesson(data(),view.unit);l.notes=$('epLessonNotes').value.slice(0,6000);l.updatedAt=Date.now();}
 if(persist)save(S);
}
function leave(){
 if(!visible()||paused)return;capture();if(view.kind==='paper')E.interruptPaper(data(),view.paper);host.hidden=true;document.body.classList.remove('entrance-active','entrance-paper');save(S);
}
function open(kind='home',id){
 if(!host||paused)return;
 capture();if(view.kind==='paper'&&kind!=='paper'&&kind!=='results')E.interruptPaper(data(),view.paper);
 root.MochiSciencePathUI?.leave();if(typeof courseLeave==='function')courseLeave();if(typeof scDraft==='function')scDraft();if(typeof scAbort==='function')scAbort();if(typeof focusClose==='function')focusClose(false);
 $('viewMaths').style.display='none';$('viewScience').hidden=true;$('viewMap').hidden=true;$('viewRoom').style.display='none';$('viewCourse').hidden=true;$('focusDock').hidden=true;$('courseReturn').hidden=true;
 if(typeof SCI!=='undefined')SCI.view='maths';document.body.classList.remove('science-active','course-active');document.body.classList.add('entrance-active');host.hidden=false;
 $('subjectMaths').setAttribute('aria-pressed','true');$('subjectScience').setAttribute('aria-pressed','false');
 view={kind,unit:['lesson','practice'].includes(kind)?id:null,paper:['paper','results'].includes(kind)?id:null};message='';pointer=null;
 if(kind==='lesson'){if(data().draft&&!data().attempts.find(a=>a.id===data().draft.id)?.correct)E.help(data());E.visit(data(),id,E.lesson(data(),id).page);exampleForm=0;}
 if(kind==='practice'&&!data().draft)E.startPractice(data(),id);
 if(kind==='paper'&&!data().papers[id])E.startPaper(data(),id);
 document.body.classList.toggle('entrance-paper',kind==='paper');render();save(S);document.dispatchEvent(new Event('mochi:activity'));
 const skip=document.querySelector('.skip-link');if(skip){skip.href='#epTitle';skip.textContent='Skip to the learning activity';}
 $('epTitle')?.focus({preventScroll:true});
}
function nextRecommended(){const r=E.recommend(S);if(r.kind==='paper'){open('paper',r.paper);return;}if(r.kind==='resume'){open('practice',data().draft.unit);return;}if(r.kind==='mixed'){open('papers');return;}if(r.kind==='learn'){open('lesson',r.unit);return;}beginPractice(r.unit,r.kind==='recall'?'recall':undefined);}
function beginPractice(id,phase){
 const d=data();if(d.draft&&d.draft.unit!==id){const old=d.attempts.find(a=>a.id===d.draft.id);if(!old?.correct&&!confirm('A question and its working are saved. Start a different question instead? The recorded answers will remain, but this unsent draft will be replaced.')){open('practice',d.draft.unit);return;}E.finishPractice(d);}
 if(d.draft&&d.attempts.find(a=>a.id===d.draft.id)?.correct)E.finishPractice(d);
 E.startPractice(d,id,{phase});open('practice',id);
}
function header(title,kicker='YOUR MATHEMATICS PATH'){return `<div class="ep-heading"><div><p class="ep-kicker">${esc(kicker)}</p><h1 id="epTitle" tabindex="-1">${esc(title)}</h1></div><span class="ep-target">June 2027<br><small>Preparation goal</small></span></div>`;}
function render(){
 if(!host||paused)return;
 const nav=`<nav class="ep-nav" aria-label="Mathematics pathway"><button id="epHome" ${view.kind==='home'?'aria-current="page"':''}>My path</button><button id="epLessons" ${view.kind==='lessons'||view.kind==='lesson'?'aria-current="page"':''}>Lessons</button><button id="epPapers" ${view.kind==='papers'||view.kind==='paper'?'aria-current="page"':''}>Papers</button><button id="epFoundations">Foundation classroom</button></nav>`;
 let html='';if(view.kind==='home')html=home();else if(view.kind==='lessons')html=lessonList();else if(view.kind==='lesson')html=lessonView();else if(view.kind==='practice')html=practiceView();else if(view.kind==='papers')html=paperList();else if(view.kind==='paper')html=paperView();else if(view.kind==='results')html=resultsView();
 document.body.classList.toggle('entrance-paper',view.kind==='paper');host.innerHTML=nav+html;wireNavigation();wire();paintParent();
}
function home(){
 const d=data(),r=E.recommend(S),report=E.report(d),u=r.unit&&E.unit(r.unit),active=r.kind==='paper'?E.paperDefinitions.find(p=>p.id===r.paper)?.title:u?.title||'Mixed reasoning';
 return header('Learn deeply. Solve independently.')+`<p class="ep-lead">Build the methods behind unfamiliar entrance-style questions. Learn an idea, try it, explain it, and return to it later.</p><section class="ep-next"><p class="ep-kicker">NEXT STEP</p><h2>${esc(active)}</h2><p>${esc(r.reason)}</p><button id="epContinue" class="ep-primary">${r.kind==='learn'?'Explore this lesson':r.kind==='paper'?'Resume saved paper':r.kind==='resume'?'Resume my question':'Continue my path'}</button></section><div class="ep-evidence-strip"><span><strong>${report.units.filter(x=>x.taught).length}/24</strong> methods explored</span><span><strong>${report.units.filter(x=>x.transfer).length}</strong> methods with independent transfer practice</span><span><strong>${report.units.filter(x=>x.delayed).length}</strong> revisited after a week</span></div><section class="ep-two-col"><div class="ep-card"><h2>A starting point, not a judgement</h2><p>Two short six-question checks show what needs teaching. Unfamiliar questions are expected. Results do not estimate an admission chance.</p><button data-start-paper="baseline-a">${d.papers['baseline-a']?.submittedAt?'Review check A':d.papers['baseline-a']?'Resume check A':'Starting-point check A'}</button><button data-start-paper="baseline-b">${d.papers['baseline-b']?.submittedAt?'Review check B':d.papers['baseline-b']?'Resume check B':'Starting-point check B'}</button></div><div class="ep-card"><h2>Our target</h2><p>Work towards 85% on three reserved mixed papers, broad coverage and explanations reviewed by an adult. Confirm progress using external unseen work.</p><p class="ep-note">${report.qualifyingPapers}/3 internal paper targets recorded. This is a training goal, not a school cutoff or a readiness percentage.</p><button id="epOpenProgress">See the evidence</button></div></section><details class="ep-details"><summary>The route to June</summary><div class="ep-timeline">${E.D.stages.map(s=>`<div><strong>${esc(s.title)}</strong><small>Planning window through ${esc(s.until)}</small><p>${esc(s.detail)}</p></div>`).join('')}</div><p>Progress determines the pace. Earlier foundations and the September SPERS goal remain available; the new maths preparation goal is June.</p></details><p class="ep-scope">${esc(E.D.scope)}</p>`;
}
function lessonList(){const d=data();return header('Methods that travel with you.')+`<p class="ep-lead">Each lesson includes an explanation, worked examples and a concept check. Existing foundation work guides recommendations; it is not relabelled as entrance-test mastery.</p>${Object.entries(E.D.strands).map(([key,title])=>`<section class="ep-strand"><h2>${esc(title)}</h2><div class="ep-lesson-grid">${E.D.units.filter(u=>u.strand===key).map(u=>{const e=E.evidence(d,u.id);return `<button class="ep-lesson-card" data-lesson="${u.id}"><strong>${esc(u.title)}</strong><span>${esc(e.stage)}</span><small>${e.apply} independent application · ${e.transfer} transfer practice · ${e.delayed} delayed</small></button>`;}).join('')}</div></section>`).join('')}`;}
function lessonView(){
 const u=E.unit(view.unit),l=E.lesson(data(),u.id),titles=['Understand the idea','See the method working','Check the idea'];let body='';
 if(l.page===0)body=`<article class="ep-teaching">${u.ideas.map(p=>`<p>${esc(p)}</p>`).join('')}<aside><strong>What should transfer?</strong><p>${esc(u.why)}</p></aside></article>`;
 if(l.page===1){const q=E.B.make(u.id,exampleForm,104729+E.D.units.indexOf(u)*7919);data().seen[q.fingerprint]=data().seen[q.fingerprint]||Date.now();body=`<label class="ep-select-label" for="epExample">Worked example</label><select id="epExample"><option value="0" ${exampleForm===0?'selected':''}>Start with the relationship</option><option value="1" ${exampleForm===1?'selected':''}>Apply the method</option><option value="2" ${exampleForm===2?'selected':''}>Change the problem structure</option></select><article class="ep-question-sheet"><p class="ep-question-text">${esc(q.text)}</p>${F.diagram(q.figure,q.id+'-worked',true)}<ol class="ep-worked">${q.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p><strong>Answer: ${esc(q.answerLabel)} ${esc(q.suffix||'')}</strong></p><p class="ep-note">This is teaching, not independent evidence. Another valid method is welcome.</p></article>`;}
 if(l.page===2){const c=u.check,correct=l.conceptChoice===c[2];body=`<div class="ep-concept"><p class="ep-question-text">${esc(c[0])}</p><div class="ep-choices">${c[1].map((x,i)=>`<button data-concept="${i}" aria-pressed="${l.conceptChoice===i}">${esc(x)}</button>`).join('')}</div><p class="ep-feedback" role="status">${l.conceptChoice<0?'Choose and explain the relationship in your own words.':correct?'That relationship is correct. '+esc(c[3]):'Revisit the relationship. '+esc(c[3])}</p></div>`;}
 return header(u.title,E.D.strands[u.strand])+`<div class="ep-lesson-tabs" role="group" aria-label="Lesson sections">${titles.map((t,i)=>`<button data-page="${i}" aria-pressed="${l.page===i}">${i+1}. ${t}</button>`).join('')}</div>${body}<div class="ep-actions"><button id="epLessonPrevious" ${l.page===0?'disabled':''}>Previous</button>${l.page<2?'<button id="epLessonNext" class="ep-primary">Next section</button>':`<button id="epCompleteLesson" class="ep-primary" ${l.visited.length<3||l.conceptChoice!==u.check[2]?'disabled':''}>Finish lesson & try guided practice</button>`}</div>${data().draft?'<button id="epResumeDraft">Resume my saved question</button>':''}<details class="ep-details"><summary>My lesson notes</summary><textarea id="epLessonNotes" maxlength="6000" rows="4" aria-label="Lesson notes">${esc(l.notes)}</textarea><p>Notes are saved. Reading and concept-check completion measure exposure, not mastery.</p></details><details class="ep-details"><summary>Prerequisites and benchmark mapping</summary><p>${u.prerequisites.length?'Builds on: '+u.prerequisites.map(id=>esc(E.unit(id).title)).join('; '):'An entry point into this strand.'}</p><p>Working benchmark pages: ${esc(u.benchmarkPages)}. Original teaching, not copied exercises or an official syllabus.</p><button data-foundation="${u.foundation}">Open related foundation lesson</button></details>`;
}
function editor(q,saved={},paper=false,disabled=false){strokes=E.ink(saved.strokes||[]);return `<div class="ep-answer-area"><label for="epAnswer">Your answer${q.suffix?' ('+esc(q.suffix)+')':''}</label>${q.choices?`<div class="ep-choices">${q.choices.map(x=>`<button data-answer="${esc(x)}" aria-pressed="${saved.answer===x}" ${disabled?'disabled':''}>${esc(x)}</button>`).join('')}</div>`:''}<input id="epAnswer" ${q.choices?'class="ep-choice-value"':''} aria-label="Your answer" value="${esc(saved.answer||'')}" type="text" inputmode="text" autocomplete="off" maxlength="180" ${disabled?'disabled':''}><p class="ep-note">Fractions such as 3/4 or 1 1/2 are accepted. Use π or pi for an exact circle expression.</p><div class="ep-input-switch" role="group" aria-label="Working input"><button id="epKeyboard" aria-pressed="${!pen}">Keyboard</button><button id="epStylus" aria-pressed="${pen}">Stylus</button></div><label for="epWorking">My reasoning and checks <small>(saved, not automatically graded)</small></label><textarea id="epWorking" rows="4" maxlength="6000" placeholder="Represent the relationship, show your steps, then check.">${esc(saved.working||'')}</textarea><div id="epInkArea" ${pen?'':'hidden'}><label class="ep-check"><input type="checkbox" id="epPenOnly" checked> Pen only; uncheck to draw with a finger</label><canvas id="epCanvas" width="800" height="320" aria-label="Saved handwriting pad"></canvas><button id="epUndoInk">Undo stroke</button><button id="epClearInk">Clear drawing</button></div>${!paper?`<label class="ep-check"><input type="checkbox" id="epGuess" ${saved.guess?'checked':''} ${disabled?'disabled':''}> I guessed or received help outside the app</label>`:''}</div>`;}
function practiceView(){
 const v=data().draft;if(!v){view={kind:'home'};return home();}view.unit=v.unit;const q=E.question(v),a=data().attempts.find(x=>x.id===v.id),u=E.unit(v.unit),done=!!a?.correct;
 const status=done?(a.independent&&!a.seenBefore?'Correct on the first answer without recorded help.':a.independent?'Correct familiar practice.':'Correct after support or revision.'):'',phase={guided:'Guided practice',apply:'Independent application',transfer:'Transfer practice',recall:'Delayed retrieval'}[v.phase];
 let feedback=message||status;if(a&&!a.correct&&!message)feedback=a.responses.length>=2?'Two attempts need a closer look. Revisit the lesson or open the worked solution, then try a fresh question.':'Not yet. Check your representation, calculation and units. You can revise.';
 return header(u.title,phase)+`<article class="ep-question-sheet"><p class="ep-question-text">${esc(q.text)}</p>${F.diagram(q.figure,q.id)}${editor(q,v,false,done)}<div class="ep-actions">${done?'<button id="epNextPractice" class="ep-primary">Next learning step</button><button id="epMorePractice">Another question in this method</button>':'<button id="epCheckAnswer" class="ep-primary">Check my answer</button><button id="epHint">A hint</button><button id="epReveal">Show the worked solution</button>'}</div>${!done&&(v.revealed||(a?.responses.length||0)>=2)?'<button id="epFreshGuided">Try a fresh guided question</button>':''}<p id="epFeedback" class="ep-feedback" role="status">${esc(feedback)}</p><div id="epSupport">${v.revealed?`<ol>${q.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>`:''}</div></article><div class="ep-actions"><button id="epRevisitLesson">Revisit this lesson</button><button id="epSaveHome">Save & return to my path</button><button id="epPrintPractice">Print a mixed practice set</button></div><p class="ep-note">${v.phase==='guided'?'Guided work is recorded as supported. ':''}A correct answer does not validate the explanation. ${v.seenBefore?'This exact question has appeared before; it is not new independent evidence.':'New numerical variants and new problem structures are tracked separately.'}</p>`;
}
function paperList(){
 const d=data();return header('Try it without a topic label.')+`<p class="ep-lead">The two starting checks are short and untimed. The three mixed papers each contain 24 questions with a 75-minute practice limit. These are original training formats, not the school’s announced test format.</p><div class="ep-paper-grid">${E.paperDefinitions.map(p=>{const saved=d.papers[p.id],score=saved?.submittedAt?E.scorePaper(d,p.id):null;return `<article class="ep-card"><h2>${esc(p.title)}</h2><p>${p.units.length} questions · ${p.minutes?p.minutes+' minutes':'untimed'}</p><p>${score?`${score.correct}/${score.total} · ${Math.round(score.percent)}%` : saved?'Already opened: resume with the original deadline.':'Reserved: questions have not been displayed in this pathway.'}</p><button data-start-paper="${p.id}" class="ep-primary">${score?'Review my paper':saved?'Resume':'Start'}</button>${score?`<p class="ep-note">${esc(score.status)}</p>`:''}</article>`;}).join('')}</div><details class="ep-details"><summary>How paper evidence is used</summary><p>Feedback and solutions appear only after submission. You can edit answers and mark questions for later. Leaving for a lesson or pausing converts the form to supported practice. The clock does not reset after reloading or closing a tab.</p><p>Each reserved form counts once. An opened or submitted paper is not presented as unseen again. The 85% target needs all three timed, independent forms, broad strand coverage, reviewed explanations and an external cross-check. It is not an admissions cutoff.</p></details>`;
}
function paperView(){
 const p=data().papers[view.paper];if(!p){view={kind:'papers'};return paperList();}if(p.submittedAt){view={kind:'results',paper:p.id};return resultsView();}
 const qs=E.paperQuestions(p.id),q=qs[p.index],def=E.paperDefinitions.find(x=>x.id===p.id),saved=p.answers[p.index]||{};
 return header(def.title,def.kind==='baseline'?'STARTING-POINT CHECK':'INDEPENDENT MIXED PAPER')+`<div class="ep-paper-meta"><strong>Question ${p.index+1} of ${qs.length}</strong><span id="epPaperClock" role="timer">${p.deadline?'Time remaining':'Untimed'}</span><span>${p.assisted||p.interrupted?'Supported practice':'No hints or feedback until submission'}</span></div><div class="ep-paper-map" aria-label="Question navigation">${qs.map((_,i)=>`<button data-paper-index="${i}" aria-label="Question ${i+1}${p.answers[i]?.answer?' answered':''}${p.flags.includes(i)?', marked for later':''}" ${p.index===i?'aria-current="step"':''} data-answered="${!!p.answers[i]?.answer}">${i+1}${p.flags.includes(i)?' *':''}</button>`).join('')}</div><article class="ep-question-sheet"><p class="ep-question-text">${esc(q.text)}</p>${F.diagram(q.figure,q.id)}${editor(q,saved,true)}<div class="ep-actions"><button id="epPaperPrev" ${p.index===0?'disabled':''}>Previous</button><button id="epPaperFlag">${p.flags.includes(p.index)?'Unmark':'Mark for later'}</button><button id="epPaperNext" ${p.index===qs.length-1?'disabled':''}>Next</button><button id="epSubmitPaper" class="ep-primary">Submit paper</button></div><p class="ep-note" id="epPaperSave">Answers and working save as you go. Submission freezes the paper.</p></article><button id="epPausePaper">Pause & use as practice</button><p class="ep-scope">Original practice format; not an official NUS High examination. The timer continues if this page is hidden.</p>`;
}
function resultsView(){
 const score=E.scorePaper(data(),view.paper);if(!score){view={kind:'papers'};return paperList();}const p=E.paperDefinitions.find(x=>x.id===view.paper);
 return header('Review the reasoning, not just the score.')+`<section class="ep-result-summary"><h2>${esc(p.title)}</h2><p class="ep-result-number">${score.correct}<small> / ${score.total}</small></p><p>${Math.round(score.percent)}% · ${esc(score.status)}</p><p>${score.unseen?'First exposure':'Previously exposed'} · ${score.independent?'No recorded help':'Support or interruption recorded'} · ${score.timed?'Within the practice limit':score.kind==='baseline'?'Untimed starting check':'Not a qualifying timed result'}</p></section><div class="ep-evidence-strip">${Object.entries(score.byStrand).filter(([,v])=>v.total).map(([k,v])=>`<span><strong>${v.correct}/${v.total}</strong>${esc(E.D.strands[k])}</span>`).join('')}</div><section class="ep-review-list">${score.results.map((a,i)=>`<details><summary>Question ${i+1} · ${a.correct?'Correct answer':a.blank?'Not answered':'Revisit'} · ${esc(E.unit(a.unit).title)}</summary><p>${esc(a.question)}</p><p><strong>Your answer:</strong> ${esc(a.answer||'Blank')}</p><p><strong>Your working:</strong> ${esc(a.working||'No typed working recorded.')}</p>${a.strokes.length?drawing(a.strokes):''}<p><strong>Answer:</strong> ${esc(a.reference)}</p><ol>${a.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><button data-lesson="${a.unit}">Learn this method</button><p class="ep-note">Review your explanation with an adult. A numerical match alone is not a reasoning grade.</p></details>`).join('')}</section><button id="epContinue" class="ep-primary">Choose my next learning step</button>`;
}
function wireNavigation(){
 $('epHome').onclick=()=>open('home');$('epLessons').onclick=()=>open('lessons');$('epPapers').onclick=()=>open('papers');$('epFoundations').onclick=()=>{leave();root.courseOpen('maths');};
 for(const b of host.querySelectorAll('[data-lesson]'))b.onclick=()=>open('lesson',b.dataset.lesson);
 for(const b of host.querySelectorAll('[data-foundation]'))b.onclick=()=>{leave();root.courseOpen('maths',b.dataset.foundation);};
 for(const b of host.querySelectorAll('[data-start-paper]'))b.onclick=()=>{
  capture();const id=b.dataset.startPaper,p=data().papers[id],other=Object.values(data().papers).find(x=>!x.submittedAt&&x.id!==id);
  if(other){message='Finish the saved paper before opening another.';open('paper',other.id);return;}
  if(p?.submittedAt){open('results',id);return;}
  if(!p&&!confirm('Start this reserved form now? Opening it records exposure. Mixed papers have a 75-minute practice limit; the short starting checks are untimed.'))return;
  E.startPaper(data(),id);open('paper',id);
 };
}
function wire(){
 if($('epContinue'))$('epContinue').onclick=nextRecommended;
 if($('epOpenProgress'))$('epOpenProgress').onclick=()=>{open('lessons');};
 if(view.kind==='lesson'){
  const l=E.lesson(data(),view.unit);for(const b of host.querySelectorAll('[data-page]'))b.onclick=()=>{capture();E.visit(data(),view.unit,+b.dataset.page);render();save(S);};
  if($('epExample'))$('epExample').onchange=()=>{exampleForm=+$('epExample').value;render();save(S);};
  for(const b of host.querySelectorAll('[data-concept]'))b.onclick=()=>{E.concept(data(),view.unit,+b.dataset.concept);render();save(S);};
  $('epLessonPrevious').onclick=()=>{capture();E.visit(data(),view.unit,l.page-1);render();save(S);};
  if($('epLessonNext'))$('epLessonNext').onclick=()=>{capture();E.visit(data(),view.unit,l.page+1);render();save(S);};
  if($('epCompleteLesson'))$('epCompleteLesson').onclick=()=>{capture();if(E.complete(data(),view.unit)){const id=view.unit;save(S);beginPractice(id,'guided');}};
  if($('epResumeDraft'))$('epResumeDraft').onclick=()=>open('practice',data().draft.unit);
  $('epLessonNotes').oninput=()=>capture(true);
 }
 if(view.kind==='practice'){
  wireEditor();
  if($('epCheckAnswer'))$('epCheckAnswer').onclick=()=>{
   capture();const result=E.respond(data());if(!result.ok){message=result.reason;render();return;}
   const a=result.attempt;message=a.correct?'Your answer checks out. Explain why your method works.':result.needsLesson?'Two attempts need a closer look. Open the lesson or worked solution before trying a fresh problem.':'Not yet. Check the relationship, calculation and units, then revise.';
   if(a.phase==='guided'&&root.MochiPlanner){const d=MochiPlanner.day(MochiPlanner.init(S),'maths');d.exitIds=[...new Set([...d.exitIds,'entrance:'+a.id])].slice(-8);d.updatedAt=Date.now();}
   save(S);render();
  };
  if($('epHint'))$('epHint').onclick=()=>{capture();E.help(data());$('epSupport').innerHTML='<p>'+esc(E.unit(view.unit).ideas[0])+'</p><p>'+esc(E.unit(view.unit).why)+'</p>';save(S);};
  if($('epReveal'))$('epReveal').onclick=()=>{capture();E.help(data(),true);render();save(S);};
  if($('epNextPractice'))$('epNextPractice').onclick=()=>{capture();E.finishPractice(data());save(S);nextRecommended();};
  if($('epMorePractice'))$('epMorePractice').onclick=()=>{capture();const id=view.unit;E.finishPractice(data());beginPractice(id);};
  if($('epFreshGuided'))$('epFreshGuided').onclick=()=>{capture();const id=view.unit;E.finishPractice(data());beginPractice(id,'guided');};
  $('epRevisitLesson').onclick=()=>{capture();E.help(data());open('lesson',view.unit);};$('epSaveHome').onclick=()=>open('home');$('epPrintPractice').onclick=printPractice;
 }
 if(view.kind==='paper'){
  wireEditor();const p=data().papers[view.paper],qs=E.paperQuestions(p.id);
  const go=i=>{capture();p.index=i;p.updatedAt=Date.now();render();save(S);};
  for(const b of host.querySelectorAll('[data-paper-index]'))b.onclick=()=>go(+b.dataset.paperIndex);
  $('epPaperPrev').onclick=()=>go(Math.max(0,p.index-1));$('epPaperNext').onclick=()=>go(Math.min(qs.length-1,p.index+1));
  $('epPaperFlag').onclick=()=>{capture();p.flags=p.flags.includes(p.index)?p.flags.filter(x=>x!==p.index):[...p.flags,p.index];render();save(S);};
  $('epSubmitPaper').onclick=()=>{capture();const blanks=qs.filter((_,i)=>!p.answers[i]?.answer.trim()).length;if(!confirm(`Submit this paper${blanks?' with '+blanks+' unanswered question(s)':''}? You cannot edit it after submission.`))return;E.submitPaper(data(),p.id);save(S);open('results',p.id);};
  $('epPausePaper').onclick=()=>{capture();if(!confirm('Pause and continue as supported practice? The paper will no longer count as an independent timed check.'))return;E.interruptPaper(data(),p.id);open('home');};
  tickPaper();
 }
 requestAnimationFrame(drawInk);
}
function wireEditor(){
 $('epAnswer').oninput=$('epWorking').oninput=()=>capture(true);
 $('epAnswer').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();if(view.kind==='practice')$('epCheckAnswer')?.click();else capture(true);}};
 for(const b of host.querySelectorAll('[data-answer]'))b.onclick=()=>{$('epAnswer').value=b.dataset.answer;host.querySelectorAll('[data-answer]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));capture(true);};
 if($('epGuess'))$('epGuess').onchange=()=>capture(true);
 $('epKeyboard').onclick=()=>{pen=false;$('epInkArea').hidden=true;$('epKeyboard').setAttribute('aria-pressed','true');$('epStylus').setAttribute('aria-pressed','false');$('epWorking').focus();};
 $('epStylus').onclick=()=>{pen=true;$('epInkArea').hidden=false;$('epKeyboard').setAttribute('aria-pressed','false');$('epStylus').setAttribute('aria-pressed','true');drawInk();};
 const cv=$('epCanvas');cv.onpointerdown=e=>{if(pointer!==null||(e.pointerType==='touch'&&$('epPenOnly').checked)||e.button>0)return;e.preventDefault();pointer=e.pointerId;cv.setPointerCapture?.(e.pointerId);strokes.push([]);strokes=strokes.slice(-60);cv.onpointermove(e);};
 cv.onpointermove=e=>{if(e.pointerId!==pointer)return;e.preventDefault();const r=cv.getBoundingClientRect(),s=strokes.at(-1);if(!r.width||!r.height||s.length>=300)return;s.push([Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))]);drawInk();};
 cv.onpointerup=cv.onpointercancel=e=>{if(e.pointerId!==pointer)return;pointer=null;capture(true);};
 $('epUndoInk').onclick=()=>{strokes.pop();drawInk();capture(true);};$('epClearInk').onclick=()=>{if(strokes.length&&!confirm('Clear this drawing? Typed working stays.'))return;strokes=[];drawInk();capture(true);};
}
function drawInk(){const cv=$('epCanvas');if(!cv||!pen)return;const ctx=cv.getContext('2d');if(!ctx)return;const r=cv.getBoundingClientRect();if(!r.width)return;const dpr=Math.min(root.devicePixelRatio||1,2);cv.width=Math.round(r.width*dpr);cv.height=Math.round(r.height*dpr);ctx.clearRect(0,0,cv.width,cv.height);ctx.strokeStyle='#29232f';ctx.lineWidth=2.2*dpr;ctx.lineCap='round';ctx.lineJoin='round';for(const s of strokes){ctx.beginPath();s.forEach(([x,y],i)=>i?ctx.lineTo(x*cv.width,y*cv.height):ctx.moveTo(x*cv.width,y*cv.height));ctx.stroke();}}
function tickPaper(){
 if(paused||!data().papers)return;const active=Object.values(data().papers).filter(p=>!p.submittedAt&&p.deadline);
 for(const p of active){const remaining=p.deadline-Date.now();if(remaining<=0){E.submitPaper(data(),p.id,Math.max(p.deadline,Date.now()));save(S);if(visible()&&view.kind==='paper'&&view.paper===p.id)open('results',p.id);continue;}if(visible()&&view.kind==='paper'&&view.paper===p.id&&$('epPaperClock')){$('epPaperClock').textContent=`${Math.floor(remaining/60000)}:${String(Math.floor(remaining/1000)%60).padStart(2,'0')} remaining`;$('epPaperClock').dataset.warning=String(remaining<300000);}}
}
function printPractice(){
 capture();const seed=Math.floor(Math.random()*4294967296),qs=E.D.units.filter((_,i)=>i%2===0).map((u,i)=>E.B.make(u.id,1,(seed+i*7919)>>>0));qs.forEach(q=>data().seen[q.fingerprint]=data().seen[q.fingerprint]||Date.now());save(S);
 let print=$('epPrint');if(!print){print=document.createElement('section');print.id='epPrint';document.body.append(print);}print.innerHTML='<h1>Mochi · Mixed reasoning practice</h1><p>Original learning questions. Not an official NUS High paper. This practice set is separate from the reserved in-app forms.</p>'+qs.map((q,i)=>`<article><h2>Question ${i+1}</h2><p>${esc(q.text)}</p>${F.diagram(q.figure,q.id+'-print')}<div class="ep-print-working"></div><p>Answer: _______________________</p></article>`).join('');root.print();
}
function paintParent(){
 if(!$('entranceParent')?.open)return;const d=data(),report=E.report(d),recent=d.attempts.slice(-60).reverse(),sig=JSON.stringify([report, d.reviews, d.external]);if(sig===lastParent)return;lastParent=sig;
 $('entranceParentBody').innerHTML=`<p><strong>June 2027 mathematics preparation.</strong> ${report.qualifyingPapers}/3 internal paper targets; ${report.reviewedStrands}/4 strands with an independently correct explanation marked valid by an adult; ${report.externalChecks} qualifying parent-reported external checks.</p><p>${report.internalTarget?'Internal training target evidence is recorded. Confirm it against external unseen material.':'Readiness is not yet established by the recorded evidence.'} No admission probability or percentile is calculated.</p><div class="ep-table-wrap"><table><thead><tr><th>Method</th><th>Next stage</th><th>Independent application / transfer / delayed</th></tr></thead><tbody>${report.units.map(u=>`<tr><td>${esc(u.title)}</td><td>${esc(u.stage)}</td><td>${u.apply} / ${u.transfer} / ${u.delayed}</td></tr>`).join('')}</tbody></table></div><label for="epReviewPick">Review a recorded response</label><select id="epReviewPick"><option value="">Choose a response</option>${recent.map(a=>`<option value="${esc(a.id)}">${esc(E.unit(a.unit).title)} · ${a.correct?'correct answer':'revisit'} · ${new Date(a.answeredAt).toLocaleDateString()}</option>`).join('')}</select><div id="epReviewDetail"></div><details><summary>Record an external unseen paper</summary><p>Parent-entered evidence is kept separate from app marking. Use previously unseen material and record the actual conditions.</p><label>Paper name <input id="epExternalName" maxlength="150"></label><label>Marks earned <input id="epExternalScore" type="number" min="0" step="any"></label><label>Total marks <input id="epExternalTotal" type="number" min="1" step="any"></label><label><input type="checkbox" id="epExternalUnseen"> Previously unseen</label><label><input type="checkbox" id="epExternalIndependent"> No help</label><label><input type="checkbox" id="epExternalTimed"> Completed within its time limit</label><button id="epSaveExternal">Save external result</button><p id="epExternalStatus" role="status"></p>${d.external.map(x=>`<p>${esc(x.name)}: ${x.score}/${x.total}, ${x.unseen?'unseen':'familiar'}, ${x.independent?'independent':'supported'}, ${x.timed?'timed':'untimed'}.</p>`).join('')}</details><p class="ep-note">${report.limits.map(esc).join(' ')}</p>`;
 $('epReviewPick').onchange=()=>{const a=d.attempts.find(a=>a.id===$('epReviewPick').value);if(!a){$('epReviewDetail').innerHTML='';return;}const v=a.responses.at(-1),review=d.reviews[a.id];$('epReviewDetail').innerHTML=`<p><strong>${esc(a.question)}</strong></p><p>Submitted answer: ${esc(v.answer)}. ${a.independent?'No recorded answer help.':'Support, a revision or a conflict is recorded.'}</p><p>${esc(v.working||'No typed explanation recorded.')}</p>${drawing(v.strokes)}${a.reflection?'<p>Later notes: '+esc(a.reflection)+'</p>':''}<label for="epReviewVerdict">Adult review of the explanation</label><select id="epReviewVerdict">${[['unreviewed','Not reviewed'],['valid','Reasoning is valid'],['needs-discussion','Needs discussion']].map(([id,label])=>`<option value="${id}" ${review?.verdict===id?'selected':''}>${label}</option>`).join('')}</select><textarea id="epReviewNote" rows="2" maxlength="1500" aria-label="Adult review note">${esc(review?.note||'')}</textarea><button id="epSaveReview">Save review</button><p id="epReviewStatus" role="status"></p>`;$('epSaveReview').onclick=()=>{E.review(d,a.id,$('epReviewVerdict').value,$('epReviewNote').value);save(S);$('epReviewStatus').textContent='Review saved separately from numerical marking.';lastParent='';};};
 $('epSaveExternal').onclick=()=>{try{E.addExternal(d,{name:$('epExternalName').value,score:Number($('epExternalScore').value),total:Number($('epExternalTotal').value),unseen:$('epExternalUnseen').checked,independent:$('epExternalIndependent').checked,timed:$('epExternalTimed').checked});save(S);lastParent='';paintParent();}catch(e){$('epExternalStatus').textContent=e.message;}};
}
function init(){
 E.init(S);host=document.createElement('main');host.id='viewEntrance';host.className='entrance-view';host.hidden=true;$('viewMaths').before(host);
 const details=document.createElement('details');details.id='entranceParent';details.className='study-details';details.innerHTML='<summary>Entrance pathway · evidence and external benchmarks</summary><div id="entranceParentBody"></div>';$('parentEvidence').before(details);details.ontoggle=paintParent;
 const entry=document.createElement('button');entry.id='entranceReturn';entry.className='course-secondary entrance-return';entry.textContent='Entrance pathway · June 2027';entry.onclick=()=>open('home');$('courseReturn').before(entry);
 const bind=()=>{$('subjectMaths').onclick=()=>open('home');};bind();
 document.addEventListener('mochi:cloud-merged',()=>{bind();lastParent='';if(visible())render();paintParent();});
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')capture(true);else tickPaper();});root.addEventListener('pagehide',()=>capture(true));root.addEventListener('resize',drawInk);
 $('adultBtn').addEventListener('click',()=>{if(visible()&&view.kind==='paper'){capture();E.interruptPaper(data(),view.paper);save(S);}});
 root.MochiEntranceUI={open,leave,visible,capture,view:()=>({...view}),next:nextRecommended,practice:beginPractice,pause:()=>{capture();paused=true;},refresh:()=>{paused=false;bind();lastParent='';open('home');paintParent();},currentUnit:()=>view.unit};
 const reset=$('resetBtn').onclick;$('resetBtn').onclick=()=>{const before=S.learning;reset();if(before!==S.learning){S.entrance=E.fresh();paused=false;save(S);open('home');}};
 setInterval(tickPaper,500);open('home');
}
if(root.MochiReady)init();else document.addEventListener('mochi:ready',init,{once:true});
})(window);
