/* Seeded original questions. Forms 0/1/2 are guided/application/transfer.
   Form 3 is reserved for independent papers and never selected by practice. */
(function(root){
'use strict';
const D=root.MochiEntranceData||(typeof require==='function'?require('./entrance-data.js'):null);
const F=root.MochiEntranceFigures||(typeof require==='function'?require('./entrance-figures.js'):null);
const gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a),lcm=(a,b)=>a/gcd(a,b)*b,round=x=>Math.round(x*1e8)/1e8;
const fraction=(a,b)=>{const g=gcd(a,b);return b/g===1?String(a/g):`${a/g}/${b/g}`;};
function random(seed){let n=seed>>>0;return (a,b)=>{n=(Math.imul(1664525,n)+1013904223)>>>0;return a+Math.floor(n/4294967296*(b-a+1));};}
function hash(s){let h=2166136261;for(const c of s){h=Math.imul(h^c.charCodeAt(0),16777619);}return (h>>>0).toString(36);}
function modPow(b,n,m){let v=1;while(n-- >0)v=v*b%m;return v;}
function exposed(edge,hole=0){const c=new Set();for(let x=0;x<edge;x++)for(let y=0;y<edge;y++)for(let z=0;z<edge;z++)if(!(hole&&x>=1&&x<=hole&&y>=1&&y<=hole))c.add([x,y,z].join(','));let faces=0;for(const key of c){const p=key.split(',').map(Number);for(const [d,k]of [[0,-1],[0,1],[1,-1],[1,1],[2,-1],[2,1]]){const q=p.slice();q[d]+=k;if(!c.has(q.join(',')))faces++;}}return faces;}
function bestPacks(budget,costs,counts){let best=0,winner=[];function visit(i,remaining,total,chosen){if(i===costs.length){if(total>best){best=total;winner=chosen;}return;}for(let n=0;n<=Math.floor(remaining/costs[i]);n++)visit(i+1,remaining-n*costs[i],total+n*counts[i],[...chosen,n]);}visit(0,budget,0,[]);return {best,winner};}
function make(unit,form,seed){
 const u=D.units.find(x=>x.id===unit);if(!u||!Number.isInteger(form)||form<0||form>3||!Number.isSafeInteger(seed)||seed<0||seed>4294967295)throw Error('Invalid question identity');
 const r=random((seed^parseInt(hash(unit),36)^Math.imul(form+1,2654435761))>>>0),pick=a=>a[r(0,a.length-1)];let q;
 const out=(text,answer,steps,params={},extra={})=>q={unit,strand:u.strand,form,seed,id:`ep1:${unit}:${form}:${seed}`,text,answer,steps,params,level:form===0?1:form===1?2:3,...extra};
 if(unit==='relationships'){
  if(form===0){const x=r(3,14),a=r(3,8),b=r(4,20);out(`A number is multiplied by ${a}, then ${b} is added. The result is ${a*x+b}. What is the number?`,x,[`Let the number be x: ${a}x + ${b} = ${a*x+b}.`,`Subtract ${b}, then divide by ${a}: x = ${x}.`,`Check: ${a} × ${x} + ${b} = ${a*x+b}.`],{x,a,b});}
  if(form===1){const small=r(13,45),difference=r(7,21),total=2*small+difference;out(`Two trays contain ${total} counters altogether. The first tray contains ${difference} more than the second. How many counters are in the second tray?`,small,[`Remove the difference: ${total} − ${difference} = ${2*small}.`,`This is twice the smaller amount: ${2*small} ÷ 2 = ${small}.`,`The other tray has ${small+difference}; together they have ${total}.`],{total,difference});}
  if(form===2){const excess=2*r(2,9),short=2*r(2,7),depth=(excess+3*short)/2;out(`A cord is ${excess} cm longer than the depth of a container. Folded into three equal lengths, it is ${short} cm shorter than that depth. What is the depth of the container?`,depth,[`Let the depth be d. The cord is d + ${excess} cm.`,`Three folded lengths give 3(d − ${short}) = d + ${excess}.`,`Thus 2d = ${excess+3*short}, so d = ${depth} cm.`,`Check: cord ${depth+excess} cm; one third is ${depth-short} cm.`],{excess,short},{suffix:'cm'});}
  if(form===3){const shelf=r(60,110),diff=r(8,25),a=shelf+diff,b=shelf-diff;out(`A tall vase is placed on a shelf and a short vase stands on the floor. Their tops differ in height by ${a} cm. When the vases swap places, their tops differ by ${b} cm, with the vase on the shelf still higher. How high is the shelf?`,shelf,[`Let h be the shelf height and d the difference between vase heights.`,`h + d = ${a}; h − d = ${b}.`,`Add the equations: 2h = ${a+b}. So h = ${shelf} cm.`,`The vase difference is ${diff} cm; both conditions check.`],{a,b},{suffix:'cm'});}
 }else if(unit==='percent'){
  if(form===0){const price=100*r(2,12),rate=pick([9,10,15,20]),tax=price*rate/100;out(`A device costs $${price} before a ${rate}% charge. What is its price including that charge?`,price+tax,[`The charge is added, so the answer must be greater than $${price}.`,`${rate}% of ${price} = ${tax}.`,`Total = ${price} + ${tax} = $${price+tax}.`],{price,rate},{prefix:'$'});}
  if(form===1){const original=100*r(2,10),rate=pick([15,20,25,30]),paid=original*(100-rate)/100;out(`After a ${rate}% discount, a desk costs $${paid}. What was its price before the discount?`,original,[`${100-rate}% of the original is $${paid}.`,`Original = ${paid} ÷ ${(100-rate)/100} = $${original}.`,`Check by taking ${rate}% off the original.`],{rate,paid},{prefix:'$'});}
  if(form===2){const original=100*r(3,16),p=pick([10,20,30]),s=pick([10,20,25]),paid=round(original*(100-p)*(100-s)/10000);out(`A coat is reduced by ${p}%. A further ${s}% discount is applied to the reduced price. The final price is $${paid}. What was the original price?`,original,[`The two discounts act on different wholes.`,`The fraction left is ${(100-p)/100} × ${(100-s)/100} = ${round((100-p)*(100-s)/10000)}.`,`Original = ${paid} ÷ ${round((100-p)*(100-s)/10000)} = $${original}.`,`Do not add the discounts as if both acted on the original price.`],{p,s,paid},{prefix:'$'});}
  if(form===3){const a=10*r(4,16),difference=10*r(2,8),total=round(.9*a+1.2*(a+difference));out(`A centre originally has ${difference} more junior members than senior members. The senior membership then decreases by 10%, while the junior membership increases by 20%. There are now ${total} members altogether. How many senior members were there originally?`,a,[`Let the original senior count be x; juniors = x + ${difference}.`,`0.9x + 1.2(x + ${difference}) = ${total}.`,`2.1x = ${round(total-1.2*difference)}, so x = ${a}.`,`Check both changed groups separately before adding them.`],{difference,total});}
 }else if(unit==='remainders'){
  if(form===0){const whole=12*r(3,12);out(`A roll contains ${whole} m of ribbon. First 1/3 of it is used, then 1/4 of the remaining ribbon is used. How many metres remain?`,whole/2,[`After the first use, 2/3 remains: ${whole*2/3} m.`,`After the second use, 3/4 of that remains: ${whole/2} m.`,`The retained fraction is 2/3 × 3/4 = 1/2.`],{whole},{suffix:'m'});}
  if(form===1){const whole=4*r(10,35),fixed=r(5,15),left=whole*3/4-fixed;out(`A child spends 1/4 of some money and then another $${fixed}. There is $${left} left. How much money was there at first?`,whole,[`Undo the last purchase: ${left} + ${fixed} = ${whole*3/4}.`,`This is 3/4 of the original.`,`Original = ${whole*3/4} ÷ 3 × 4 = $${whole}.`],{fixed,left},{prefix:'$'});}
  if(form===2){const whole=24*r(3,11),fixed=r(5,18),left=whole/4-fixed;out(`A store sells 1/3 of its pencils in the morning, then 5/8 of those remaining in the afternoon. It gives away ${fixed} more pencils and has ${left} left. How many pencils did it have at first?`,whole,[`Before the giveaway there were ${left+fixed} pencils.`,`The fraction after both sales was 2/3 × 3/8 = 1/4.`,`Original = (${left} + ${fixed}) × 4 = ${whole}.`,`Check each sale using the current remainder, not the original count.`],{fixed,left});}
  if(form===3){const a=12*r(3,12),b=12*r(3,12),total=a+b,finalB=(b+a/3)*3/4;out(`Two boxes hold ${total} beads altogether. First 1/3 of the beads in A are moved to B. Then 1/4 of the beads now in B are moved to A. B finishes with ${finalB} beads. How many beads were in A initially?`,a,[`Undo the second move: B previously held ${finalB} ÷ 3 × 4 = ${finalB*4/3}.`,`At that moment A held ${total} − ${finalB*4/3} = ${a*2/3}.`,`That is 2/3 of A’s original amount.`,`Initially A held ${a*2/3} ÷ 2 × 3 = ${a}.`],{total,finalB});}
 }else if(unit==='simultaneous'){
  if(form===0){const bikes=r(6,16),carts=r(4,14),total=bikes+carts,wheels=2*bikes+4*carts;out(`A shed contains ${total} vehicles: bicycles with 2 wheels and carts with 4 wheels. There are ${wheels} wheels altogether. How many carts are there?`,carts,[`An all-bicycle baseline gives ${total} × 2 = ${total*2} wheels.`,`Extra wheels = ${wheels} − ${total*2} = ${2*carts}.`,`Each cart adds 2 beyond the baseline, giving ${carts} carts.`],{total,wheels});}
  if(form===1){const a=r(4,12),b=r(2,8),one=2*a+3*b,two=4*a+b;out(`Two notebooks and three pens cost $${one}. Four notebooks and one pen cost $${two}. What is the price of one notebook?`,a,[`Let notebook and pen prices be n and p.`,`2n + 3p = ${one}; 4n + p = ${two}.`,`Multiply the second equation by 3 and subtract the first: 10n = ${3*two-one}.`,`n = $${a}; the pen price is $${b}.`],{one,two},{prefix:'$'});}
  if(form===2){const years=r(2,5),young=3*years;out(`${years} years ago, an adult was 5 times a child’s age. In ${years} years, the adult will be 3 times the child’s age. How old is the child now?`,young,[`Let the child’s present age be c and the adult’s be a.`,`a − ${years} = 5(c − ${years}), so a = 5c − ${4*years}.`,`a + ${years} = 3(c + ${years}), so a = 3c + ${2*years}.`,`2c = ${6*years}; c = ${young} years.`],{years},{suffix:'years'});}
  if(form===3){const a=r(5,14),b=r(2,7),one=3*a+2*b,two=2*a+5*b;out(`Three panels and two brackets cost $${one}. Two panels and five brackets cost $${two}. What is the cost of four panels and three brackets?`,4*a+3*b,[`Let prices be p and b: 3p + 2b = ${one}; 2p + 5b = ${two}.`,`Multiply the first by 5 and the second by 2, then subtract: 11p = ${5*one-2*two}.`,`One panel costs $${a} and one bracket costs $${b}.`,`Required cost = 4 × ${a} + 3 × ${b} = $${4*a+3*b}.`],{one,two},{prefix:'$'});}
 }else if(unit==='ratios'){
  if(form===0){const a=r(2,5),b=a+r(1,4),k=r(3,9);out(`The ratio of blue beads to white beads is ${a}:${b}. There are ${b*k} white beads. How many beads are there altogether?`,(a+b)*k,[`${b} units = ${b*k}, so 1 unit = ${k}.`,`The total has ${a+b} units.`,`Total = ${a+b} × ${k} = ${(a+b)*k}.`],{a,b,white:b*k});}
  if(form===1){const k=r(4,18);out(`The ratio of red to blue tiles is 2:3. After ${7*k} blue tiles are added, it is 3:8. No red tiles are changed. How many tiles were there at first?`,15*k,[`Match the unchanged red amount: 2:3 becomes 6:9; 3:8 becomes 6:16.`,`The extra ${7*k} blue tiles represent 7 units.`,`One unit = ${k}; original total = 15 × ${k} = ${15*k}.`],{added:7*k});}
  if(form===2){const k=r(5,21);out(`Counters in boxes A and B are in the ratio 5:3. Moving ${k} counters from A to B makes the two amounts equal. How many counters are there altogether?`,8*k,[`The original difference is 2 ratio units.`,`Moving counters changes the difference by twice the number moved: one leaves A and joins B.`,`So 1 unit = ${k}; total = 8 × ${k} = ${8*k}.`],{moved:k});}
  if(form===3){const k=r(2,8),a=10*k,b=15*k;out(`A supply of water can give ${a} litres to each can in group A, or ${b} litres to each can in group B. The groups have no cans in common. If the same water is shared equally among all cans in both groups, how many litres does each can receive?`,6*k,[`Choose a convenient supply of ${a*b} litres.`,`It serves ${b} cans in A or ${a} cans in B.`,`Together there are ${a+b} cans.`,`Equal share = ${a*b} ÷ ${a+b} = ${6*k} litres. The chosen supply cancels out.`],{a,b},{suffix:'litres'});}
 }else if(unit==='rates'){
  if(form===0){const rate=r(6,18),time=r(4,10),target=rate*r(12,25);out(`A machine produces ${rate*time} identical parts in ${time} minutes at a constant rate. How many minutes does it need for ${target} parts?`,target/rate,[`Rate = ${rate*time} ÷ ${time} = ${rate} parts per minute.`,`Time = ${target} ÷ ${rate} = ${target/rate} minutes.`],{count:rate*time,time,target},{suffix:'minutes'});}
  if(form===1){const k=r(2,7),a=3*k,b=6*k;out(`Pump A fills a tank in ${a} hours; pump B fills it in ${b} hours. Both have constant rates and can operate independently. Starting together with an empty tank, how many hours do they take to fill it?`,2*k,[`A fills 1/${a} tank per hour; B fills 1/${b}.`,`Combined rate = ${fraction(a+b,a*b)} tank per hour.`,`Time for one tank = ${2*k} hours.`],{a,b},{suffix:'hours'});}
  if(form===2){const combined=r(15,30),a=r(5,12),time=r(3,8),b=combined-a,target=b*r(10,20);out(`Two workers together pack ${combined*time} parcels in ${time} hours. The first alone packs ${a*4} parcels in 4 hours. At these constant rates, how many hours would the second alone need to pack ${target} parcels?`,target/b,[`Combined rate = ${combined*time} ÷ ${time} = ${combined} parcels/hour.`,`First worker’s rate = ${a*4} ÷ 4 = ${a}.`,`Second worker’s rate = ${combined} − ${a} = ${b}.`,`Required time = ${target} ÷ ${b} = ${target/b} hours.`],{count:combined*time,time,first:a*4,target},{suffix:'hours'});}
  if(form===3){const inflow=r(2,5),rate=r(8,15),stock=(rate-inflow)*r(10,20),outflow=2*rate,first=stock/(rate-inflow);out(`Water flows into a tank at a constant rate of ${inflow} litres per minute. One pump removes ${rate} litres per minute and empties the initially partly filled tank in ${first} minutes while the inflow continues. How many minutes would two identical pumps take from the same starting amount, with the inflow still continuing?`,stock/(outflow-inflow),[`With one pump, net removal = ${rate} − ${inflow} = ${rate-inflow} litres/minute.`,`Starting amount = ${first} × ${rate-inflow} = ${stock} litres.`,`With two pumps, net removal = ${outflow} − ${inflow} = ${outflow-inflow}.`,`Time = ${stock}/${outflow-inflow} minutes. Leave as an exact fraction if needed.`],{inflow,rate,first},{suffix:'minutes',answerLabel:fraction(stock,outflow-inflow)});}
 }else if(unit==='motion'){
  if(form===0){const a=r(40,70),b=r(30,50),t=r(4,9),distance=(a+b)*t;out(`Two walkers start ${distance} m apart and walk towards each other along a straight path at ${a} m/min and ${b} m/min. After how many minutes do they meet?`,t,[`The gap closes at ${a} + ${b} = ${a+b} m/min.`,`Time = ${distance} ÷ ${a+b} = ${t} minutes.`],{a,b,distance},{suffix:'minutes',figure:{kind:'motion',a,b,distance,alt:`Two walkers ${distance} m apart, moving towards each other at ${a} and ${b} metres per minute.`}});}
  if(form===1){const a=r(6,10)*10,b=a-r(2,4)*10,leg=lcm(a,b);out(`A rider travels ${leg} km at ${a} km/h, then returns along the same route at ${b} km/h without stopping. What is the average speed for the whole journey? Give an exact fraction if needed.`,2*a*b/(a+b),[`Outward time = ${leg}/${a} = ${leg/a} hours.`,`Return time = ${leg}/${b} = ${leg/b} hours.`,`Average speed = total distance / total time = ${2*leg}/${leg/a+leg/b} = ${fraction(2*a*b,a+b)} km/h.`,`The two times differ, so do not average the speeds directly.`],{a,b,leg},{suffix:'km/h',answerLabel:fraction(2*a*b,a+b)});}
  if(form===2){const a=r(4,8),b=r(3,7),distance=(a+b)*r(2,5),messenger=r(15,25);out(`Two walkers approach each other along a straight road at ${a} km/h and ${b} km/h from points ${distance} km apart. A drone flies back and forth between them at a constant ${messenger} km/h until they meet, turning without delay. How far does the drone travel?`,distance/(a+b)*messenger,[`Meeting time = ${distance} ÷ (${a} + ${b}) = ${distance/(a+b)} hours.`,`The drone flies for that entire time.`,`Distance = ${messenger} × ${distance/(a+b)} = ${distance/(a+b)*messenger} km.`],{a,b,distance,messenger},{suffix:'km'});}
  if(form===3){const walk=r(2,5),belt=r(1,walk-1),length=lcm(walk+belt,walk-belt)*r(3,7),withTime=length/(walk+belt),againstTime=length/(walk-belt);out(`A moving walkway has a constant speed. A child walks at the same speed relative to it in either direction. Crossing with the walkway takes ${withTime} seconds; crossing against it takes ${againstTime} seconds. The child’s walking speed relative to the walkway is ${walk} m/s. How long is the walkway?`,length,[`Let its length be L and its speed be v.`,`L/${withTime} = ${walk} + v; L/${againstTime} = ${walk} − v.`,`Add to eliminate v: L(1/${withTime} + 1/${againstTime}) = ${2*walk}.`,`L = ${length} metres.`],{walk,withTime,againstTime},{suffix:'m'});}
 }else if(unit==='capacity'){
  const large=3*r(4,9),small=large*2,usedLarge=r(2,5),usedSmall=r(5,12),capacity=lcm(large,small);
  if(form===0)out(`A rack holds ${large} large trays or ${small} small trays. How many small trays occupy the same space as ${usedLarge} large trays?`,2*usedLarge,[`One large tray occupies the same space as ${small}/${large} = 2 small trays.`,`${usedLarge} large trays correspond to ${2*usedLarge} small trays.`],{large,small,usedLarge});
  if(form===1)out(`A rack holds ${large} large trays or ${small} small trays. It currently contains ${usedLarge} large trays and ${usedSmall} small trays. What is the greatest number of additional large trays that will fit?`,Math.floor((small-2*usedLarge-usedSmall)/2),[`Use small-tray units: capacity ${small}; each large tray uses 2.`,`Unused capacity = ${small} − ${usedLarge} × 2 − ${usedSmall} = ${small-2*usedLarge-usedSmall}.`,`Divide by 2 and take complete trays only: ${Math.floor((small-2*usedLarge-usedSmall)/2)}.`],{large,small,usedLarge,usedSmall});
  if(form===2){const a=5*r(3,7),b=3*a/5,taken=r(2,5),fill=a-taken;out(`A container holds ${a} small boxes or ${b} large boxes. It is full of small boxes. What is the minimum number of small boxes that must be removed to make room for ${taken} large boxes?`,Math.ceil(taken*a/b),[`One large box uses ${a}/${b} small-box spaces.`,`${taken} large boxes need ${fraction(taken*a,b)} small-box spaces.`,`Remove at least that many complete small boxes: ${Math.ceil(taken*a/b)}.`],{a,b,taken});}
  if(form===3){const capacity=60*r(2,5),wide=5,narrow=3,count=r(4,9),remain=capacity-wide*count;out(`A shelf is ${capacity} cm long. Wide books are 5 cm thick and narrow books are 3 cm thick. There must be ${count} wide books and at least one narrow book. What is the greatest total number of books that can fit in one row?`,count+Math.floor(remain/narrow),[`The required wide books use ${count} × 5 = ${5*count} cm.`,`The remaining ${remain} cm fit ${Math.floor(remain/3)} complete narrow books.`,`Total = ${count} + ${Math.floor(remain/3)} = ${count+Math.floor(remain/3)}.`],{capacity,count});}
 }else if(unit==='area'){
  if(form===0){const b=2*r(5,13),h=r(6,15);out(`Triangle ABC has base BC = ${b} cm and perpendicular height ${h} cm. Find its area.`,b*h/2,[`Area = base × perpendicular height ÷ 2.`,`${b} × ${h} ÷ 2 = ${b*h/2} cm².`],{b,h},{suffix:'cm²',figure:{kind:'triangle',b,h,alt:`Triangle ABC with base ${b} cm and marked perpendicular height ${h} cm.`}});}
  if(form===1){const a=r(2,6),b=r(7,12),unitArea=r(6,18);out(`B, D and C lie in that order on a straight line, with BD = ${a} cm and DC = ${b} cm. Triangle ABD has area ${a*unitArea} cm². What is the area of triangle ADC?`,b*unitArea,[`Triangles ABD and ADC have a common vertex and collinear bases, so their heights are equal.`,`Area per centimetre of base = ${a*unitArea} ÷ ${a} = ${unitArea}.`,`Area ADC = ${b} × ${unitArea} = ${b*unitArea} cm².`],{a,b,area:a*unitArea},{suffix:'cm²',figure:{kind:'split',parts:[a,b],alt:`Triangle ABC divided by AD, with BD ${a} cm and DC ${b} cm.`}});}
  if(form===2){const a=r(2,6),b=r(3,7),c=r(2,8),k=r(4,12),total=(a+b+c)*k;out(`The base BC of triangle ABC is divided at D and E, in the order B, D, E, C. BD = ${a} cm, DE = ${b} cm and EC = ${c} cm. The whole triangle has area ${total} cm². Find the shaded area ADE.`,b*k,[`All three small triangles have the same perpendicular height.`,`The total base is ${a+b+c} cm.`,`ADE occupies ${b}/${a+b+c} of the total: ${total} × ${b}/${a+b+c} = ${b*k} cm².`],{a,b,c,total},{suffix:'cm²',figure:{kind:'split',parts:[a,b,c],shade:1,alt:`Triangle ABC split into bases ${a}, ${b} and ${c} cm. Only middle triangle ADE is shaded.`}});}
  if(form===3){const a=r(3,7),b=r(4,9),s=r(4,10),areaA=a*s,whole=(a+b)*s;out(`D lies on BC of triangle ABC. The areas of triangles ABD and ADC are ${areaA} cm² and ${b*s} cm². If BC = ${2*(a+b)} cm, find DC.`,2*b,[`With equal heights, BD:DC = ${areaA}:${b*s} = ${a}:${b}.`,`The whole base represents ${a+b} parts.`,`DC = ${2*(a+b)} × ${b}/${a+b} = ${2*b} cm.`],{areaA,areaB:b*s,base:2*(a+b)},{suffix:'cm',figure:{kind:'triangle',b:2*(a+b),alt:`Triangle ABC with D on base BC and segment AD drawn. Areas are given in the question.`}});q.figure={kind:'split',parts:[a,b],alt:`Triangle ABC divided by AD. Use the areas and total BC stated in the question.`};q.figure.hideMeasures=true;}
 }else if(unit==='decomposition'){
  if(form===0){const w=r(14,24),h=r(10,13),b=r(1,3),answer=w*h-(w-2*b)*(h-2*b);out(`A rectangular plot is ${w} m by ${h} m. A path ${b} m wide runs just inside all four edges. Find the area of the path.`,answer,[`Inner dimensions are ${w-2*b} m and ${h-2*b} m: subtract the border at both ends.`,`Path = whole − inner rectangle.`,`${w*h} − ${(w-2*b)*(h-2*b)} = ${answer} m².`],{w,h,b},{suffix:'m²',figure:{kind:'border',w,h,b}});}
  if(form===1){const w=2*r(6,13),h=2*r(4,8),position=pick([.25,.4,.65]);out(`ABCD is a rectangle of length ${w} cm and breadth ${h} cm. E and G lie on AB and DC respectively, with EG perpendicular to AB. F and H lie on BC and AD. Find the shaded area EFGH.`,w*h/2,[`Draw EG. It is a vertical base of length ${h} cm.`,`Triangles EFG and EHG have horizontal heights that add to ${w} cm.`,`Their combined area is 1/2 × ${h} × ${w} = ${w*h/2} cm².`],{w,h,position},{suffix:'cm²',figure:{kind:'inscribed',w,h,position,alt:`Rectangle ABCD. E on top and G on bottom are directly aligned. F is on the right, H on the left; EFGH is shaded.`}});}
  if(form===2){const k=pick([2,3]),side=(k*k+1)*r(2,5),answer=side*side*(k-1)**2/(k*k+1);out(`ABCD is a square of side ${side} cm. Points E, F, G and H lie on BC, CD, DA and AB respectively, with BE/BC = CF/CD = DG/DA = AH/AB = 1/${k}. Segments AE, BF, CG and DH enclose a small central square. Find its area.`,answer,[`Let P be the intersection of AE and BF. A quarter-turn carries AE to BF, so these lines are perpendicular.`,`Triangles ABP and BEP are similar right triangles: corresponding angles match. Their hypotenuses AB and BE have ratio ${k}:1, so their areas have ratio ${k*k}:1.`,`Together those two triangles form ABE. Area ABE = ${side} × ${side/k} ÷ 2 = ${side*side/(2*k)} cm².`,`The small overlap triangle BEP is 1/${k*k+1} of ABE: ${side*side/(2*k)}/${k*k+1} cm².`,`The four congruent corner triangles ABE, BCF, CDG and DAH cover everything outside the centre. Neighbouring corner triangles overlap in four copies of BEP.`,`Centre = whole square − four corner triangles + four overlaps.`,`Area = ${side*side} − 4 × ${side*side/(2*k)} + 4 × (${side*side/(2*k)}/${k*k+1}) = ${answer} cm². The overlaps are added back because subtracting both corner triangles removed them twice.`],{k,side},{suffix:'cm²',figure:{kind:'central',k,side,alt:`Square ABCD with E,F,G,H dividing successive sides at fraction 1/${k}; AE,BF,CG,DH enclose the shaded central square.`}});}
  if(form===3){const a=r(8,13),b=r(6,10),ox=r(2,4),oy=r(2,4);out(`Two squares have sides ${a} cm and ${b} cm. Their overlapping region is a rectangle ${ox} cm by ${oy} cm, as shown. What is the total area covered by the two squares?`,a*a+b*b-ox*oy,[`Sum of square areas = ${a*a} + ${b*b} = ${a*a+b*b}.`,`The overlap, ${ox*oy} cm², has been counted twice.`,`Covered area = ${a*a+b*b} − ${ox*oy} = ${a*a+b*b-ox*oy} cm².`],{a,b,ox,oy},{suffix:'cm²',figure:{kind:'overlap',a,b,ox,oy}});}
 }else if(unit==='circles'){
  if(form===0){const radius=r(3,12);out(`A semicircle has radius ${radius} cm. Find its full perimeter, including the straight edge. Give your answer in terms of π.`,{a:2*radius,b:radius},[`The curved part is half of 2πr, or ${radius}π cm.`,`The straight diameter is ${2*radius} cm.`,`Perimeter = ${2*radius} + ${radius}π cm.`],{radius},{suffix:'cm',answerLabel:`${2*radius} + ${radius}π`});}
  if(form===1){const ds=[2*r(3,8),2*r(2,7),2*r(3,9)],b=ds.reduce((a,b)=>a+b,0)/2;out(`Three semicircular arcs have diameters ${ds.join(', ')} cm respectively. Find their total curved length, excluding the straight diameter segments. Give the answer in terms of π.`,{a:0,b},[`Each arc length is π × diameter ÷ 2.`,`Total = (${ds.join(' + ')})π ÷ 2 = ${b}π cm.`],{ds},{suffix:'cm',answerLabel:`${b}π`,figure:{kind:'semicircles',ds}});}
  if(form===2){const k=r(2,5),smallArea=r(5,20);out(`The radius of a large circle is ${k} times the radius of a small circle. The small circle has area ${smallArea}π cm². What is the area of the large circle in terms of π?`,{a:0,b:smallArea*k*k},[`Area scales as the square of radius.`,`Area multiplier = ${k} × ${k} = ${k*k}.`,`Large area = ${smallArea}π × ${k*k} = ${smallArea*k*k}π cm².`],{k,smallArea},{suffix:'cm²',answerLabel:`${smallArea*k*k}π`,figure:{kind:'circleRatio',k}});}
  if(form===3){const side=2*r(4,11);out(`A circle is inscribed in a square of side ${side} cm, touching all four sides. Find the shaded area inside the square but outside the circle. Give an exact answer in terms of π.`,{a:side*side,b:-side*side/4},[`The circle’s diameter is ${side} cm, so its radius is ${side/2} cm.`,`Square area = ${side*side}; circle area = ${side*side/4}π.`,`Shaded area = ${side*side} − ${side*side/4}π cm².`],{side},{suffix:'cm²',answerLabel:`${side*side} − ${side*side/4}π`,figure:{kind:'circleSquare',side}});}
 }else if(unit==='angles'){
  if(form===0||form===1){const apex=2*r(20,60),base=(180-apex)/2,answer=form===0?base:180-base;out(`Triangle ABC has AB = AC and angle BAC = ${apex}°. ${form===0?'Find angle ABC.':'BC is extended beyond C. Find the exterior angle between CA and the extension of BC at C.'}`,answer,[`The equal base angles share 180° − ${apex}° = ${180-apex}°.`,`Each base angle is ${base}°.` ,...(form===1?[`The exterior angle and interior base angle form 180°: ${180-base}°.`]:[])],{apex},{suffix:'°',figure:{kind:'isosceles',apex,exterior:form===1}});}
  if(form===2){const angleC=2*r(17,37),tip=(126-angleC)/2;out(`Five points on a circle are joined in order A–C–E–B–D–A to form a five-point star. The angle at tip A is ${tip}°. Find the sum of the other four tip angles.`,180-tip,['Trace the indicated star in one continuous route.','The total turning is 720°, or two complete turns.','The five tip angles therefore sum to 5 × 180° − 720° = 180°.',`Subtract the given tip: 180° − ${tip}° = ${180-tip}°.`],{tip}, {suffix:'°',figure:{kind:'star',angleC,alt:'Five points A,B,C,D,E around a circle, connected by skipping one point each time to form a five-point star.'}});}
  if(form===3){const theta=2*r(15,35);out(`ABCD is a square. Triangle BCE is constructed outside the square with BC = BE and angle CBE = ${theta}°. Segment AE is drawn. Find angle BAE.`,(90-theta)/2,['AB = BC = BE, so triangle ABE is isosceles.',`Angle ABE = 90° + ${theta}° = ${90+theta}° because E is outside the square.`,`The other two angles are equal: (180° − ${90+theta}°) ÷ 2 = ${(90-theta)/2}°.`],{theta}, {suffix:'°',figure:{kind:'squareTriangle',theta,alt:`Square ABCD with A lower left, B lower right, C upper right, D upper left. Triangle BCE is outside on the right with BC = BE and angle CBE ${theta} degrees. Segment AE is drawn.`}});}
 }else if(unit==='spatial'){
  const labels=[1,2,3,4,5,6];for(let i=5;i>0;i--){const j=r(0,i);[labels[i],labels[j]]=[labels[j],labels[i]];}
  if(form===0||form===1){const target=form===0?0:3,opposite={0:2,2:0,1:5,5:1,3:4,4:3};out(`The illustrated net folds into a cube. Which numbered face is opposite face ${labels[target]}?`,labels[opposite[target]],[`Fold the horizontal row around the centre face, then fold the vertical strip.`,`The opposite pairs are ${labels[0]}–${labels[2]}, ${labels[1]}–${labels[5]}, and ${labels[3]}–${labels[4]}.`,`Face ${labels[target]} is opposite ${labels[opposite[target]]}.`],{labels,target},{figure:{kind:'net',labels,alt:`Net with horizontal row ${labels[0]},${labels[1]},${labels[2]}; ${labels[3]} above the centre; ${labels[4]},${labels[5]} below it in that order.`}});}
  if(form===2||form===3){const views=[[labels[0],labels[2],labels[1]],[labels[3],labels[2],labels[4]]];out(`The pictures show two orientations of the same cube. Its faces are numbered 1 to 6, once each. Which number is opposite face ${labels[2]}?`,labels[5],[`Face ${labels[2]} touches ${labels[0]} and ${labels[1]} in one view, and ${labels[3]} and ${labels[4]} in the other.`,`These are its four different neighbours.`,`The remaining face, ${labels[5]}, must be opposite it.`],{labels,views},{figure:{kind:'views',views,alt:`View 1: top ${views[0][0]}, front ${views[0][1]}, right ${views[0][2]}. View 2: top ${views[1][0]}, front ${views[1][1]}, right ${views[1][2]}.`}});}
 }else if(unit==='volume'){
  if(form===0){const edge=r(2,9);out(`A solid cube has volume ${edge**3} cm³. Find its edge length.`,edge,[`Find a length e such that e × e × e = ${edge**3}.`,`${edge} × ${edge} × ${edge} = ${edge**3}, so the edge is ${edge} cm.`,`Dividing by 3 would not undo multiplication of three equal lengths.`],{volume:edge**3},{suffix:'cm',figure:{kind:'cubes',alt:'A cube with an unknown edge length. The volume is given in the question.'}});}
  if(form===1){const cubes=r(3,9),edge=r(2,5);out(`${cubes} identical cubes, each of edge ${edge} cm, are joined in a straight row with complete faces touching. Find the total exposed surface area of the resulting solid.`,(4*cubes+2)*edge*edge,[`Separate cubes have ${6*cubes} faces.`,`There are ${cubes-1} joins, each hiding two faces.`,`Exposed faces = ${6*cubes} − ${2*(cubes-1)} = ${4*cubes+2}.`,`Each face has area ${edge*edge}; total = ${(4*cubes+2)*edge*edge} cm².`],{cubes,edge},{suffix:'cm²'});}
  if(form===2){const edge=r(5,10),cut=r(1,edge-2);out(`A cube of edge ${edge} cm has a smaller cube of edge ${cut} cm removed from one corner. The removed cube shares that corner and its three edges follow the original edges. What is the total surface area of the remaining solid?`,6*edge*edge,[`The original surface area is 6 × ${edge}² = ${6*edge*edge} cm².`,`Three ${cut} × ${cut} outside squares are removed.`,`Three equal inside squares are exposed. These changes cancel.`,`Total surface area remains ${6*edge*edge} cm².`],{edge,cut},{suffix:'cm²'});}
  if(form===3){const edge=r(5,9),hole=r(1,edge-2);out(`A straight square tunnel of side ${hole} cm passes completely through a cube of edge ${edge} cm, perpendicular to its front and back faces. The opening lies strictly inside both faces. Find the remaining solid’s total surface area, including the tunnel walls.`,6*edge*edge-2*hole*hole+4*hole*edge,[`Original outside area = 6 × ${edge}² = ${6*edge*edge}.`,`Remove two openings: 2 × ${hole}² = ${2*hole*hole}.`,`Add four tunnel walls: 4 × ${hole} × ${edge} = ${4*hole*edge}.`,`Total = ${6*edge*edge-2*hole*hole+4*hole*edge} cm².`],{edge,hole},{suffix:'cm²',figure:{kind:'cubes',edge,hole,alt:`Cube of edge ${edge} cm; a shaded square of side ${hole} cm on the front indicates a straight tunnel to the back.`}});}
 }else if(unit==='factors'){
  const a=r(1,4),b=r(1,3),N=2**a*3**b;
  if(form===0)out(`Find the number of positive factors of ${N}.`,(a+1)*(b+1),[`${N} = 2^${a} × 3^${b}.`,`A factor chooses an exponent of 2 from 0 to ${a}, and an exponent of 3 from 0 to ${b}.`,`Number of choices = ${a+1} × ${b+1} = ${(a+1)*(b+1)}.`],{a,b,N});
  if(form===1){const x=2**a*3,y=2*3**b*5;out(`What is the least positive whole number divisible by both ${x} and ${y}?`,lcm(x,y),[`Prime factors: ${x} = 2^${a} × 3; ${y} = 2 × 3^${b} × 5.`,`Use the greatest exponent needed for every prime.`,`LCM = 2^${a} × 3^${b} × 5 = ${lcm(x,y)}.`],{x,y});}
  if(form===2){const p=pick([3,5,7]);out(`Find the smallest positive integer that is divisible by ${p} and has exactly 6 positive factors.`,Math.min(p**5,p*p*2,4*p),['Exactly six factors requires prime exponents 5, or 2 and 1. ',`Compare ${p}^5, ${p}² × 2, and 2² × ${p}.`,`The least is ${Math.min(p**5,p*p*2,4*p)}. Its factor count is 3 × 2 = 6.`],{p});}
  if(form===3){const c=r(1,2),value=N*5**c;out(`How many positive factors of ${value} are divisible by 6?`,a*b*(c+1),[`${value} = 2^${a} × 3^${b} × 5^${c}.`,`A factor divisible by 6 must use at least one 2 and at least one 3.`,`There are ${a} choices for the exponent of 2, ${b} for 3, and ${c+1} for 5.`,`Total = ${a*b*(c+1)}.`],{a,b,c,value});}
 }else if(unit==='cycles'){
  if(form===0){const divisor=r(3,12),N=r(15,40)*divisor+r(0,divisor-1);out(`What is the remainder when ${N} is divided by ${divisor}?`,N%divisor,[`${N} = ${divisor} × ${Math.floor(N/divisor)} + ${N%divisor}.`,`The remainder is ${N%divisor}, smaller than the divisor.`],{N,divisor});}
  if(form===1){const ds=pick([[3,4,7],[4,5,6],[3,5,8],[5,6,7]]),multiple=ds.reduce(lcm);out(`Find the smallest positive whole number which leaves remainder ${ds[0]-1} when divided by ${ds[0]}, remainder ${ds[1]-1} when divided by ${ds[1]}, and remainder ${ds[2]-1} when divided by ${ds[2]}.`,multiple-1,[`Adding one gives a multiple of ${ds.join(', ')}.`,`Their least common multiple is ${multiple}.`,`Required number = ${multiple} − 1 = ${multiple-1}. Check each remainder.`],{ds});}
  if(form===2){const [base,divisor]=pick([[2,7],[3,5],[2,5],[3,7]]),n=r(21,60),m=r(61,99),answer=(modPow(base,n,divisor)+modPow(base,m,divisor))%divisor;let cycle=[],v=1;do{v=v*base%divisor;cycle.push(v);}while(v!==1&&cycle.length<20);out(`A sequence begins ${base} and each term is obtained by multiplying the previous term by ${base}. What is the remainder when the sum of its ${n}th and ${m}th terms is divided by ${divisor}?`,answer,[`The remainders repeat in a cycle: ${cycle.join(', ')}.`,`The cycle length is ${cycle.length}. The terms have remainders ${modPow(base,n,divisor)} and ${modPow(base,m,divisor)}.`,`Add them and take the remainder again: ${answer}.`],{base,divisor,n,m});}
  if(form===3){const a=r(3,8),b=a+r(1,5),c=r(7,12),after=r(50,120),period=lcm(lcm(a,b),c),answer=(Math.floor(after/period)+1)*period;out(`Three lights flash together at the start. They then flash every ${a}, ${b} and ${c} seconds respectively. At how many seconds after the start will they first flash together strictly after ${after} seconds?`,answer,[`Simultaneous flashes repeat every LCM(${a}, ${b}, ${c}) = ${period} seconds.`,`Choose the first multiple of ${period} greater than ${after}.`,`That is ${answer} seconds after the start.`],{a,b,c,after},{suffix:'seconds'});}
 }else if(unit==='counting'){
  if(form===0){const n=r(5,13);out(`${n} players enter a tournament. Each pair plays exactly one match. How many matches are played?`,n*(n-1)/2,[`Each player has ${n-1} opponents.`,`${n} × ${n-1} counts every match twice, once for each player.`,`Matches = ${n} × ${n-1} ÷ 2 = ${n*(n-1)/2}.`],{n});}
  if(form===1){const cols=r(3,7),rows=r(2,5);out('How many rectangles, including squares, have their sides along the lines of the complete grid shown?',cols*(cols+1)*rows*(rows+1)/4,[`Choose two of the ${cols+1} vertical boundaries: ${cols*(cols+1)/2} choices.`,`Choose two of the ${rows+1} horizontal boundaries: ${rows*(rows+1)/2} choices.`,`Multiply: ${cols*(cols+1)*rows*(rows+1)/4} rectangles.`],{cols,rows},{figure:{kind:'grid',cols,rows,alt:`A complete rectangular grid with ${cols} columns and ${rows} rows; count all rectangles using its lines.`}});}
  if(form===2){const a=r(5,11),b=r(4,9);out(`A team must contain one pupil from a club of ${a} pupils and one from a different club of ${b} pupils. The clubs have no pupils in common. How many teams are possible?`,a*b,[`Each of the ${a} pupils in the first club can be paired with ${b} in the second.`,`These cases do not overlap because the clubs are distinct.`,`There are ${a*b} teams; do not divide by 2.`],{a,b});}
  if(form===3){const lines=r(7,15),parallel=r(2,4);out(`${lines} straight lines are drawn in a plane. Exactly ${parallel} of them are mutually parallel. No other pair is parallel, and no three lines meet at one point. What is the maximum number of regions formed?`,1+lines*(lines+1)/2-parallel*(parallel-1)/2,[`With no parallel lines or triple intersections, each added line creates one more region than the number of its intersections.`,`Total would be 1 + 1 + 2 + … + ${lines} = ${1+lines*(lines+1)/2}.`,`The parallel group removes ${parallel*(parallel-1)/2} pairwise intersections and hence that many regions.`,`Maximum = ${1+lines*(lines+1)/2-parallel*(parallel-1)/2}.`],{lines,parallel});}
 }else if(unit==='digits'){
  if(form===0){const a=r(5,9),b=r(1,a-1),sum=a+b,difference=9*(a-b);out(`A two-digit number has digit sum ${sum}. It is ${difference} greater than the number obtained by reversing its digits. Find the original number.`,10*a+b,[`Let the digits be a and b. Then a + b = ${sum}.`,`(10a+b) − (10b+a) = 9(a−b) = ${difference}.`,`So a − b = ${difference/9}. Solving gives a = ${a}, b = ${b}.`,`The number is ${10*a+b}.`],{sum,difference});}
  if(form===1){const digits=pick([3,4,5,6]),free=Math.ceil(digits/2);out(`How many ${digits}-digit positive integers are palindromes? A palindrome reads the same forwards and backwards.`,9*10**(free-1),[`Choose the first ${free} digits; the rest are determined by reflection.`,`The leading digit has 9 choices. Each other free digit has 10.`,`Count = 9 × 10^${free-1} = ${9*10**(free-1)}.`],{digits});}
  if(form===2){const divisor=pick([3,9]),lo=r(1,4),hi=r(6,9);let count=0;for(let a=lo;a<=hi;a++)for(let b=0;b<10;b++)if((101*a+10*b)%divisor===0)count++;out(`How many three-digit palindromes are divisible by ${divisor} and have a hundreds digit from ${lo} to ${hi}, inclusive?`,count,[`Write each palindrome as aba. Its digit sum is 2a + b.`,`For each a from ${lo} to ${hi}, list b = 0 to 9 satisfying divisibility by ${divisor}.`,`The cases are disjoint and give ${count} valid numbers.`],{divisor,lo,hi});}
  if(form===3){const limit=r(3,7);let count=0;for(let a=1;a<=limit;a++)for(let b=0;b<=limit;b++)for(let c=0;c<=limit;c++)if((2*a+2*b+c)%3===0)count++;out(`Only the digits 0 to ${limit} may be used, with repetition allowed. How many five-digit palindromes made from these digits are divisible by 3?`,count,[`Write the number as abcba, with a from 1 to ${limit}, and b,c from 0 to ${limit}.`,`Divisibility by 3 requires 2a + 2b + c to be divisible by 3.`,`For every pair (a,b), count the allowed c values. This complete case count is ${count}.`],{limit});}
 }else if(unit==='sums'){
  if(form===0){const first=r(12,45),last=first+r(30,80);out(`Find the sum of all integers from ${first} to ${last}, inclusive.`,(last-first+1)*(first+last)/2,[`There are ${last} − ${first} + 1 = ${last-first+1} terms.`,`Pair the first and last terms; the average term is (${first}+${last})/2.`,`Sum = ${last-first+1} × (${first}+${last}) ÷ 2 = ${(last-first+1)*(first+last)/2}.`],{first,last});}
  if(form===1){const last=2*r(30,100)+1;out(`Evaluate 1 − 2 + 3 − 4 + … − ${last-1} + ${last}.`,(last+1)/2,[`Pair (1−2), (3−4), and so on. There are ${(last-1)/2} pairs, each equal to −1.`,`The final term ${last} is unpaired.`,`Total = ${last} − ${(last-1)/2} = ${(last+1)/2}.`],{last});}
  if(form===2){const b=r(40,120),a=b+r(2,8);out(`Evaluate ${a}² − ${b}² without separately multiplying both squares.`,(a-b)*(a+b),['Use a² − b² = (a − b)(a + b).',`(${a} − ${b}) × (${a} + ${b}) = ${a-b} × ${a+b} = ${(a-b)*(a+b)}.`],{a,b});}
  if(form===3){const start=r(8,18),end=start+r(7,15),sum=n=>n*(n+1)*(2*n+1)/6;out(`Find ${start}² + ${start+1}² + … + ${end}².`,sum(end)-sum(start-1),['Use S(n) = 1² + … + n² = n(n+1)(2n+1)/6.',`Required sum = S(${end}) − S(${start-1}).`,`${sum(end)} − ${sum(start-1)} = ${sum(end)-sum(start-1)}.`],{start,end});}
 }else if(unit==='patterns'){
  if(form===0){const n=r(9,30);out(`A row of adjoining squares is built from matchsticks. The first square uses 4 sticks; each new square shares one complete side with its predecessor. How many sticks are needed for ${n} squares?`,3*n+1,[`After the first square there are ${n-1} additions.`,`Each adds 3 sticks.`,`Total = 4 + 3 × ${n-1} = ${3*n+1}.`],{n},{figure:{kind:'sticks',alt:'First three rows contain one, two and three adjoining squares, sharing full sides.'}});}
  if(form===1){const n=r(15,45),sticks=3*n+1;out(`A straight row of adjoining matchstick squares uses ${sticks} sticks. Every neighbouring pair shares one complete side. How many squares are in the row?`,n,[`For n squares, count = 4 + 3(n−1) = 3n+1.`,`3n + 1 = ${sticks}; n = (${sticks} − 1)/3 = ${n}.`],{sticks},{figure:{kind:'sticks'}});}
  if(form===2){const n=r(12,35),first=r(2,6),increment=r(2,4);out(`A tile staircase has ${n} rows. The top row has ${first} tiles, and each row below has ${increment} more tiles than the preceding row. How many tiles are there altogether?`,n*(2*first+(n-1)*increment)/2,[`Bottom row = ${first} + (${n} − 1) × ${increment} = ${first+(n-1)*increment}.`,`The rows form an arithmetic sequence.`,`Total = ${n} × (${first} + ${first+(n-1)*increment}) ÷ 2 = ${n*(2*first+(n-1)*increment)/2}.`],{n,first,increment});}
  if(form===3){const k=r(12,30),tail=r(1,k+1),N=k*(k+1)/2+tail;out(`A sequence is made in blocks: one 1, then two 2s, then three 3s, and so on. What is the value of the ${N}th term?`,k+1,[`Blocks 1 to ${k} contain ${k} × ${k+1} ÷ 2 = ${k*(k+1)/2} terms.`,`The next block contains ${k+1} copies of ${k+1}.`,`Position ${N} is ${tail} places into that block, so its value is ${k+1}.`],{N});}
 }else if(unit==='spirals'){
  const N=form===0?r(27,60):r(220,750),p=F.spiral(N-1);let pairs=0;while((pairs+1)*(pairs+2)<=N-1)pairs++;const used=pairs*(pairs+1),start=(pairs%2?1:-1)*Math.ceil(pairs/2),remaining=N-1-used;
  const spiralSteps=[`Number ${N} requires ${N-1} moves because 1 is already at the centre.`,`Group lengths into pairs: (1,1), (2,2), … . The first ${pairs} complete pairs use ${pairs} × ${pairs+1} = ${used} moves.`,`At the end of those pairs the point is (${start}, ${start}). A complete pair of odd length moves right then up; one of even length moves left then down.`,`There are ${remaining} moves left. The next directions are ${pairs%2?'left then down':'right then up'}, with at most ${pairs+1} moves on each segment.`,`The resulting point is (${p.x}, ${p.y}); choose only the coordinate asked for.`];
  if(form===0||form===2)out(`Numbers begin with 1 at the centre of a square spiral. From 1, move right 1 step, up 1, left 2, down 2, right 3, up 3, and continue the pattern. What is the horizontal coordinate of ${N}, taking the centre as 0 and right as positive?`,p.x,spiralSteps,{N},{figure:{kind:'spiral',alt:'First 25 values of a counterclockwise square spiral beginning by moving right. Larger requested values are outside the displayed sample.'}});
  if(form===1){const length=r(50,250),p=F.spiral(length),last=p.segments.at(-1);out(`A pen draws a square spiral with segment lengths 1, 1, 2, 2, 3, 3, … cm, turning left after each segment. It stops after drawing exactly ${length} cm. How much of its final segment has it drawn? Count the final segment even when it is complete.`,last.length,[`Add complete lengths in the order 1,1,2,2,… .`,`Before the final segment, ${length-last.length} cm has been drawn.`,`The final drawn portion is ${length} − ${length-last.length} = ${last.length} cm.`],{length},{suffix:'cm',figure:{kind:'spiralPath',alt:'A line turns left after segments of lengths 1,1,2,2,3,3 and so on. Only an initial sample is drawn, not the final requested length.'}});}
  if(form===3)out(`A square spiral begins with 1 at the centre and moves right, up, left, down with successive step counts 1, 1, 2, 2, 3, 3, … . What is the vertical coordinate of number ${N}, using 0 at the centre and up as positive?`,p.y,spiralSteps,{N},{figure:{kind:'spiral'}});
 }else if(unit==='cases'){
  if(form===0||form===1){const labels=['A','B','C'],rotation=r(0,2),a=labels[rotation],b=labels[(rotation+1)%3],c=labels[(rotation+2)%3];out(`A token is in exactly one of boxes A, B or C. The labels read: ${a}: “The token is in ${b}.” ${b}: “The token is not in ${b}.” ${c}: “The token is not in ${c}.” Exactly one label is true. Which box contains the token?`,c,[`The first two statements are opposites, so exactly one of them is always true.`,`The third statement must therefore be false.`,`So the token is in ${c}. Check that only one label is true in that case.`],{a,b,c},{choices:['A','B','C']});}
  if(form===2){const a=r(5,9),b=r(1,4),total=11*(a+b),difference=a-b;out(`A and B are different non-zero digits. The two-digit numbers AB and BA have sum ${total}. A is ${difference} greater than B. Find AB.`,10*a+b,[`AB + BA = 11(A+B), so A+B = ${total/11}.`,`Also A−B = ${difference}.`,`Solve: A = ${a}, B = ${b}.`,`AB = ${10*a+b}; check the column addition and both non-zero digits.`],{total,difference});}
  if(form===3){const n=r(25,60),a=r(2,5),b=r(6,10),total=a*n+b*(n+1);out(`A positive whole number x satisfies both conditions: ${a}x + ${b}y = ${total}, and y = x + 1. What is the value of x + y?`,2*n+1,[`Substitute y = x+1 into the first condition.`,`${a+b}x + ${b} = ${total}, so x = ${n}.`,`Then y = ${n+1}; x+y = ${2*n+1}.`,`Both positive-integer conditions are satisfied.`],{a,b,total});}
 }else if(unit==='invariants'){
  if(form===0){const start=2*r(3,12),target=start+2*r(3,10)+1;out(`Start with ${start}. A move may add 6 or subtract 4; negative intermediate values are allowed. Is it possible to reach ${target}?`, 'No',[`The start ${start} is even.`,`Both allowed changes are even, so every reachable number is even.`,`${target} is odd, so it cannot be reached.`],{start,target},{choices:['Yes','No']});}
  if(form===1){const N=r(8,22)**2+r(0,9);out(`${N} switches are initially off and numbered 1 to ${N}. On pass k, every switch whose number is a multiple of k is flipped, for k = 1 to ${N}. How many switches are on at the end?`,Math.floor(Math.sqrt(N)),['Switch n is flipped once for each positive factor of n.','Only perfect squares have an odd number of positive factors. ',`Count the squares at most ${N}: there are ${Math.floor(Math.sqrt(N))}.`],{N});}
  if(form===2){const colours=r(3,8),need=r(3,6);out(`A bag has many beads of each of ${colours} colours, at least ${need} of every colour. What is the smallest number of beads that must be drawn without looking to guarantee ${need} of the same colour?`,colours*(need-1)+1,[`In the worst case, draw ${need-1} of every colour without reaching ${need}.`,`That is ${colours*(need-1)} beads.`,`One more guarantees ${need} of one colour, so ${colours*(need-1)+1} are required.`],{colours,need});}
  if(form===3){const n=2*r(6,15);out(`Cards are numbered 1 to ${n}, once each. What is the smallest number of cards that must be selected to guarantee that two selected numbers have sum ${n+1}?`,n/2+1,[`Pair 1 with ${n}, 2 with ${n-1}, and so on. There are ${n/2} disjoint pairs.`,`It is possible to take one from every pair and avoid the required sum.`,`Taking ${n/2+1} forces one complete pair.`],{n});}
 }else if(unit==='bounds'){
  if(form===0||form===2){const budget=r(22,45),costs=form===0?[4,7]:[4,7,11],counts=form===0?[5,9]:[5,9,15],best=bestPacks(budget,costs,counts);out(`Puzzle tokens are sold only in complete packs. ${counts.map((n,i)=>`A pack of ${n} costs $${costs[i]}`).join('; ')}. With $${budget}, what is the greatest number of tokens that can be bought?`,best.best,[`Enumerate each possible count of the largest pack from 0 to ${Math.floor(budget/costs.at(-1))}.`,`For each remaining budget, compare complete smaller packs.`,`The best combination is ${best.winner.map((n,i)=>`${n} pack(s) of ${counts[i]}`).join(', ')}.`,`It gives ${best.best} tokens and costs $${best.winner.reduce((s,n,i)=>s+n*costs[i],0)}. The enumeration covers all affordable cases.`],{budget,costs,counts});}
  if(form===1){const total=r(30,50),a=total-r(5,12),b=total-r(8,15);out(`In a group of ${total} pupils, ${a} play chess and ${b} play badminton. What is the smallest possible number who play both?`,a+b-total,[`The two counts add to ${a+b}, exceeding the population by ${a+b-total}.`,`At least ${a+b-total} must be counted in both groups.`,`This is attainable by having everyone in at least one group, so it is the minimum.`],{total,a,b});}
  if(form===3){const a=r(15,30),b=r(12,25),both=r(5,10),total=a+b-both+r(2,20);out(`Of ${total} pupils, ${a} join robotics, ${b} join music, and ${both} join both. How many join neither club?`,total-a-b+both,[`Count the union once: ${a} + ${b} − ${both} = ${a+b-both}.`,`Neither = total − union = ${total} − ${a+b-both} = ${total-a-b+both}.`],{total,a,b,both});}
 }
 if(!q)throw Error('Unimplemented template');
 q.answerLabel??=typeof q.answer==='object'?`${q.answer.a}+${q.answer.b}π`:String(round(Number(q.answer))===Number(q.answer)?q.answer:q.answer);
 q.fingerprint=hash(q.text+'|'+JSON.stringify(q.figure||{}));return q;
}
// Restricted arithmetic parser, never eval. A pair [a,b] represents a + bπ.
function parse(input,suffix=''){
 let s=String(input).trim().toLowerCase().replace(/−|–/g,'-').replace(/×/g,'*').replace(/÷/g,'/').replace(/π/g,'pi').replace(/,/g,'').replace(/^\$\s*/,'');
 const units={cm:['cm','centimetres','centimeters'],m:['m','metres','meters'],'cm²':['cm²','cm2','square centimetres'],'m²':['m²','m2','square metres'],hours:['hours','hour','h'],minutes:['minutes','minute','min'],seconds:['seconds','second','s'],years:['years','year'],litres:['litres','liters','l'],'km/h':['km/h'],km:['km'],'°':['°','degrees','deg']};
 for(const u of units[suffix]||[]){if(s.endsWith(u)){s=s.slice(0,-u.length).trim();break;}}
 s=s.replace(/(-?\d+)\s+(\d+)\s*\/\s*(\d+)/g,(_,a,b,c)=>a[0]==='-'?`(-(${a.slice(1)}+${b}/${c}))`:`(${a}+${b}/${c})`).replace(/\s+/g,'').replace(/(\d|\))(?=pi|\()/g,'$1*').replace(/pi(?=\d|\()/g,'pi*');
 if(!s||s.length>180)return null;const tokens=s.match(/pi|(?:\d+(?:\.\d*)?|\.\d+)|[()+*/-]/g)||[];if(tokens.join('')!==s||tokens.length>100)return null;let i=0;
 const sum=(a,b,sign)=>[a[0]+sign*b[0],a[1]+sign*b[1]];
 function factor(){const t=tokens[i++];if(t==='+')return factor();if(t==='-'){const x=factor();return x.map(n=>-n);}if(t==='('){const x=expr();if(tokens[i++]!==')')throw Error();return x;}if(t==='pi')return [0,1];if(t!==undefined&&Number.isFinite(Number(t)))return [Number(t),0];throw Error();}
 function term(){let a=factor();while(tokens[i]==='*'||tokens[i]==='/'){const op=tokens[i++],b=factor();if(op==='*'){if(a[1]&&b[1])throw Error();a=[a[0]*b[0],a[0]*b[1]+a[1]*b[0]];}else{if(b[1]||!b[0])throw Error();a=a.map(x=>x/b[0]);}}return a;}
 function expr(){let a=term();while(tokens[i]==='+'||tokens[i]==='-'){const sign=tokens[i++]==='+'?1:-1;a=sum(a,term(),sign);}return a;}
 try{const a=expr();return i===tokens.length&&a.every(Number.isFinite)?a.map(n=>n===0?0:n):null;}catch(_){return null;}
}
function mark(q,input){if(typeof q.answer==='string')return String(input).trim().toLowerCase()===q.answer.toLowerCase();const a=parse(input,q.suffix),b=typeof q.answer==='object'?[q.answer.a,q.answer.b]:[q.answer,0];return !!a&&a.every((x,i)=>Math.abs(x-b[i])<=1e-9*Math.max(1,Math.abs(b[i])));}
root.MochiEntranceBank={make,mark,parse,hash,fraction,modPow,exposed,bestPacks};if(typeof module!=='undefined')module.exports=root.MochiEntranceBank;
})(typeof globalThis!=='undefined'?globalThis:this);
