/* New DSA-bridge science units (sx-): cells, machines, pressure, waves, chemistry and life.
   Original questions mixing conclusion+reason choices, numeric entry, variable roles and short
   written explanations marked by key ideas. Synthetic data are illustrative, not real results. */
(function(root){
'use strict';
root.MochiSciencePathSX=function(h){
const {pair,statements,table,numeric,written,roles,idea,bar}=h,S={};
const pick=(r,a)=>a[r.int(0,a.length-1)];
const round=(n,d=6)=>Math.round(n*10**d)/10**d;
const others=(r,all,keep,n)=>{const rest=all.filter(x=>x!==keep),out=[];while(out.length<n&&rest.length){out.push(rest.splice(r.int(0,rest.length-1),1)[0]);}return out;};
// Shared key-idea groups.
const NOT=['not','no$','never','without','lack','none'];
const SAME=['same','constant','equal','identical','fixed','unchanged','kept','similar'];
const COMPETE=idea('Seedlings grow away from the parent, so there is less competition',['competi','compete','crowd','overcrowd','share','fight','space','sunlight','water','nutrient','mineral','room'],['parent','less','fewer','not','away','reduc','enough','more','own']);

/* ---------------- Cells ---------------- */
const PARTS={
 membrane:{name:'The cell membrane',fn:'controls which substances enter and leave the cell',reason:'The membrane lets some substances through and keeps others out.',wrong:['The cell wall is the outer layer, so it decides what can enter.','The nucleus controls everything, so it lets substances in itself.']},
 wall:{name:'The cell wall',fn:'gives a plant cell a fixed shape and support',reason:'The fairly rigid wall outside the membrane holds the cell’s shape.',wrong:['The thin membrane is the strongest layer, so it holds the shape.','The nucleus is the hardest part, so it keeps the whole cell rigid.']},
 nucleus:{name:'The nucleus',fn:'contains genetic material and controls the cell’s activities',reason:'Genetic material in the nucleus carries the cell’s instructions.',wrong:['The cytoplasm holds the instructions, as it fills most of the cell.','The membrane controls the cell, as it touches everything outside.']},
 cytoplasm:{name:'The cytoplasm',fn:'is where most of the cell’s chemical reactions take place',reason:'The jelly-like cytoplasm is where most cell reactions happen.',wrong:['Every reaction happens in the nucleus, as it controls the cell.','Reactions happen in the cell wall, as it is the busiest layer.']},
 chloroplast:{name:'The chloroplast',fn:'traps light energy to make food',reason:'Chloroplasts contain chlorophyll, which traps light energy.',wrong:['The nucleus makes the food, because it controls the whole cell.','The cell wall traps light, as it is the outermost layer.']}
};
const CELL_LABEL={membrane:'cell membrane',wall:'cell wall',nucleus:'nucleus',cytoplasm:'cytoplasm',chloroplast:'chloroplast',vacuole:'vacuole'};
const CELL_TYPES=[
 {key:'leaf',row:['yes','yes','yes'],claim:'A cell from a plant leaf',reason:'A cell wall shows a plant cell, and chloroplasts suggest a leaf.'},
 {key:'root',row:['yes','no','yes'],claim:'A cell from a plant root',reason:'A cell wall shows a plant cell; no chloroplasts suits a root.'},
 {key:'animal',row:['no','no','yes'],claim:'A cell from an animal',reason:'No cell wall but a nucleus points to an animal cell.'},
 {key:'bacterium',row:['yes','no','no'],claim:'A single bacterium cell',reason:'A cell wall but no nucleus fits a bacterium, not a plant.'}
];
const CELL_WRONG=['Cells without chloroplasts must always come from an animal.','Any cell that has a nucleus must be a plant cell.','Only animal cells are surrounded by a cell membrane.'];
S['sx-cells']=[
 r=>{const v=r.int(0,2);
  if(v===0){const key=pick(r,Object.keys(PARTS)),p=PARTS[key],opts=others(r,Object.keys(PARTS),key,3).map(k=>PARTS[k].name);
   return pair(`Which part of a plant cell ${p.fn}?`,p.name,opts,p.reason,p.wrong,[`Recall the job of each part: ${p.name.toLowerCase()} ${p.fn}.`,'Plant and animal cells share the membrane, cytoplasm and nucleus; plant cells add a wall and often chloroplasts.']);}
  if(v===1){const c=pick(r,CELL_TYPES),wrong=CELL_TYPES.filter(x=>x!==c).map(x=>x.claim),wr=c.key==='leaf'?[CELL_WRONG[1],CELL_WRONG[2]]:c.key==='animal'?[CELL_WRONG[1],CELL_WRONG[2]]:[CELL_WRONG[0],CELL_WRONG[1]];
   return pair('A cell is examined under a microscope. The table records what was seen. Which is it most likely to be?',c.claim,wrong,c.reason,wr,['Use several features together.','A cell wall points to a plant (or a bacterium); chloroplasts point to a cell that receives light; a nucleus is missing in bacteria.'],table(['Feature','Seen?'],[['Cell wall',c.row[0]],['Chloroplasts',c.row[1]],['Nucleus',c.row[2]]],'Observations of one cell (synthetic)'));}
  const target=pick(r,['nucleus','chloroplast','wall','vacuole']),letters=['P','Q','R','S'],pool=['wall','membrane','nucleus','chloroplast','vacuole'].filter(x=>x!==target),chosen=[target,...others(r,pool,null,3)];
  const order=chosen.slice().sort(()=>0).map((x,i)=>x);for(let i=order.length-1;i>0;i--){const j=r.int(0,i);[order[i],order[j]]=[order[j],order[i]];}
  const marks=order.map((part,i)=>[letters[i],part]),answer=letters[order.indexOf(target)];
  const Q={nucleus:['controls the cell’s activities','The nucleus is the round body that holds genetic material.',['The largest part of a cell must be the one in control.','The outer layer controls the cell, since it is on the outside.']],chloroplast:['traps light energy for photosynthesis','Chloroplasts are the small green bodies containing chlorophyll.',['The largest part of a cell must be where light is trapped.','The outermost layer traps light, as light reaches it first.']],wall:['gives the plant cell its fixed shape','The cell wall is the firm outer layer outside the membrane.',['The large vacuole is the firm layer that holds the shape.','The nucleus is the firmest part, so it holds the shape.']],vacuole:['stores cell sap','The large central vacuole is a space filled with cell sap.',['The nucleus stores sap, as it is the biggest round part.','Sap is stored in the cell wall, which is thick and spongy.']]}[target];
  return pair(`The diagram shows a plant cell with four labelled parts. Which labelled part ${Q[0]}?`,`Part ${answer}`,letters.filter(x=>x!==answer).map(x=>`Part ${x}`),Q[1],Q[2],['Match each labelled part to its shape and position.','Then recall the job of that part.'],{type:'cell',cell:'plant',marks});},
 r=>{const v=r.int(0,2);
  if(v===0){const e=pick(r,[5,10,15]),o=pick(r,[4,10,40,100]);return numeric(`A microscope has a ×${e} eyepiece lens and a ×${o} objective lens. What is the total magnification?`,e*o,{unit:'×',units:['×','x','times'],method:'Total magnification = eyepiece magnification × objective magnification.',steps:[`Total magnification = ${e} × ${o}.`,`= ×${e*o}.`]});}
  if(v===1){const a=pick(r,[0.02,0.025,0.04,0.05,0.06,0.08,0.1]),M=pick(r,[100,200,400,500]),img=round(a*M);return numeric(`A cell is ${a} mm across. A microscope magnifies it ×${M}. How wide is the image of the cell, in millimetres?`,img,{unit:'mm',units:[['mm',1],['cm',10],['millimetres',1]],tol:0.001,method:'Image size = actual size × magnification.',steps:[`Image size = ${a} mm × ${M}.`,`= ${img} mm.`]});}
  const c=pick(r,[{s:'onion bulb skin',row:['yes','no','yes'],claim:'Sample Y, from an onion bulb'},{s:'leaf',row:['yes','yes','yes'],claim:'Sample X, from a leaf'},{s:'human cheek',row:['no','no','yes'],claim:'Sample Z, from a human cheek'}]);
  const rows={leaf:['X','yes','yes','yes'],onion:['Y','yes','no','yes'],cheek:['Z','no','no','yes']};
  const all=['Sample X, from a leaf','Sample Y, from an onion bulb','Sample Z, from a human cheek','None of the three samples'];
  const reason=c.s==='leaf'?'Only X has both a cell wall and chloroplasts, as leaf cells do.':c.s==='human cheek'?'Only Z has no cell wall, which fits an animal cell.':'Y has a cell wall but no chloroplasts, like cells grown in the dark.';
  return pair(`Three slides of cells are labelled X, Y and Z. One is from ${c.s==='human cheek'?'a human cheek':c.s==='leaf'?'a leaf':'an onion bulb'}. Which slide is it?`,c.claim,all.filter(x=>x!==c.claim),reason,['Every plant cell has chloroplasts, so any cell without them is an animal cell.','A cell without a cell wall must come from a plant root.'],['Compare the features of each sample.','Onion bulb cells grow underground, so they have walls but no chloroplasts.'],table(['Slide','Cell wall','Chloroplasts','Nucleus'],[rows.leaf,rows.onion,rows.cheek],'Microscope observations (synthetic)'));},
 r=>{const v=r.int(0,2);
  if(v===0){const thing=pick(r,['a carrot root','an onion bulb']);return written(`A pupil says, “All plant cells have chloroplasts.” She looks at cells from ${thing} and sees cell walls but no chloroplasts. Do her observations support her claim? Explain your answer.`,{key:'cells-not-all-green',ideas:[
    idea('Claim: no, not all plant cells have chloroplasts',['not all','not every','some plant cells','wrong','incorrect','disagree','false','not support','do not support','does not support','not true','not correct','untrue','no not']),
    idea('Evidence: these cells have walls (plant cells) but no chloroplasts',['root','carrot','onion','bulb','these cells','her cells','the cells'],['no chloroplast','not have chloroplast','not have any chloroplast','without chloroplast','lack','none','no green','not contain chloroplast','not see chloroplast','not see any chloroplast']),
    idea('Reason: these parts grow without light, so they do not photosynthesise',['light','dark','underground','under the ground','in the soil','sunlight','photosynth','make food','make their own food','make its own food'])],
   model:`No, her observations do not support the claim. The cells from ${thing} have cell walls, so they are plant cells, but they have no chloroplasts. This part of the plant grows underground where there is no light, so its cells do not photosynthesise and do not need chloroplasts.`,steps:['State whether the claim is supported.','Quote the observation: plant cells (walls) without chloroplasts.','Explain: no light reaches them, so they do not photosynthesise.']});}
  if(v===1)return pair('A single-celled pond organism has chloroplasts and swims using a whip-like tail. A pupil says it must be an animal because it moves. Which evaluation is best?','Its chloroplasts suggest it makes food, so moving alone does not decide.',['It must be an animal, because only animals can move from place to place.','It must be a plant, because its tail helps it swim towards the sunlight.','It cannot be living, as one cell is too small to carry out life processes.'],'Chloroplasts are used for photosynthesis, which animals cannot do.',['Moving about is the one feature that only animals ever have.','A single cell cannot carry out all the processes of life alone.'],['Movement is shared by many groups.','Chloroplasts show the organism can photosynthesise; a single cell can be a whole organism.']);
  return statements('Yeast is a fungus made of single cells. Each cell has a cell wall and a nucleus. Evaluate these statements.',[['One yeast cell can take in food, respire and reproduce.',true],['Yeast must be a plant, because it has a cell wall.',false],['Yeast cells have no nucleus, just like bacteria.',false]],'A single cell can carry out every life process; a wall alone does not decide.',['Any organism with a cell wall must belong to the plant group.','All single-celled organisms lack a nucleus, just as bacteria do.'],['A unicellular organism carries out all life processes in one cell.','Fungi, plants and bacteria have walls; use several features to classify.']);},
 r=>{const v=r.int(0,2);
  if(v===0){const a=pick(r,[0.02,0.025,0.04,0.05,0.06,0.08]),M=pick(r,[200,400,500]),img=round(a*M);return numeric(`Under a ×${M} microscope, the image of a cell is ${img} mm wide. What is the actual width of the cell, in millimetres?`,a,{unit:'mm',units:[['mm',1],['millimetres',1],['µm',0.001],['um',0.001],['micrometres',0.001]],tol:0.0005,method:'Actual size = image size ÷ magnification.',steps:[`Actual size = ${img} mm ÷ ${M}.`,`= ${a} mm.`]});}
  if(v===1){const each=pick(r,[0.02,0.04,0.05,0.08]),n=pick(r,[15,20,25,30,40]),len=round(each*n);return numeric(`A row of identical cells seen under a microscope is ${len} mm long. Each cell is ${each} mm long. How many cells are in the row?`,n,{unit:'cells',units:['cells','cell'],method:'Number of cells = total length ÷ length of one cell.',steps:[`Number of cells = ${len} ÷ ${each}.`,`= ${n} cells.`]});}
  return statements('Compare the plant and animal cells studied in school science. Evaluate these statements.',[['Both plant and animal cells have a cell membrane.',true],['Every plant cell contains chloroplasts.',false],['Of the two, only plant cells have a cell wall.',true]],'Membranes are shared; only some plant cells have chloroplasts.',['Animal cells have no membrane, since they have no cell wall.','All plant cells are green, so every one contains chloroplasts.'],['List the parts shared by both cell types.','Remember that root and bulb cells have no chloroplasts.']);}
];

/* ---------------- Levers, pulleys and ramps ---------------- */
const lever=(left,right,unit='m')=>({type:'lever',left,right,unit});
S['sx-machines']=[
 r=>{const v=r.int(0,1);
  if(v===0){const spanner=r.int(0,1);
   if(spanner)return pair('A pupil wants to loosen a tight nut with a spanner using as little force as possible. Where should she hold the spanner?','At the far end of the handle',['Close to the nut, near the pivot','In the middle of the handle','Anywhere, as it makes no difference'],'A larger distance from the pivot gives a larger moment.',['The turning effect depends only on how hard you push.','Holding near the nut is best, as that is where it turns.'],['The nut is the pivot.','Moment = force × perpendicular distance, so a longer distance needs less force.']);
   return pair('A pupil pushes a door with the same force at different points. Where does the push have the largest turning effect?','At the handle, far from the hinges',['Halfway between handle and hinges','Right next to the hinges','It is the same at every point'],'A larger distance from the pivot gives a larger moment.',['The turning effect depends only on how hard you push.','Pushing near the hinges is best, as that is where it turns.'],['The hinges are the pivot.','Moment = force × perpendicular distance from the pivot.']);}
  const F=r.int(4,40),cm=pick(r,[20,25,40,50,60,80]),d=cm/100;return numeric(`A force of ${F} N acts at right angles to a spanner, ${cm} cm from the centre of the nut. What is the moment of the force about the nut, in newton metres (N m)?`,round(F*d),{unit:'N m',units:[['N m',1],['Nm',1],['N·m',1],['newton metres',1],['N cm',0.01],['Ncm',0.01]],tol:0.001,method:'Moment = force × perpendicular distance from the pivot.',steps:[`Distance = ${cm} cm = ${d} m.`,`Moment = ${F} N × ${d} m = ${round(F*d)} N m.`]});},
 r=>{const v=r.int(0,2),x=r.int(2,6);let y=r.int(2,6);if(y===x)y=x===6?2:x+1;const c=pick(r,[5,6,8,10]),d1=x*0.5,d2=y*0.5,m1=y*c,m2=x*c;
  if(v===0)return numeric(`A uniform plank is balanced at its centre. A ${m1} kg sack hangs ${d1} m to the left of the pivot. What mass must hang ${d2} m to the right of the pivot to balance it?`,m2,{unit:'kg',units:[['kg',1],['g',0.001]],method:'Balanced: mass × distance on the left = mass × distance on the right.',steps:[`Left: ${m1} × ${d1} = ${m1*d1}.`,`Right: mass × ${d2} = ${m1*d1}, so mass = ${m1*d1} ÷ ${d2} = ${m2} kg.`],figure:lever([[`${m1} kg`,d1]],[['?',d2]])});
  if(v===1)return numeric(`A ${m1} kg child sits ${d1} m from the pivot of a balanced see-saw. How far from the pivot, in metres, must a ${m2} kg child sit on the other side?`,d2,{unit:'m',units:[['m',1],['cm',0.01],['metres',1]],tol:0.001,method:'Balanced: mass × distance is equal on both sides of the pivot.',steps:[`Left: ${m1} × ${d1} = ${m1*d1}.`,`Distance = ${m1*d1} ÷ ${m2} = ${d2} m.`],figure:lever([[`${m1} kg`,d1]],[[`${m2} kg`,'?']])});
  const a=pick(r,[[20,1.5,30,1],[30,1,20,2],[25,2,40,1],[40,1.5,30,2],[30,2,20,3]]),L=a[0]*a[1],R=a[2]*a[3],flip=r.int(0,1),left=flip?[a[2],a[3]]:[a[0],a[1]],right=flip?[a[0],a[1]]:[a[2],a[3]],lm=left[0]*left[1],rm=right[0]*right[1];
  const claim=lm>rm?'The left side goes down.':rm>lm?'The right side goes down.':'The plank stays balanced.';
  return pair(`A plank is pivoted at its centre. ${left[0]} kg hangs ${left[1]} m left of the pivot and ${right[0]} kg hangs ${right[1]} m right of the pivot. What happens when it is released?`,claim,['The left side goes down.','The right side goes down.','The plank stays balanced.','It swings, then always ends level.'].filter(x=>x!==claim),lm===rm?`Both sides have mass × distance = ${lm}, so the moments balance.`:`Left gives ${lm} and right gives ${rm}; the larger moment wins.`,['The side with the heavier load always goes down.','The side whose load hangs further out always goes down.'],[`Left: ${left[0]} × ${left[1]} = ${lm}.`,`Right: ${right[0]} × ${right[1]} = ${rm}.`],lever([[`${left[0]} kg`,left[1]]],[[`${right[0]} kg`,right[1]]]));},
 r=>{const v=r.int(0,2);
  if(v===0){const load=pick(r,[100,150,200,240,300]);return pair(`Which arrangement needs the smallest effort to lift a ${load} N load? Ignore friction and the weight of the pulleys.`,'A single movable pulley',['A single fixed pulley','Lifting the load straight up','A fixed pulley with a longer rope'],'Two rope sections share the load, so each pulls about half.',['A fixed pulley halves the effort because the rope bends over a wheel.','A longer rope always reduces the effort needed to lift a load.'],['A fixed pulley changes direction only: effort ≈ load.',`A movable pulley is held by two rope sections: effort ≈ ${load/2} N.`],{type:'pulley',kind:'movable',load:`${load} N`});}
  if(v===1){const load=pick(r,[80,120,160,200,250,300]),movable=r.int(0,1);return numeric(`A ${load} N load is lifted at a steady speed using a single ${movable?'movable':'fixed'} pulley. Ignoring friction and the pulley’s weight, what effort is needed, in newtons?`,movable?load/2:load,{unit:'N',units:['N','newtons'],method:movable?'Two rope sections support the load, so ideal effort = load ÷ 2.':'A fixed pulley only changes direction, so ideal effort = load.',steps:movable?[`Effort = ${load} ÷ 2 = ${load/2} N.`,'You must pull twice as much rope as the height the load rises.']:[`Effort = load = ${load} N.`,'The pulley lets you pull down instead of lifting up.'],figure:{type:'pulley',kind:movable?'movable':'fixed',load:`${load} N`}});}
  return written('Two ramps lead up to the same platform. Ramp A is short and steep; ramp B is long and gentle. Explain why it is easier to push a trolley up ramp B, and what you have to give up in exchange.',{key:'ramp-tradeoff',ideas:[
    idea('A smaller force (effort) is needed on the gentle ramp',['less','small','lower','reduc','not as much','weaker'],['force','effort','strength','push']),
    idea('The trolley must be pushed over a longer distance',['longer','further','farther','more distance','greater distance','long way','twice as far','long distance'])],
   contradictions:[idea('Says the trolley becomes lighter',['lighter','less weight','weighs less','less mass','loses weight','loses mass'])],
   model:'Ramp B needs a smaller force to push the trolley because it rises gently. In exchange, I have to push the trolley over a longer distance to reach the same height. The trolley’s weight does not change.',steps:['Both ramps raise the trolley to the same height.','The gentle ramp spreads the job over a longer distance, so less force is needed.']});},
 r=>{const v=r.int(0,2);
  if(v===0){const m1=pick(r,[10,20,30]),d1=pick(r,[1,2]),m2=pick(r,[10,20]),d2=pick(r,[0.5,1.5]),d3=pick(r,[1,2,2.5]),total=m1*d1+m2*d2,ans=round(total/d3,3);return numeric(`On a beam pivoted at its centre, ${m1} kg hangs ${d1} m and ${m2} kg hangs ${d2} m to the left of the pivot. What single mass, ${d3} m to the right, balances the beam?`,ans,{unit:'kg',units:[['kg',1],['g',0.001]],tol:0.01,method:'Add the moments on the left; the right-hand moment must equal the total.',steps:[`Left: ${m1} × ${d1} + ${m2} × ${d2} = ${total}.`,`Mass = ${total} ÷ ${d3} = ${ans} kg.`],figure:lever([[`${m1} kg`,d1],[`${m2} kg`,d2]],[['?',d3]])});}
  if(v===1)return statements('Ignore friction and the weight of the pulleys. Evaluate these statements about simple machines.',[['A single fixed pulley changes the direction of the effort.',true],['A single movable pulley lets you lift a load by pulling less rope.',false],['A ramp reduces the force needed but increases the distance moved.',true]],'Machines trade force for distance; they never give out extra energy.',['A movable pulley halves both the effort and the rope you must pull.','A fixed pulley halves the effort because the rope goes over a wheel.'],['A movable pulley halves the effort but doubles the rope pulled.','Less force over more distance does the same job.']);
  return written('On a see-saw, a heavier child must sit nearer the pivot than a lighter child for it to balance. Explain why, using the idea of moments.',{key:'seesaw-moments',ideas:[
    idea('Moment = weight (force) × distance from the pivot',['moment','turning effect','turning'],['distance','far','near','close','long']),
    idea('The heavier child’s larger weight needs a smaller distance',['heav','more weight','bigger weight','more mass','larger mass','greater weight','greater mass','weighs more'],['near','closer','shorter','smaller distance','less distance','smaller','nearer']),
    idea('Balanced when the two moments are equal',['equal','same','balanc','cancel'],['moment','turning','side'])],
   model:'Each child’s moment is their weight multiplied by their distance from the pivot. The heavier child has a larger weight, so a smaller distance gives the same moment as the lighter child further away. When the clockwise and anticlockwise moments are equal, the see-saw balances.',steps:['Moment = force × perpendicular distance.','Balance needs equal moments on each side.','A larger force × smaller distance can equal a smaller force × larger distance.']});}
];

/* ---------------- Pressure ---------------- */
const P_UNITS=['N/cm²','N/cm2','N per cm²','N per cm2','newtons per square centimetre','N per square cm'];
S['sx-pressure']=[
 r=>{const v=r.int(0,1);
  if(v===0){const c=pick(r,[
   {text:'Why is a person less likely to sink into soft snow when wearing wide snowshoes?',claim:'The weight is spread over a bigger area, so pressure is lower.',wrong:['Snowshoes make the person lighter, so they press less on the snow.','Snowshoes increase the pressure and pack the snow down firmly.','The wide shoes push the person’s weight upwards off the snow.'],reason:'Pressure = force ÷ area: same weight, larger area, lower pressure.'},
   {text:'Using the same push, why does a sharp knife cut bread more easily than a blunt one?',claim:'The thin edge has a smaller area, so the pressure is greater.',wrong:['A sharp knife always pushes with a much larger force than a blunt one.','The thin edge spreads the push out over a larger area of the bread.','A sharp knife is heavier, so it presses down harder on the bread.'],reason:'Pressure = force ÷ area: same push, smaller area, higher pressure.'},
   {text:'Why are tractors used on soft, muddy fields fitted with very wide tyres?',claim:'Wide tyres spread the weight, so the pressure on the mud is lower.',wrong:['Wide tyres make the tractor lighter, so it presses less on the mud.','Wide tyres increase the pressure, so they grip the mud more firmly.','Wide tyres push the mud aside so the tractor rolls on hard ground.'],reason:'Pressure = force ÷ area: same weight, larger area, lower pressure.'}]);
   return pair(c.text,c.claim,c.wrong,c.reason,['A larger area means a larger force pushes down on the ground.','Pressure depends only on the weight, not on the area touched.'],['Identify the force (weight or push) and the area.','Pressure = force ÷ area.']);}
  const A=pick(r,[2,4,5,8,10]),p=pick(r,[3,5,6,12,15,20]),F=A*p;return numeric(`A force of ${F} N presses on an area of ${A} cm². What pressure does it exert, in N/cm²?`,p,{unit:'N/cm²',units:P_UNITS,method:'Pressure = force ÷ area.',steps:[`Pressure = ${F} N ÷ ${A} cm².`,`= ${p} N/cm².`]});},
 r=>{const v=r.int(0,2),dims=pick(r,[[2,4,10],[2,5,10],[4,5,10],[2,4,5],[3,4,10]]),[a,b,c]=dims,areas=[a*b,a*c,b*c],W=pick(r,[40,80,120,200]);
  const faces=[['A',`${a} cm × ${b} cm`,areas[0]],['B',`${a} cm × ${c} cm`,areas[1]],['C',`${b} cm × ${c} cm`,areas[2]]];
  if(v===0)return numeric(`A brick weighs ${W} N and measures ${a} cm × ${b} cm × ${c} cm. It can rest on any face. What is the greatest pressure it can exert on the floor, in N/cm²?`,round(W/areas[0],3),{unit:'N/cm²',units:P_UNITS,tol:0.01,method:'Greatest pressure comes from the smallest area: pressure = weight ÷ smallest face area.',steps:[`Smallest face = ${a} × ${b} = ${areas[0]} cm².`,`Pressure = ${W} ÷ ${areas[0]} = ${round(W/areas[0],3)} N/cm².`]});
  if(v===1)return pair(`A brick weighing ${W} N can rest on face A, B or C (see table). On which face does it exert the greatest pressure on the floor?`,'Standing on face A',['Standing on face B','Standing on face C','Same on every face'],'The same weight on the smallest area gives the largest pressure.',['The largest face presses on most floor, so it gives most pressure.','The weight changes with the face used, so the pressure changes.'],['The weight is the same whichever face is down.',`Smallest area: face A (${areas[0]} cm²).`],table(['Face','Size','Area / cm²'],faces.map(f=>[f[0],f[1],f[2]]),'Faces of the brick'));
  const w=pick(r,[360,420,480,540,600]),shoe=pick(r,[120,150,200]),one=r.int(0,1),p=round(w/(one?shoe:2*shoe),3);return numeric(`A pupil weighs ${w} N. Each of her shoes touches the floor over ${shoe} cm². What pressure does she exert on the floor standing on ${one?'one foot':'both feet'}, in N/cm²?`,p,{unit:'N/cm²',units:P_UNITS,tol:0.01,method:'Pressure = weight ÷ total area in contact with the floor.',steps:[`Area = ${one?shoe:2*shoe} cm².`,`Pressure = ${w} ÷ ${one?shoe:2*shoe} = ${p} N/cm².`]});},
 r=>{const v=r.int(0,2);
  if(v===0){const letters=['A','B','C'],order=others(r,letters,null,3),depth={[order[0]]:'near the top',[order[1]]:'halfway down',[order[2]]:'near the bottom'},deep=order[2],opts=[`From hole ${deep}, near the bottom`,`From hole ${order[1]}, halfway down`,`From hole ${order[0]}, near the top`,'All three jets are equally fast'];
   return pair('A tall can full of water has three small holes at different heights (see diagram). From which hole does water spurt out fastest?',opts[0],opts.slice(1),'Liquid pressure increases with depth, so the deepest hole is pushed hardest.',['Water near the top is closest to the air, so it spurts out fastest.','Pressure is the same everywhere in a liquid, so the jets are equal.'],['More water lies above a deeper hole.','Greater depth gives greater pressure and a faster jet.'],{type:'tank',holes:letters.map(l=>[l,order.indexOf(l)])});}
  if(v===1)return written('Explain how drinking through a straw makes the drink rise up the straw. Use the idea of air pressure.',{key:'straw-air-pressure',ideas:[
    idea('Sucking removes air, lowering the pressure inside the straw',['suck','remove','take out','draw','lower','reduc','less','decreas'],['air','pressure']),
    idea('Air pressure on the surface of the drink outside is greater',['air pressure','atmospher','air outside','outside air','air above','air on','air around','air push','pressure outside'],['greater','higher','more','bigger','larger','strong','push','harder','press']),
    idea('This pushes the drink up the straw',['push','force','forc','press'],['drink','liquid','juice','water','up$'])],
   model:'When I suck, I remove some air from the straw, so the air pressure inside the straw becomes lower. The air pressure on the surface of the drink outside the straw is now greater. This greater air pressure pushes the drink up the straw.',steps:['Sucking lowers the air pressure inside the straw.','Outside air pressure on the drink is now greater.','The difference pushes the drink up.']});
  return written('Explain why a dam is built much thicker at the bottom than at the top.',{key:'dam-depth',ideas:[
    idea('Water pressure increases with depth',['pressure','push','force'],['deep','depth','bottom','lower','down','more water above','greater','increas','higher','more']),
    idea('So the bottom must be strong enough to withstand the greater pressure',['thick','strong','withstand','resist','hold','support','not break','collapse','burst','crack'])],
   model:'Water pressure increases with depth, so the water presses hardest on the bottom of the dam. The bottom is built thicker so that it is strong enough to withstand this greater pressure without breaking.',steps:['Deeper water has more water above it.','So pressure is greatest at the bottom.','A thicker base can withstand the greater force.']});},
 r=>{const v=r.int(0,2);
  if(v===0){const k=pick(r,[10]),d=pick(r,[1.5,2.5,3.5,4,4.5,6]);return numeric(`In a simple model, water pressure rises by ${k} kPa for every 1 m of depth (ignore the air above). The table shows the start of the pattern. What is the water pressure at a depth of ${d} m, in kPa?`,round(k*d),{unit:'kPa',units:['kPa','kilopascals'],tol:0.01,method:'Pressure increases in proportion to depth in this model.',steps:[`Pressure = ${k} kPa per m × ${d} m.`,`= ${round(k*d)} kPa.`],figure:table(['Depth / m','Water pressure / kPa'],[[0,0],[1,k],[2,2*k],[3,3*k]],'Simple model of water pressure')});}
  if(v===1){const bag=r.int(0,1);
   if(bag)return pair('A sealed bag of crisps bought at sea level puffs up at the top of a high mountain. Why?','Air pressure outside is lower, so air inside pushes the bag out.',['The air inside the bag gets heavier high up and pushes harder.','The cold mountain air makes the crisps swell up inside the bag.','The air outside pushes harder up high and squeezes the bag.'],'The same air inside now pushes against less air pressure outside.',['Air pressure is greater high up, because you are nearer the sky.','Air inside a sealed bag gains extra particles as you climb.'],['Air pressure decreases with height above sea level.','The trapped air keeps pushing outwards; less push from outside lets the bag expand.']);
   return pair('A rubber suction cup is pressed flat onto a smooth tile and stays stuck. Why?','Air pressure outside is greater than under the cup.',['The rubber is sticky like glue and holds onto the tile.','The cup sucks the tile towards it with a pulling force.','Air trapped under the cup pushes it hard against the tile.'],'Pressing pushes air out, so less air under the cup pushes back.',['Suction is a pulling force made by the rubber itself.','More air under the cup holds it on more tightly.'],['Pressing the cup squeezes air out from under it.','The greater air pressure outside presses the cup onto the tile.']);}
  return statements('Evaluate these statements about pressure.',[['A diver feels greater water pressure deeper in the sea.',true],['A sharp pin and a blunt pin pushed equally hard give the same pressure.',false],['Air pressure pushes on surfaces from every direction.',true]],'Pressure depends on depth in a liquid and on force ÷ area.',['Pressure depends only on the force, never on the area.','Air presses only downwards, never sideways or upwards.'],['Pressure = force ÷ area: the sharp pin has a smaller area.','Liquid pressure rises with depth; air pressure acts in all directions.']);}
];

/* ---------------- Sound and pendulums ---------------- */
const SPEED=340;
const HZ=['Hz','hertz','vibrations per second','/s','per second'];
S['sx-waves']=[
 r=>{const v=r.int(0,2);
  if(v===0)return pair('A ringing alarm clock sits inside a glass jar. Air is slowly pumped out of the jar. What happens to the sound you hear?','It becomes fainter, though the bell is still moving.',['It becomes louder as the air is removed from the jar.','It becomes higher in pitch but stays just as loud.','It stops at once, because the bell stops moving.'],'Sound needs particles to pass on vibrations; light does not.',['Air soaks up sound, so less air lets more sound escape.','The bell stops vibrating once the air around it is gone.'],['Sound is passed on by particles of a medium.','Light can cross a vacuum, so you still see the bell.']);
  if(v===1){const ch=pick(r,['shortened','tightened','lengthened','loosened','plucked harder']),up=ch==='shortened'||ch==='tightened',loud=ch==='plucked harder';
   const claim=loud?'The note becomes louder only.':up?'The pitch becomes higher.':'The pitch becomes lower.';
   const reason={shortened:'A shorter string vibrates faster, so the frequency rises.',tightened:'A tighter string vibrates faster, so the frequency rises.',lengthened:'A longer string vibrates more slowly, so the frequency falls.',loosened:'A looser string vibrates more slowly, so the frequency falls.','plucked harder':'A harder pluck makes bigger vibrations, not faster ones.'}[ch];
   const wr=loud?['Plucking harder makes the string vibrate faster and higher.','Plucking harder makes the string vibrate more slowly.']:up?['A longer, looser string vibrates faster, giving a higher note.','Tightness changes only the loudness, not how fast it vibrates.']:['A longer, looser string vibrates faster, giving a higher note.','Length changes only the loudness, not how fast it vibrates.'];
   return pair(`A guitar string is ${ch}, then plucked in the same way as before. What happens to the note?`,claim,['The pitch becomes higher.','The pitch becomes lower.','The note becomes louder only.','Nothing about the note changes.'].filter(x=>x!==claim),reason,wr,['Pitch depends on frequency (vibrations per second).','Loudness depends on amplitude (size of the vibration).']);}
  const f=pick(r,[220,256,330,440,512]),t=pick(r,[2,3,4,5]);return numeric(`A tuning fork vibrates ${f*t} times in ${t} seconds. What is its frequency, in hertz (Hz)?`,f,{unit:'Hz',units:HZ,method:'Frequency = number of vibrations ÷ time in seconds.',steps:[`Frequency = ${f*t} ÷ ${t}.`,`= ${f} Hz.`]});},
 r=>{const v=r.int(0,2);
  if(v===0){const t=pick(r,[0.4,0.5,0.6,0.8,1,1.2,1.5,2]),d=round(SPEED*t/2);return numeric(`A pupil claps once in front of a cliff and hears the echo ${t} s later. Sound travels at ${SPEED} m/s in air. How far away is the cliff, in metres?`,d,{unit:'m',units:[['m',1],['metres',1],['km',1000]],tol:0.01,method:'The sound travels to the cliff and back, so distance = speed × time ÷ 2.',steps:[`Total path = ${SPEED} × ${t} = ${round(SPEED*t)} m.`,`Cliff distance = ${round(SPEED*t)} ÷ 2 = ${d} m.`]});}
  if(v===1){const t=pick(r,[2,3,4,5,6]);return numeric(`You see a flash of lightning and hear the thunder ${t} s later. Light reaches you almost instantly; sound travels at ${SPEED} m/s. How far away was the lightning, in metres?`,SPEED*t,{unit:'m',units:[['m',1],['metres',1],['km',1000]],tol:0.01,method:'The sound travels one way only, so distance = speed × time.',steps:[`Distance = ${SPEED} × ${t}.`,`= ${SPEED*t} m. (No halving: this is not an echo.)`]});}
  const T=pick(r,[120,126,134,142,150,160,172]),a=T/10,trials=[a+0.2,a,a-0.2].map(x=>round(x,1)),period=round(a/10,3);return numeric('A pupil times 10 complete swings of a pendulum three times. What is the mean period (time for one swing), in seconds?',period,{unit:'s',units:['s','seconds','sec'],tol:0.006,method:'Mean of the 10-swing times ÷ 10.',steps:[`Mean time for 10 swings = (${trials.join(' + ')}) ÷ 3 = ${round(a,2)} s.`,`Period = ${round(a,2)} ÷ 10 = ${period} s.`],figure:table(['Trial','Time for 10 swings / s'],trials.map((x,i)=>[i+1,x.toFixed(1)]),'Synthetic pendulum timings')});},
 r=>{const v=r.int(0,2);
  if(v===0){const noise=r.int(0,1)?0.1:-0.1;return pair('The table shows pendulum timings. Which conclusion do the data support?','Length changes the period; bob mass makes little difference.',['Mass changes the period; length makes little difference.','Both a longer string and a heavier bob slow the swing.','Neither length nor mass has any effect on the period.'],'Only the rows where length changed show a clear change in time.',['Heavier things fall faster, so a heavier bob must swing faster.','A longer string swings faster because the bob travels further.'],['Compare rows where only mass changes: times stay about 14.2 s.','Compare rows where only length changes: longer strings take longer.'],table(['Length / cm','Bob mass / g','Time for 10 swings / s'],[[50,20,(14.2).toFixed(1)],[50,50,(14.2+noise).toFixed(1)],[50,100,(14.2).toFixed(1)],[25,50,(10.0).toFixed(1)],[100,50,(20.1).toFixed(1)]],'Synthetic data (small swings)'));}
  if(v===1)return written('Mei times 10 swings of a 50 cm pendulum, using bobs of 20 g, 50 g and 100 g. Each time is about 14.2 s. What does this show about the period of a pendulum, and why was it a fair test of the bob’s mass?',{key:'pendulum-mass',ideas:[
    idea('Claim: the mass of the bob does not affect the period',['mass','heav','weight','bob','gram'],['not','no$','same','unchanged','independ','little','hardly','constant','equal','similar','no effect','no difference','matter']),
    idea('Evidence: the times stayed about the same (14.2 s)',['time','period','swing','14','took'],['same','similar','about','constant','equal','unchanged','not change','hardly','close']),
    idea('Fair test: only the mass changed; the length was kept the same',['length','string','50 cm','long'],SAME.concat(['not change','stay','stayed','remain']))],
   model:'The mass of the bob does not affect the period of the pendulum. When the mass changed from 20 g to 100 g, the time for 10 swings stayed about the same, at 14.2 s. It was a fair test because only the mass was changed; the length of the string was kept the same at 50 cm.',steps:['State the effect (none) of mass on the period.','Quote the evidence: the times were all about 14.2 s.','Explain fairness: length (and swing size) kept the same.']});
  return roles('Ravi changes the length of a pendulum’s string to 20 cm, 40 cm, 60 cm and 80 cm. Each time he uses the same 50 g bob, starts from the same small angle and times 10 complete swings. For each variable, choose whether it is changed, measured or kept the same.',[['Length of the string',0],['Time for 10 swings',1],['Mass of the bob',2],['Starting angle',2],['Number of swings timed',2]],{reason:'Only the string length is changed on purpose; the time is measured; other factors are kept the same.',steps:['The changed variable is what Ravi sets differently each time: length.','The measured variable is the time.','Mass, starting angle and number of swings are kept the same.']});},
 r=>{const v=r.int(0,2);
  if(v===0){const n=pick(r,[10,20,30]),p=pick(r,[0.8,1.2,1.5,1.6,2]),t=round(n*p);return numeric(`A pendulum makes ${n} complete swings in ${t} s. What is its period, in seconds?`,p,{unit:'s',units:['s','seconds','sec'],tol:0.001,method:'Period = total time ÷ number of complete swings.',steps:[`Period = ${t} ÷ ${n}.`,`= ${p} s.`]});}
  if(v===1)return statements('A guitar string is plucked gently, then harder, without changing its length or tension. Evaluate these statements.',[['The harder pluck gives a louder sound.',true],['The harder pluck gives a higher pitch.',false],['The harder pluck makes vibrations with a larger amplitude.',true]],'A harder pluck makes bigger vibrations, not faster ones.',['A harder pluck makes the string vibrate faster and higher.','Loudness and pitch always change together for a string.'],['Amplitude (size of vibration) sets loudness.','Frequency (set by length, tension and thickness) sets pitch.']);
  const t=pick(r,[0.2,0.4,0.6,0.8,1.2,2]),w=1500,d=round(w*t/2);return numeric(`A ship sends a sound pulse straight down. The echo from the sea bed returns ${t} s later. Sound travels at ${w} m/s in sea water. How deep is the sea there, in metres?`,d,{unit:'m',units:[['m',1],['metres',1],['km',1000]],tol:0.01,method:'Depth = speed × time ÷ 2, since the pulse goes down and back up.',steps:[`Total path = ${w} × ${t} = ${round(w*t)} m.`,`Depth = ${round(w*t)} ÷ 2 = ${d} m.`]});}
];

/* ---------------- Chemical change, acids and alkalis ---------------- */
const CHANGES=[['burning a sheet of paper',1,'Burning makes new substances, such as ash and carbon dioxide.'],['melting a bar of chocolate',0,'Melted chocolate is still chocolate; only its state changed.'],['dissolving sugar in water',0,'The sugar is still sugar, spread out through the water.'],['frying an egg',1,'Heating forms new substances, and the egg cannot change back.'],['an iron nail rusting',1,'Rust is a new substance made from iron, water and oxygen.'],['boiling water in a kettle',0,'The bubbles are steam, which is still the same water.'],['baking soda fizzing in vinegar',1,'A new gas, carbon dioxide, is made in the reaction.'],['cutting a plank of wood',0,'The pieces are still wood; only their size and shape changed.']];
const IND={
 litmus:{acid:['Blue litmus turns red; red litmus stays red.','Only an acid turns blue litmus paper red.'],alkali:['Red litmus turns blue; blue litmus stays blue.','Only an alkali turns red litmus paper blue.'],neutral:['Red litmus stays red; blue litmus stays blue.','Neither litmus paper changed, so it is neutral.']},
 cabbage:{acid:['Red cabbage juice turns pink.','Red cabbage juice turns pink or red in acids.'],alkali:['Red cabbage juice turns green.','Red cabbage juice turns green or yellow in alkalis.'],neutral:['Red cabbage juice stays purple.','Red cabbage juice stays purple in neutral liquids.']}
};
const IND_WRONG={acid:['Blue litmus turns red only when a liquid is an alkali.','Red cabbage juice turns pink when a liquid is alkaline.'],alkali:['Red litmus turns blue only when a liquid is an acid.','Red cabbage juice turns green when a liquid is acidic.'],neutral:['A neutral liquid turns every indicator a bright red.','If nothing changes, the liquid must be a strong alkali.']};
S['sx-chem']=[
 r=>{const v=r.int(0,1);
  if(v===0){const c=pick(r,CHANGES),opts=['A chemical change, as a new substance forms','A physical change, as no new substance forms','A chemical change, as its shape has changed','A physical change, as it can be reversed'],claim=c[1]?opts[0]:opts[1];
   return pair(`Which statement best describes ${c[0]}?`,claim,opts.filter(x=>x!==claim),c[2],['Any change that gives off bubbles must be a chemical change.','A change in shape or state always makes a new substance.'],['Ask: has a new substance been made?','Bubbles, colour or shape changes are clues, not proof on their own.']);}
  const ind=pick(r,['litmus','cabbage']),type=pick(r,['acid','alkali','neutral']),claim={acid:'It is an acidic liquid.',alkali:'It is an alkaline liquid.',neutral:'It is a neutral liquid.'}[type];
  return pair(`A colourless liquid is tested with ${ind==='litmus'?'red and blue litmus paper':'red cabbage juice indicator'}. Result: ${IND[ind][type][0]} What does this show?`,claim,['It is an acidic liquid.','It is an alkaline liquid.','It is a neutral liquid.','It could be any of these.'].filter(x=>x!==claim),IND[ind][type][1],IND_WRONG[type],['Recall the indicator’s colour in acid, neutral and alkali.','Match the observed colour.']);},
 r=>{const v=r.int(0,2);
  if(v===0){const fastest=r.int(0,1),rows=[['A','Dry air (drying agent added)','none'],['B','Boiled water with a layer of oil','none'],['C','Tap water, open to air','some'],['D','Salt water, open to air','?']];
   if(fastest)return pair('Four identical iron nails are set up as shown and left for a week. In which tube would rusting be fastest?','Tube D, in salt water open to air',['Tube C, in tap water open to air','Tube B, in boiled water under oil','Tube A, in dry air with a drying agent'],'Water and air are both present, and salt speeds up rusting.',['Water alone makes iron rust, so the wettest nail rusts fastest.','Air alone makes iron rust, so dry air gives the fastest rust.'],['Rusting needs both water and oxygen (air).','Salt water speeds up rusting.'],table(['Tube','Conditions'],rows.map(x=>[x[0],x[1]]),'Rusting set-up'));
   return pair('Four identical iron nails are set up as shown and left for a week. Which nails would rust?','Only the nails in C and D',['All four nails, A to D','Only the nails in B, C and D','Only the nails in A and B'],'Rust needs both water and oxygen; only C and D have both.',['Water alone makes iron rust, so every wet nail will rust.','Air alone makes iron rust, so every nail in air will rust.'],['A has air but no water; B has water but no air.','C and D have both water and air.'],table(['Tube','Conditions'],rows.map(x=>[x[0],x[1]]),'Rusting set-up'));}
  if(v===1)return pair('Vinegar is added to crushed eggshell. The gas given off is bubbled through limewater, which turns milky. What does this show?','The gas is carbon dioxide, a new substance.',['The gas is oxygen, given off by the eggshell.','The gas is steam, from the vinegar boiling.','The gas is air that was trapped in the shell.'],'Limewater turns milky with carbon dioxide.',['Bubbles in any liquid always show oxygen is there.','Limewater turns milky when any gas bubbles through.'],['Eggshell contains a carbonate; acids react with carbonates.','Limewater turning milky is the test for carbon dioxide.']);
  const per=pick(r,[2,3,4,5,6]),V=pick(r,[15,20,25,30,35]),ans=round(per*V/10);return numeric(`Exactly ${per} mL of an acid neutralises 10 mL of an alkali solution. How much of the same acid is needed to neutralise ${V} mL of the same alkali, in mL?`,ans,{unit:'mL',units:[['mL',1],['ml',1],['cm³',1],['cm3',1],['L',1000]],tol:0.01,method:'The acid needed is proportional to the volume of alkali.',steps:[`Acid per 1 mL alkali = ${per} ÷ 10 = ${per/10} mL.`,`For ${V} mL: ${per/10} × ${V} = ${ans} mL.`]});},
 r=>{const v=r.int(0,2);
  if(v===0)return written('Liya adds vinegar to crushed eggshell. It fizzes, and when the gas is bubbled through limewater, the limewater turns milky. Is this a chemical change? Explain using the evidence.',{key:'carbonate-gas',ideas:[
    idea('Claim: it is a chemical change',['chemical']),
    idea('Evidence: limewater turning milky shows carbon dioxide',['carbon dioxide','co2','carbondioxide']),
    idea('Reason: a new substance (gas) was made',['new'],['substance','gas','product','material','chemical','thing'])],
   contradictions:[idea('Says it is not a chemical change',['not a chemical','not chemical','no chemical','is a physical','was a physical','physical change'])],
   model:'Yes, it is a chemical change. The fizzing shows a gas was given off, and the limewater turned milky, which shows the gas is carbon dioxide. Carbon dioxide is a new substance that was not there before, so a chemical change took place.',steps:['State the claim: a chemical change.','Use the limewater result: carbon dioxide.','Explain: a new substance was formed.']});
  if(v===1)return roles('Tan wants to find out whether salt affects how quickly iron nails rust. She puts identical nails in 100 mL of water containing 0 g, 5 g, 10 g or 15 g of salt, leaves them open to the air for a week, and weighs the rust that forms. For each variable, choose whether it is changed, measured or kept the same.',[['Amount of salt in the water',0],['Mass of rust formed',1],['Type and size of nail',2],['Volume of water',2],['Time left to rust',2]],{reason:'Only the amount of salt is changed; the rust is measured; everything else is kept the same.',steps:['The changed variable is the salt.','The measured variable is the mass of rust.','Nail type, water volume and time are kept the same.']});
  return written('Three iron nails were left for a week. Nail A was in dry air, nail B in boiled water under a layer of oil, and nail C in water open to the air. Only nail C rusted. What do the results show about the conditions needed for rusting? Use the results in your answer.',{key:'rust-conditions',ideas:[
    idea('Claim: rusting needs both water and air (oxygen)',['water','moist','wet','damp'],['air','oxygen'],['need','requir','both','must','necessary','only','when','present','and']),
    idea('Evidence: nail C, with both water and air, rusted',['c$','tube c','nail c','third'],['rust']),
    idea('Evidence: nails with only air or only water did not rust',['a$','b$','tube a','tube b','dry','no water','without water','no air','without air','only water','only air','boiled','oil'],['not rust','no rust','did not','not get rust','stay','no change','remain','shiny','not','neither','none'])],
   model:'Rusting needs both water and air (oxygen). Nail C had both water and air, and it rusted. Nail A had air but no water, and nail B had water but no air, and neither of them rusted.',steps:['Compare which conditions each nail had.','Only the nail with both water and air rusted.','So both are needed.'],figure:table(['Nail','Water?','Air?','Rusted?'],[['A','no','yes','no'],['B','yes','no','no'],['C','yes','yes','yes']],'Results after one week (synthetic)')});},
 r=>{const v=r.int(0,2);
  if(v===0){const before=round(pick(r,[180,200,220,250])+r.int(0,9)/10,1),gas=round(pick(r,[1.2,1.6,2.2,2.6,3.4]),1),after=round(before-gas,1);return numeric(`Vinegar and baking soda react in an open flask on a balance. The total mass falls from ${before.toFixed(1)} g to ${after.toFixed(1)} g. What mass of gas escaped, in grams?`,gas,{unit:'g',units:[['g',1],['grams',1],['kg',1000]],tol:0.01,method:'The mass lost from the open flask equals the mass of gas that escaped.',steps:[`Gas = ${before.toFixed(1)} − ${after.toFixed(1)}.`,`= ${gas} g. In a sealed flask, the mass would not change.`]});}
  if(v===1)return statements('Evaluate these statements about acids and alkalis.',[['Adding an alkali to an acid can make the mixture neutral.',true],['Universal indicator shows pH 3 for a strong alkali.',false],['Vinegar turns blue litmus paper red.',true]],'Acid and alkali cancel out; a low pH means acidic.',['A low pH number means a liquid is strongly alkaline.','Mixing an acid with an alkali always makes a stronger acid.'],['Neutralisation: acid + alkali → salt + water.','pH below 7 is acidic; above 7 is alkaline.']);
  return pair('Water boiling in a pan gives off bubbles. Baking soda in vinegar also gives off bubbles. Which observation shows a chemical change?','The bubbles from baking soda in vinegar',['The bubbles from the boiling water','Both, since both give off bubbles','Neither, since bubbles are not a clue'],'Its gas is a new substance; steam from boiling is still water.',['Any change that gives off bubbles must be a chemical change.','Bubbles always contain air, so they never show a new substance.'],['Ask what the bubbles are made of.','Steam is water; carbon dioxide is new.']);}
];

/* ---------------- Life cycles, reproduction and the environment ---------------- */
const ORGS=[['butterfly',4],['mosquito',4],['beetle',4],['housefly',4],['cockroach',3],['grasshopper',3]];
const FRUITS={
 wing:{feature:'a thin, flat wing-like part attached to the seed',agent:'It is carried by the wind.',reason:'Its wing-like part catches the air, so it spins slowly away.'},
 hairs:{feature:'a tuft of long, fine, feathery hairs',agent:'It is carried by the wind.',reason:'Fine hairs catch the wind and keep it in the air for longer.'},
 fibrous:{feature:'a thick, fibrous husk with air spaces and a waterproof skin',agent:'It floats away on water.',reason:'Its fibrous husk traps air, so it floats for a long time.'},
 hooks:{feature:'many tiny hooks all over its surface',agent:'It is carried by animals.',reason:'Hooks catch on fur, so passing animals carry it far away.'},
 juicy:{feature:'soft, sweet, brightly coloured flesh around small seeds',agent:'It is carried by animals.',reason:'Animals eat the juicy flesh and pass out the seeds elsewhere.'},
 pod:{feature:'a long pod that dries, twists and splits open',agent:'Its pod splits and flings it.',reason:'The drying pod twists open and flings the seeds outwards.'}
};
const AGENTS=['It is carried by the wind.','It floats away on water.','It is carried by animals.','Its pod splits and flings it.'];
S['sx-life']=[
 r=>{const v=r.int(0,2);
  if(v===0){const o=pick(r,ORGS),four=o[1]===4,claim=four?'Egg → larva → pupa → adult':'Egg → nymph → adult';
   return pair(`Which sequence describes the life cycle of a ${o[0]}?`,claim,['Egg → larva → pupa → adult','Egg → nymph → adult','Egg → pupa → larva → adult','Egg → adult → nymph'].filter(x=>x!==claim),four?'Its young (larva) look very different from the adult and pupate.':'Its young nymph looks like a small adult without full wings.',four?['All insects hatch looking like small copies of the adult.','A pupa is the stage that comes straight after the egg.']:['Every insect passes through a pupa stage before adulthood.','A nymph is just a pupa with another name.'],['Recall whether the young look like the adult.',four?'A four-stage cycle has a larva and a pupa.':'A three-stage cycle has a nymph and no pupa.'],{type:'cycle',labels:four?['Egg','Larva','Pupa','Adult']:['Egg','Nymph','Adult']});}
  if(v===1){const key=pick(r,Object.keys(FRUITS)),f=FRUITS[key],wrongReasons=others(r,Object.keys(FRUITS).filter(k=>FRUITS[k].agent!==f.agent),null,2).map(k=>FRUITS[k].reason);
   return pair(`A fruit has ${f.feature}. How is it most likely dispersed?`,f.agent,AGENTS.filter(x=>x!==f.agent),f.reason,wrongReasons,['Link the feature to what it could catch, float on or attract.','Dispersal carries seeds away from the parent plant.'],{type:'fruit',kind:key});}
  return statements('Evaluate these statements about reproduction in flowering plants.',[['Pollination is the transfer of pollen from the anther to the stigma.',true],['Fertilisation happens before pollination.',false],['After fertilisation, the ovule develops into a seed.',true]],'Pollen reaches the stigma first; fertilisation then happens in the ovule.',['Fertilisation and pollination are two names for the same step.','The ovary becomes the seed and the ovule becomes the fruit.'],['Order: pollination → fertilisation → seed and fruit form.','Ovule → seed; ovary → fruit.']);},
 r=>{const v=r.int(0,2);
  if(v===0){const o=pick(r,[['butterfly',[4,14,10]],['mosquito',[2,7,2]],['beetle',[7,21,9]],['housefly',[1,5,5]]]),stages=o[1].map(x=>x+r.int(0,2)),total=stages.reduce((a,b)=>a+b,0);return numeric(`The table shows how long a ${o[0]} spends in each stage of its life cycle (synthetic data). How many days pass from the egg being laid until the adult appears?`,total,{unit:'days',units:['days','day','d'],method:'Add the time spent as egg, larva and pupa.',steps:[`${stages.join(' + ')} = ${total} days.`,'The adult stage starts after the pupa stage ends.'],figure:table(['Stage','Time / days'],[['Egg',stages[0]],['Larva',stages[1]],['Pupa',stages[2]]],'Synthetic life-cycle timings')});}
  if(v===1){const a=[3,r.int(25,40),0],b=[r.int(2,4),r.int(5,8),r.int(6,10)],nymph=a[1],larvaPupa=b[1]+b[2],claimA=nymph>larvaPupa;
   const claim=claimA?'Insect P has a longer young stage.':'Insect Q has a longer young stage.';
   return pair('Insect P has a three-stage life cycle and insect Q a four-stage life cycle (see table). Which spends longer between hatching and becoming an adult?',claim,[claimA?'Insect Q has a longer young stage.':'Insect P has a longer young stage.','Both have exactly the same young stage.','It cannot be told from life-cycle data.'],`P’s nymph stage is ${nymph} days; Q’s larva plus pupa is ${larvaPupa} days.`,['An insect with more stages always takes longer to grow up.','Only the larva counts, because a pupa is not a young stage.'],['P: young stage = nymph.',`Q: young stages = larva + pupa = ${b[1]} + ${b[2]}.`],table(['Insect','Egg / days','Nymph / days','Larva / days','Pupa / days'],[['P',a[0],nymph,'—','—'],['Q',b[0],'—',b[1],b[2]]],'Synthetic life-cycle timings'));}
  const N=pick(r,[20,25,40,50]),pct=pick(r,[60,70,80,90]),n=N*pct/100;return numeric(`A pupil plants ${N} seeds and ${n} of them germinate. What percentage of the seeds germinated?`,pct,{unit:'%',units:['%','percent','per cent'],method:'Percentage = number germinated ÷ number planted × 100%.',steps:[`${n} ÷ ${N} × 100%.`,`= ${pct}%.`]});},
 r=>{const v=r.int(0,2);
  if(v===0){const hooks=r.int(0,1);
   if(hooks)return written('The fruit of plant Y is small and covered in tiny hooks. How is it most likely dispersed, and how does this help plant Y?',{key:'dispersal-hooks',ideas:[
     idea('It is dispersed by animals',['animal','fur','dog','sheep','monkey','squirrel','deer','clothes','people','human','bird','goat','cat$','cats$']),
     idea('The hooks catch on fur, so it is carried away',['hook','spike','spine','barb','prick','bristle'],['catch','stick','attach','cling','hold','grip','caught','hook on','hook onto','carri']),
     COMPETE],
    model:'It is dispersed by animals. Its hooks catch on the fur of passing animals, which carry it far from the parent plant before it drops off. The seedlings then grow away from the parent plant, so there is less competition for light, water and space.',steps:['Name the agent: animals.','Link the feature (hooks) to how it is carried.','Explain the benefit: less competition with the parent.'],figure:{type:'fruit',kind:'hooks'}});
   return written('The fruit of plant X is very light and has a tuft of long, fine hairs. How is it most likely dispersed, and how does this help plant X?',{key:'dispersal-wind',ideas:[
     idea('It is dispersed by the wind',['wind','breez','blown','blow','air current']),
     idea('Being light with hairs, it stays in the air and is carried far',['light','hair','fluff','feather','parachute'],['carri','float','stay','far','away','drift','glide','longer','travel','blown','spread','air']),
     COMPETE],
    model:'It is dispersed by the wind. Because it is light and its fine hairs catch the air, it stays in the air for longer and is carried far from the parent plant. The seedlings then grow away from the parent, so there is less competition for light, water and space.',steps:['Name the agent: wind.','Link the features (light, hairs) to staying in the air.','Explain the benefit: less competition with the parent.'],figure:{type:'fruit',kind:'hairs'}});}
  if(v===1){const c=pick(r,[
   {text:'A desert plant has leaves that are tiny spines and a thick, fleshy stem. Which explanation is best?',claim:'Spines lose less water; the thick stem stores water.',wrong:['Spines catch rainwater; the thick stem stores only food.','Spines make food quickly; the thick stem stores heat.','Spines attract insects; the thick stem grows faster.'],reason:'Less leaf surface means less water is lost by evaporation.',wr:['Spines are leaves that make most of the plant’s food.','Desert plants need little water, so storing it is unhelpful.']},
   {text:'A polar bear has thick fur and a thick layer of fat under its skin. Which explanation is best?',claim:'Fur and fat reduce heat loss in the freezing cold.',wrong:['Fur and fat make the bear heavier so it can swim deeper.','Fur and fat keep the bear cool under the strong sun.','Fur and fat help the bear hide from its predators.'],reason:'Fur and fat are poor conductors, so less heat escapes.',wr:['Fur and fat make heat inside the bear’s body.','Thick fur lets more heat pass out when it is cold.']},
   {text:'A water lily has broad, flat leaves with air spaces that float on the pond surface. Which explanation is best?',claim:'Floating leaves stay in sunlight for photosynthesis.',wrong:['Floating leaves stop fish from eating the roots.','Floating leaves soak up water through their top surface.','Floating leaves keep the pond water warm at night.'],reason:'Air spaces help the leaves float where light is strongest.',wr:['Leaves underwater get more light than leaves at the top.','Air spaces store food for the lily during the night.']}]);
   return pair(c.text,c.claim,c.wrong,c.reason,c.wr,['Name the problem the environment poses.','Link each feature to solving it.']);}
  return written('A large area of forest is cut down to build a road. Describe two ways this could affect living things or the environment in the area, and explain each.',{key:'deforestation',ideas:[
    idea('Animals lose their habitat: food and shelter',['habitat','home','shelter','food','nest','live','place to live'],['lose','lost','loss','destroy','no$','less','fewer','gone','remov','take away','without','not have','no longer']),
    idea('A second effect: less carbon dioxide taken in, soil erosion, floods or pollution',['carbon dioxide','co2','oxygen','soil','erosion','erode','flood','landslide','pollut','temperature','hotter','warmer','climate','global warm','rain','greenhouse','smoke','noise'])],
   model:'Animals that live in the forest lose their habitat, so they lose their food and shelter and may die or have to move away. Also, there are fewer trees to take in carbon dioxide, so more carbon dioxide stays in the air, which can make the Earth warmer. Without tree roots, the soil can also be washed away more easily.',steps:['Effect 1: habitat (food and shelter) is lost.','Effect 2: less carbon dioxide absorbed, or soil erosion, flooding or pollution.','Explain each effect, not just name it.']});},
 r=>{const v=r.int(0,2);
  if(v===0){const set=r.int(0,1);
   if(set)return statements('Evaluate these statements about human reproduction.',[['Sperm are made in the testes.',true],['Eggs are released from the ovaries.',true],['Fertilisation takes place in the stomach.',false]],'Each reproductive organ has its own job; the stomach is digestive.',['Fertilisation happens wherever food is digested in the body.','The ovaries make sperm, and the testes release eggs.'],['Male: testes make sperm. Female: ovaries release eggs.','Fertilisation happens in the female reproductive system.']);
   return statements('Evaluate these statements about human reproduction.',[['Fertilisation is the joining of a sperm and an egg.',true],['A baby inherits characteristics only from its mother.',false],['A fertilised egg develops into a baby in the womb (uterus).',true]],'A sperm and an egg join, so both parents pass on traits.',['The baby grows only from the egg, so only the mother passes on traits.','Fertilisation is the birth of the baby after it grows in the womb.'],['Fertilisation joins a male and a female reproductive cell.','The baby develops in the womb and inherits from both parents.']);}
  if(v===1){const total=pick(r,[800,1200,1500,2000,2400]),pct=pick(r,[10,15,20,25,30,40]),cut=total*pct/100;return numeric(`A forest covered ${total} hectares. Then ${cut} hectares were cleared for farmland. What percentage of the forest was cleared?`,pct,{unit:'%',units:['%','percent','per cent'],method:'Percentage cleared = area cleared ÷ original area × 100%.',steps:[`${cut} ÷ ${total} × 100%.`,`= ${pct}%.`]});}
  const insect=r.int(0,1);
  if(insect)return pair('A flower is large and brightly coloured, has a sweet scent and produces nectar. How is it most likely pollinated?','By insects that visit it for nectar',['By the wind blowing its pollen','By water carrying its pollen','By the flower pollinating at night'],'Colour, scent and nectar attract insects that carry pollen.',['Bright petals help the wind pick up and carry pollen.','Scent spreads pollen through the air without any animal.'],['Look for features that attract animals.','Insects carry pollen from flower to flower.']);
  return pair('A flower is small and dull with no scent or nectar. Its stigmas are feathery and hang outside, and it makes lots of light pollen. How is it most likely pollinated?','By the wind blowing its pollen',['By insects that visit it for nectar','By birds attracted to its colour','By water carrying its pollen'],'Feathery stigmas catch light pollen carried by the wind.',['Dull flowers attract insects better than bright ones.','Light pollen is made so that bees can carry more of it.'],['No colour, scent or nectar: it does not attract animals.','Feathery stigmas and light pollen suit wind pollination.']);}
];
return S;
};
if(typeof module!=='undefined')module.exports=root.MochiSciencePathSX;
})(typeof globalThis!=='undefined'?globalThis:this);
