/* Original generated science illustrations with exact, interactive model overlays. */
(function(root){
'use strict';
const svg=(body,label)=>`<svg viewBox="0 0 600 350" role="img" aria-label="${label}" xmlns="http://www.w3.org/2000/svg"><defs>${[['scArrow','#7742b5'],['scArrowTeal','#277e8a'],['scArrowMuted','#b2a0c4']].map(([id,color])=>`<marker id="${id}" markerUnits="userSpaceOnUse" viewBox="0 0 14 14" markerWidth="14" markerHeight="14" refX="12" refY="7" orient="auto"><path d="M2 2L12 7L2 12" fill="none" stroke="${color}" stroke-width="2.5"/></marker>`).join('')}</defs><g font-family="system-ui,sans-serif" font-size="25" fill="#352452" stroke-linecap="round" stroke-linejoin="round">${body}</g></svg>`;
const label=(x,y,t)=>`<text x="${x}" y="${y}" text-anchor="middle">${t}</text>`;
const line=(x1,y1,x2,y2,color='#7952b0',width=5)=>`<path d="M${x1} ${y1}L${x2} ${y2}" fill="none" stroke="${color}" stroke-width="${width}"/>`;
const select=(key,title,options,value)=>`<label>${title}<select data-sc-key="${key}">${options.map(([v,t])=>`<option value="${v}" ${String(value)===String(v)?'selected':''}>${t}</option>`).join('')}</select></label>`;
const range=(key,title,min,max,value,unit='')=>`<label>${title} <output id="scOut-${key}">${value}${unit}</output><input data-sc-key="${key}" data-unit="${unit}" type="range" min="${min}" max="${max}" step="1" value="${value}" aria-label="${title}"></label>`;
const toggle=(key,title,value)=>`<label class="sc-toggle"><input data-sc-key="${key}" type="checkbox" ${value?'checked':''}>${title}</label>`;
const details={
 circuits:{question:'How can two bulbs be connected so that one stays lit when the other is removed?',limit:'A simplified circuit with identical bulbs. The battery is assumed to supply each working branch in the same way. The glow illustrates brightness; it is not a measurement.',challenge:'Compare series and parallel circuits. Can one bulb stay lit when the other breaks? Change one feature at a time.'},
 shadows:{question:'What controls the size of a shadow?',limit:'A small light source, an opaque object and a screen are lined up. The diagram is not drawn to scale. The size and shape of a shadow also depend on the light source used.',challenge:'Keep the light and screen fixed. Compare two object positions, then explain the result using the rays.'},
 heat:{question:'How could you test whether a wrap slows cooling?',limit:'The cups contain equal volumes of water and are in a room at 20°C. Read the starting temperatures given for this activity. The temperatures shown are calculated for the model, not measured in a real experiment.',challenge:'Choose a time to compare the cups. Which variables have been controlled? What would you repeat in a real test?'},
 plants:{question:'How do the parts of a plant work together?',limit:'The illustration shows a bean plant. Changing the conditions helps you discuss plant functions; it does not predict growth or how long the plant will survive.',challenge:'Explore a root, stem, leaf and flower. Trace water to a leaf. Predict what darkness would change and what would continue.'},
 ecosystems:{question:'What can a food web tell us—and what can it not?',limit:'This food web shows some possible feeding relationships. Arrows show the direction of energy transfer. Other conditions can affect the number of organisms.',challenge:'Trace two energy pathways. Suppose fewer snails remain: name one possible effect and a reason it might not happen.'},
 forces:{question:'Can something keep moving when forces balance?',limit:'Extension beyond primary force effects: this cart is already moving right. An opposing force is given as acting left; do not infer the direction of friction from the wheels. The model compares forces at one moment.',challenge:'Compare the push with the opposing force. Predict whether the cart speeds up, keeps the same motion or slows down. Explain your reasoning.'},
 matter:{question:'How can the same water take different forms?',limit:'The particle picture is an extension model, not required primary terminology. The dots represent water particles and are not drawn to scale. They are not air bubbles.',challenge:'Choose a starting state and a change of state. Does the water gain or lose heat? Explain what it changes into.'},
 body:{question:'How does digested food reach other parts of the body?',limit:'The illustration shows selected organs, not their exact sizes. Use the explanation to trace how the digestive, respiratory and circulatory systems work together.',challenge:'Trace swallowed food from the mouth to the small intestine. How does digested food reach the other parts of the body? How does oxygen reach them?'}
};
function controls(skill,s){switch(skill){
 case 'circuits':return select('cells','Batteries (cells)',[[1,'One'],[2,'Two']],s.cells)+select('bulbs','Bulbs',[[1,'One'],[2,'Two']],s.bulbs)+toggle('parallel','Separate parallel branches',s.parallel)+toggle('closed','Switch closed',s.closed)+toggle('broken','Bulb A broken',s.broken);
 case 'shadows':return range('object','Object distance from light',25,75,s.object,' units')+range('height','Object height',8,24,s.height,' units');
 case 'heat':return range('minutes','Time after filling',0,20,s.minutes,' min');
 case 'plants':return select('part','Explore a structure',[['root','Roots'],['stem','Stem'],['leaf','Leaves'],['flower','Flowers']],s.part)+toggle('light','Light available',s.light)+toggle('water','Water available',s.water);
 case 'ecosystems':return select('organism','Trace a food source',[['algae','Algae'],['snail','Snail'],['larvae','Insect larvae'],['fish','Fish']],s.organism)+toggle('remove','Imagine fewer snails',s.remove);
 case 'forces':return range('push','Rightward push',0,8,s.push,' N')+range('friction','Opposing force to the left',0,5,s.friction,' N');
 case 'matter':return select('state','Start with',[['solid','Ice: solid'],['liquid','Water: liquid'],['gas','Water vapour: gas']],s.state)+select('process','Try a change',[['melting','Melting'],['freezing','Freezing'],['evaporation','Evaporation'],['condensation','Condensation']],s.process);
 case 'body':return select('system','Trace a pathway',[['digestive','Digestion and absorption'],['respiratory','Air and oxygen'],['circulatory','Transport in blood']],s.system);
 default:return '';
}}
function figure(skill,s,shown,assessment=false){
 shown=Boolean(shown)&&!assessment;
 if(skill==='circuits'){
  const m=MochiScience.circuit(s),parallel=s.parallel&&Number(s.bulbs)===2;
  const bulb=(x,y,name,broken)=>`<circle cx="${x}" cy="${y}" r="29" fill="${shown&&m.lit&&!broken?`hsl(43 100% ${96-Math.min(1,m.power/2)*34}%)`:'#f9f6ff'}" stroke="#63418f" stroke-width="4"/>${broken?line(x-13,y-13,x+1,y+1)+line(x+7,y+7,x+15,y+15):line(x-17,y-17,x+17,y+17)+line(x-17,y+17,x+17,y-17)}${label(x,y+61,name)}`;
  let wires=line(80,95,200,95)+line(260,95,520,95)+line(520,95,520,285)+line(520,285,80,285)+line(80,285,80,Number(s.cells)===2?220:202)+line(80,170,80,95);
  wires+=line(56,170,104,170)+line(65,188,95,188)+label(150,207,`${s.cells} cell${Number(s.cells)>1?'s':''}`);
  if(Number(s.cells)===2)wires+=line(80,188,80,202)+line(56,202,104,202)+line(65,220,95,220);
  else wires+=line(80,188,80,202);
  wires+=`<circle cx="200" cy="95" r="5"/><circle cx="260" cy="95" r="5"/>`+line(200,95,255,s.closed?95:60)+label(226,40,s.closed?'Closed':'Open');
  if(parallel){wires+=line(315,95,315,285)+line(450,95,450,285)+bulb(315,182,'A',s.broken)+bulb(450,182,'B',false);}
  else {wires+=bulb(Number(s.bulbs)===2?350:400,95,'A',s.broken);if(Number(s.bulbs)===2)wires+=bulb(485,95,'B',false);}
  // Remove the outer right shunt when separate bulb branches complete the circuit.
  if(parallel)wires=wires.replace(line(520,95,520,285),'');
  return svg(wires,'Circuit schematic showing battery cells, switch and bulb connections');
 }
 if(skill==='shadows'){
  const m=MochiScience.shadow(s),x=60+m.object*5,h=m.height*3,sh=m.shadow*3;
  return svg(`<circle cx="60" cy="175" r="12" fill="#d7a124"/>${line(510,35,510,315,'#a18bb7',7)}<path d="M60 175L510 ${175-sh/2}L510 ${175+sh/2}Z" fill="#dac8ff" opacity=".45"/>${line(60,175,510,175-sh/2,'#d5a024',3)}${line(60,175,510,175+sh/2,'#d5a024',3)}${line(x,175-h/2,x,175+h/2,'#654096',9)}${line(511,175-sh/2,511,175+sh/2,'#30203f',12)}${label(70,340,'Light')}${label(x,310,'Object')}${label(505,340,'Screen')}`,'Straight rays from a point light source past an opaque object onto a screen');
 }
 if(skill==='heat'){
  const curve=(k,start)=>Array.from({length:21},(_,i)=>`${i?'L':'M'}${70+i*22} ${292-(20+(start-20)*Math.exp(-k*i)-20)*3.1}`).join(' ');
  const m=MochiScience.cooling(s),x=70+m.minutes*22;
  return `<figure class="sc-art-plate sc-heat-plate"><img src="science-heat.webp" width="1200" height="800" alt="Original painted study of two matching cups with equal water levels, one bare and one with a lavender insulating wrap"><figcaption><span><i class="sc-key sc-key-bare"></i>Bare cup${shown?`<strong>${m.bare.toFixed(1)}°C</strong>`:`<small>Start: ${m.bareStart}°C</small>`}</span><span><i class="sc-key"></i>Wrapped cup${shown?`<strong>${m.wrapped.toFixed(1)}°C</strong>`:`<small>Start: ${m.wrappedStart}°C</small>`}</span></figcaption></figure>`+(shown?`<details class="sc-chart-detail" open><summary>Compare the cooling curves</summary>`+svg(`${line(70,60,70,292,'#aa9cb9',2)}${line(70,292,550,292,'#aa9cb9',2)}${[20,40,60,80].map(t=>label(34,300-(t-20)*3.1,t)+line(70,292-(t-20)*3.1,550,292-(t-20)*3.1,'#e8e0f1',1)).join('')}<path d="${curve(.085,m.bareStart)}" fill="none" stroke="#277e8a" stroke-width="5"/><path d="${curve(.025,m.wrappedStart)}" fill="none" stroke="#874acf" stroke-width="5"/>${shown?line(x,75,x,292,'#544261',2):''}${label(160,34,'Temperature / °C')}${label(70,337,'0')}${label(510,337,'20 min')}`,'Illustrative temperature against time curves: purple wrapped cup; teal bare cup')+'</details>':assessment?'':`<p class="sc-figure-caption">Predict which cup will cool faster. Test to compare temperatures.</p>`);
 }
 if(skill==='plants')return `<div class="sc-botanical"><img src="science-plant.webp" width="680" height="1020" alt="Original botanical illustration of a flowering bean plant, with leaves, stem and roots in cutaway soil">${[['root',50,78,'Roots'],['stem',50,51,'Stem'],['leaf',78,26,'Leaf'],['flower',60,19,'Flower']].map(([key,x,y,title])=>`<button type="button" class="sc-hotspot ${s.part===key?'selected':''}" style="left:${x}%;top:${y}%" data-sc-part="${key}" aria-label="Explore ${title}">${title}</button>`).join('')}</div>`;
 if(skill==='ecosystems'){
  // Keep every arrow tip 16 units outside the rounded label boxes.
  const arrow=(d,active)=>`<path d="${d}" fill="none" stroke="${active?'#8447c9':'#b2a0c4'}" stroke-width="${active?4:2.5}" marker-end="url(#${active?'scArrow':'scArrowMuted'})"/>`;
  const node=(x,y,w,t,active)=>`<rect x="${x}" y="${y}" width="${w}" height="54" rx="18" fill="${active?'#eadbf9':'#fbf8fe'}" stroke="#d0bde2" stroke-width="2"/><g font-size="30">${label(x+w/2,y+37,t)}</g>`;
  return `<img class="sc-pond" src="science-pond.webp" width="1080" height="720" alt="Original pond habitat illustration with green plants, a snail, fish, a frog and a dragonfly"><p class="sc-figure-caption">Follow the energy: food to consumer</p>`+svg(`${arrow('M156 165L214 73',s.organism==='algae')}${arrow('M156 185L204 277',s.organism==='algae')}${arrow('M386 73L440 163',s.organism==='snail')}${arrow('M396 277L440 187',s.organism==='larvae')}${node(20,148,120,'Algae',s.organism==='algae')}${node(230,30,140,'Snail',s.organism==='snail')}${node(220,266,160,'Larvae',s.organism==='larvae')}${node(456,148,124,'Fish',s.organism==='fish')}`,'Possible energy pathways: algae to snail and insect larvae; snail and larvae to fish');
 }
 if(skill==='forces'){
  const m=MochiScience.force(s);
  // Separate force lanes clear the illustration. Both use the same 22 units per newton.
  return `<p class="sc-figure-caption">A 2 kg cart, already moving right</p>`+svg(`<svg x="70" y="86" width="460" height="180" viewBox="0 172 1200 438"><image href="science-cart.webp" width="1200" height="800"/></svg><path d="M260 60h${m.push*22}" fill="none" stroke="#7742b5" stroke-width="5" opacity="${m.push?1:0}" marker-end="url(#scArrow)"/><path d="M340 296h-${m.friction*22}" fill="none" stroke="#277e8a" stroke-width="5" opacity="${m.friction?1:0}" marker-end="url(#scArrowTeal)"/><g font-size="30">${label(365,30,`Push: ${m.push} N right`)}${label(245,338,`Opposing: ${m.friction} N left`)}</g>`,'Painted dynamics cart with opposing force arrows in separate lanes: push to the right above, given opposing force to the left below')+`<p class="sc-model-reading">${shown?`Net force: ${Math.abs(m.net)} N ${m.net>0?'right':m.net<0?'left':'— balanced'}`:'Compare the opposing forces'}</p>`;
 }
 if(skill==='matter'){
  const change=MochiScience.changes[s.process],state=shown&&change&&change.from===s.state?change.to:s.state;const gas=state==='gas',solid=state==='solid';let dots='';
  for(let i=0;i<24;i++){const ring=Math.floor(i/6),angle=(i%6)*Math.PI/3;const x=gas?98+(i*89)%410:solid?205+(ring%2)*135+40*Math.cos(angle):225+(i%6)*28+(i%3-1)*3,y=gas?78+(i*47)%210:solid?118+Math.floor(ring/2)*100+40*Math.sin(angle):145+Math.floor(i/6)*27+(i%4-1)*3;dots+=`<circle cx="${x}" cy="${y}" r="9" fill="#9665d6" stroke="#633e94" stroke-width="2"/>`;}
  return svg(`<rect x="60" y="45" width="480" height="260" rx="12" fill="#f4edff" stroke="#cbb4e9" stroke-width="3"/>${dots}${label(300,337,solid?'Solid: ice':gas?'Gas: water vapour':'Liquid: water')}`,'Extension model of water particles: open rings in ice, closer together in liquid water, far apart in water vapour')+`<p class="sc-figure-caption">Extension model: particle arrangement. Ice has a more open arrangement than liquid water. Water vapour is invisible.</p>`;
 }
 const routes={
  digestive:{title:'Digestion, absorption and transport',steps:[['Mouth & gullet','Food is taken in and passes towards the stomach.'],['Stomach & small intestine','Food is digested. Digested food is absorbed through the walls of the small intestine into the blood.'],['Blood to body cells','Blood transports digested food to other parts of the body. Swallowed pieces of food do not travel around in the blood.']]},
  respiratory:{title:'Air to oxygen for cells',steps:[['Windpipe to lungs','Air reaches the lungs through branching airways.'],['Lungs to blood','Oxygen passes into blood. Carbon dioxide passes from blood into the lungs.'],['Blood to body cells','Blood carries oxygen to cells; carbon dioxide is carried away.']]},
  circulatory:{title:'The transport connection',steps:[['Heart','The heart pumps blood around the body.'],['Blood','Blood transports oxygen from the lungs and digested food absorbed in the small intestine.'],['Body cells','Blood supplies cells with oxygen and digested food and carries carbon dioxide away.']]}
 };
 const route=routes[s.system]||routes.digestive;
 return `<figure class="sc-art-plate sc-body-plate"><img src="science-body.webp" width="1200" height="800" alt="Original painted organ studies: digestive organs on the left, lungs and heart on the right"><figcaption><span>Digestive organs</span><span>Lungs & heart</span></figcaption></figure>${shown?`<section class="sc-route" aria-label="${route.title}"><h3>${route.title}</h3><ol>${route.steps.map(([title,explanation])=>`<li><strong>${title}</strong><span>${explanation}</span></li>`).join('')}</ol></section>`:assessment?'':`<p class="sc-figure-caption">Predict how these systems connect. Test your idea to trace the pathway.</p>`}`;
}
function observation(skill,s){const m=MochiScience.model(skill,s);switch(skill){
 case 'circuits':return !m.lit?'The circuit has a gap, so no current flows through the bulbs and they do not light up.':`${m.active} bulb${m.active>1?'s light':' lights'} up because there is a closed circuit. ${s.parallel&&Number(s.bulbs)===2?'Each working bulb is connected in its own branch across the battery.':'The components are connected in one path.'}`;
 case 'shadows':return `Shadow height: ${m.shadow.toFixed(1)} units for an object ${m.height} units high. Source to screen: 90 units; source to object: ${m.object} units.`;
 case 'heat':return `At ${m.minutes} min: bare cup ${m.bare.toFixed(1)}°C; wrapped cup ${m.wrapped.toFixed(1)}°C. Room: 20°C. Starting temperatures: bare cup ${m.bareStart}°C; wrapped cup ${m.wrappedStart}°C.`;
 case 'plants':return ({root:'Roots anchor the plant and absorb water and mineral salts.',stem:'The stem supports the plant and transports substances, including water to leaves.',leaf:'Green leaves use light energy, water and carbon dioxide to make food (sugar) during photosynthesis. Oxygen is also produced.',flower:'Flowers are involved in sexual reproduction; after successful fertilisation, seeds can develop.'}[s.part])+' '+(!s.light?'Without light, photosynthesis cannot take place. Respiration can continue, releasing energy from stored food.':!s.water?'A continuing lack of water limits photosynthesis and other functions.':'With suitable conditions, the parts support growth together.');
 case 'ecosystems':return s.remove?'Fewer snails could mean less grazing on algae and less food for some fish. Alternative food and other conditions can change the outcome.':({algae:'Algae are eaten by some snails and insect larvae. Energy is transferred from the algae to these consumers.',snail:'Some fish eat snails. The arrow goes from snail to fish.',larvae:'Some insect larvae eat algae; fish may eat the larvae. Species have different diets.',fish:'The fish obtains energy by eating other organisms. This simplified food web shows snails and insect larvae as its food sources.'}[s.organism]);
 case 'forces':return m.net===0?'The opposing forces are equal. In this extension model, the cart continues at the same speed in the same direction.':m.net>0?`Net force is ${m.net} N right; the right-moving cart speeds up.`:`Net force is ${-m.net} N left; the right-moving cart slows down at this instant.`;
 case 'matter':{const change=MochiScience.changes[s.process];return !change?'Choose a change of state.':s.state!==change.from?`To investigate ${s.process}, start with ${change.start}. Select that starting state, then test your prediction.`:change.text;}
 case 'body':return ({digestive:'Food passes through the gullet to the stomach and then small intestine. Digested food is absorbed through the walls of the small intestine into the blood.',respiratory:'Air reaches the lungs through the windpipe. Oxygen passes into blood; carbon dioxide passes out of blood to be breathed out.',circulatory:'Blood transports oxygen and digested food to all parts of the body and carries carbon dioxide away. The heart pumps the blood.'}[s.system]);
}}
root.MochiScienceScenes={details,controls,figure,observation};
})(typeof globalThis!=='undefined'?globalThis:this);
