/* Checked teaching models. These are simplified demonstrations, not physical measurements. */
(function(root){
'use strict';
const skills={
 circuits:{label:'Electric circuits',concept:'A bulb needs a complete conducting path through both battery terminals.',resource:'https://phet.colorado.edu/en/simulations/circuit-construction-kit-dc'},
 shadows:{label:'Light & shadows',concept:'Light travels in straight lines. An opaque object blocks some rays.',resource:'https://phet.colorado.edu/en/simulations/bending-light'},
 heat:{label:'Heat & fair tests',concept:'Heat transfers from hotter to cooler surroundings. Insulation slows the transfer.',resource:'https://openstax.org/books/physics/pages/11-2-heat-specific-heat-and-heat-transfer'},
 plants:{label:'Plant systems',concept:'Roots absorb water and mineral salts; leaves make sugars using light, water and carbon dioxide.',resource:'https://openstax.org/books/biology-2e/pages/8-1-overview-of-photosynthesis'},
 ecosystems:{label:'Living things & food webs',concept:'Food-web arrows point from a food organism to its consumer, showing energy transfer.',resource:'https://openstax.org/books/biology-2e/pages/46-2-energy-flow-through-ecosystems'},
 forces:{label:'Forces & motion',concept:'A net force changes motion. Opposing forces can balance.',resource:'https://phet.colorado.edu/en/simulations/forces-and-motion-basics'},
 matter:{label:'Matter & water',concept:'Melting and evaporation are different changes of state. Evaporation can occur below boiling.',resource:'https://www.usgs.gov/special-topics/water-science-school/science/water-cycle'},
 body:{label:'Human body systems',concept:'Digestion breaks down food; blood transports absorbed nutrients and oxygen to cells.',resource:'https://openstax.org/books/biology-2e/pages/34-1-digestive-systems'}
};
const defaults={circuits:{cells:1,bulbs:2,parallel:false,closed:false,broken:false},shadows:{object:45,height:18},heat:{minutes:0,insulated:true},plants:{part:'leaf',light:true,water:true},ecosystems:{organism:'algae',remove:false},forces:{push:4,friction:2},matter:{state:'solid',process:'melting'},body:{system:'digestive',part:'small intestine'}};
const copy=x=>JSON.parse(JSON.stringify(x));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
function circuit(s){const cells=clamp(s.cells,1,2),bulbs=clamp(s.bulbs,1,2),lit=!!s.closed&&(!s.broken||s.parallel&&bulbs===2);return {lit,active:lit?(s.broken?1:bulbs):0,power:lit?(s.parallel?cells*cells:(cells/bulbs)**2):0};}
function shadow(s){const object=clamp(s.object,25,75),height=clamp(s.height,8,24);return {object,height,shadow:height*90/object,magnification:90/object};}
function cooling(s){const t=clamp(s.minutes,0,20),temp=k=>20+60*Math.exp(-k*t);return {minutes:t,bare:temp(.085),wrapped:temp(.025),ambient:20,start:80};}
function force(s){const push=clamp(s.push,0,8),friction=clamp(s.friction,0,5);return {push,friction,net:push-friction,acceleration:(push-friction)/2};}
function model(skill,s){if(skill==='circuits')return circuit(s);if(skill==='shadows')return shadow(s);if(skill==='heat')return cooling(s);if(skill==='forces')return force(s);return copy(s);}
// Each item is authored; assessment items are reserved from the practice selector.
const items=[];
function add(skill,id,prompt,choices,answer,why,options={}){items.push({skill,id,prompt,choices,answer,why,level:1,...options});}
add('circuits','c-path','The switch is open. What must change to light both bulbs?', ['Close the switch','Add a second cell only','Turn one bulb upside down'],0,'Closing the switch completes a conducting path through the bulbs and both battery terminals.');
add('circuits','c-series','Two identical bulbs are in series. One bulb breaks. What happens to the other?', ['It stays equally bright','It goes out','It becomes brighter'],1,'The broken bulb opens the only conducting path, so neither bulb lights.',{level:2,state:{closed:true,broken:false}});
add('circuits','c-parallel','Two identical bulbs have separate parallel branches. One breaks. In this ideal-battery model, the other…',['Goes out','Keeps its brightness','Has to become brighter'],1,'The unbroken branch still has a complete path across the same ideal battery.',{level:3,state:{closed:true,parallel:true}});
add('circuits','c-assess','Two parallel lamps light a model house. Removing lamp A leaves lamp B lit. Which explanation fits?', ['Lamp B still has its own complete circuit','Electricity is stored inside lamp B','Current jumps across the empty socket'],0,'The second branch remains connected to both terminals.',{assessment:true,level:2,state:{closed:true,parallel:true,broken:true}});
add('shadows','l-block','What makes a shadow on the screen?', ['The object sends out darkness','The object blocks light travelling to the screen','The screen absorbs all surrounding air'],1,'An opaque object blocks some of the light travelling from the source to the screen.');
add('shadows','l-position','Keep the light and screen fixed. Move the same object nearer the light. What happens to its shadow?', ['It becomes larger','It becomes smaller','It must stay the same size'],0,'The object blocks a wider spread of rays. In this point-source model, shadow height / object height equals source-to-screen distance / source-to-object distance.',{level:2});
add('shadows','l-fair','You want to test the effect of object position on shadow size. What should stay fixed?', ['Only the date','Light position, screen position and object size','Both object size and object position must change'],1,'Changing only object position lets the comparison address that variable.',{level:3});
add('shadows','l-assess','The source-to-screen distance is fixed. An opaque card is moved towards the screen. Its shadow becomes…',['Larger','Smaller','A source of light'],1,'The rays spread less between the object and screen, so the shadow gets smaller.',{assessment:true,level:2,state:{object:65}});
add('heat','h-direction','The water starts at 80°C in a 20°C room. Which way does heat transfer overall?', ['From the room into the hotter water','From the hotter water to the room','There is no transfer unless water boils'],1,'There is net heat transfer from the hotter water to its cooler surroundings.');
add('heat','h-insulation','Identical cups start with equal volumes of equally hot water. Why might a wrapped cup cool more slowly?', ['The wrap continually makes heat','The wrap reduces heat transfer','The wrap makes the water heavier'],1,'Insulation reduces the rate of heat transfer. It does not supply heat.',{level:2});
add('heat','h-evidence','A wrapped cup started at 80°C; a bare cup started at 60°C. The wrapped cup is warmer later. Does this alone prove its wrap worked?', ['Yes, a warmer final reading proves it','No, the starting temperatures were different','Yes, the starting temperature never matters'],1,'The starting temperatures confound the comparison. Repeat with equal starting temperatures and control other relevant conditions.',{level:3});
add('heat','h-assess','To compare two insulating materials fairly, which arrangement is best?', ['Different cups, volumes and starting temperatures','Matching cups and water volumes, same start temperature, comparable wrap thickness, same surroundings','One cup indoors and the other outdoors'],1,'Control the other relevant variables, record temperatures at the same times, and repeat measurements.',{assessment:true,level:3});
add('plants','p-root','Which plant structure takes up water and mineral salts from the soil?', ['Roots','Flowers','Fruit'],0,'Roots absorb water and mineral salts. These are transported to other parts of the plant.');
add('plants','p-food','Where does a green plant make much of its food?', ['In leaves using light, water and carbon dioxide','By taking ready-made food from the soil','Only in flowers at night'],0,'Photosynthesis in green parts makes sugars using light energy, water and carbon dioxide. Soil supplies mineral salts, not the plant’s main food.');
add('plants','p-dark','A watered green plant is put in darkness. Which statement is best?', ['It immediately stops all life processes','It cannot photosynthesise, but respiration continues','Its roots replace sunlight'],1,'Light is needed for photosynthesis. Living plant cells continue to respire, using stored food.',{level:3,state:{light:false}});
add('plants','p-assess','A healthy plant gains mass as it grows. Which statement best explains where much of the carbon in its food came from?', ['Carbon dioxide in the air','Light itself becomes carbon','The flower petals absorb carbon from the pot'],0,'The plant uses carbon dioxide during photosynthesis to make sugars. This is a reasoning extension beyond naming plant parts.',{assessment:true,level:3});
add('ecosystems','e-arrow','In a food web, an arrow from algae to a snail means…',['The algae eats the snail','The snail obtains energy by eating algae','The snail protects all algae'],1,'The arrow points from food to consumer, in the direction of energy transfer.');
add('ecosystems','e-producer','Which organism in this pond can make food using sunlight?', ['Green algae','A frog','A snail'],0,'Green algae photosynthesise. Animals obtain food by consuming other organisms.');
add('ecosystems','e-change','Suppose fewer snails graze on algae. What is a reasonable initial prediction if other conditions stay similar?', ['Algae may increase because less is eaten','All pond animals must disappear instantly','The exact future numbers are known'],0,'Reduced grazing may allow more algae to remain. Real food webs have other influences, so this is a conditional prediction.',{level:3});
add('ecosystems','e-assess','A fish eats both snails and insect larvae. Snails decrease. Why can you not calculate the fish population from this fact alone?', ['Fish do not need food','Other food, predation, reproduction and conditions also matter','All consumers change by the same percentage'],1,'A food web supports possible causal explanations, not exact population forecasts from one change.',{assessment:true,level:3});
add('forces','f-net','A cart moving to the right has a 4 N force right and a 2 N friction force left. The net force is…',['2 N right','6 N right','2 N left'],0,'Opposite forces subtract: 4 − 2 = 2 N right. This changes its motion.');
add('forces','f-balanced','A cart is already moving right. The rightward push equals the leftward friction. What happens in this model?', ['It must stop immediately','It continues at constant velocity','It must speed up'],1,'Balanced forces mean no acceleration. An already moving object keeps a constant velocity in this model.',{level:3,state:{push:2,friction:2}});
add('forces','f-compare','The same moving cart receives the same push on two surfaces. One has greater opposing friction. What changes?', ['Its rightward acceleration is smaller','Its mass must disappear','Friction must point right'],0,'More opposing friction reduces the rightward net force. If friction exceeds the push, it slows while moving right.',{level:2});
add('forces','f-assess','A cart moves right with 3 N rightward push and 5 N leftward friction. At that moment it…',['Slows down','Instantly starts moving left','Speeds up to the right'],0,'The net force is 2 N left while velocity is right, so its rightward speed decreases. Force direction alone does not give its present motion direction.',{assessment:true,level:3,state:{push:3,friction:5}});
add('matter','m-melt','An ice cube becomes liquid water. What is this change called?', ['Condensation','Melting','Evaporation'],1,'Melting changes a solid into a liquid. The water is still the same substance.');
add('matter','m-evaporate','A puddle dries on a day below 100°C. How can that happen?', ['Water can evaporate below its boiling point','All the water must first freeze','Only boiling water can become water vapour'],0,'Evaporation takes place at the liquid surface and can occur below boiling.',{level:2,state:{state:'liquid',process:'evaporation'}});
add('matter','m-condense','Drops form on the outside of a cold sealed glass. Where did that water usually come from?', ['Liquid leaking through the glass','Water vapour in the surrounding air','The glass making a new substance'],1,'Water vapour in the air cools at the cold surface and condenses.',{level:2,state:{state:'gas',process:'condensation'}});
add('matter','m-assess','Equal wet cloths dry in still and moving air, with other conditions matched. Which is a reasonable prediction?', ['Moving air can make drying faster','Neither can dry below 100°C','Water changes into air permanently'],0,'Moving air can carry water vapour away, allowing faster evaporation. Compare repeated measurements.',{assessment:true,level:3,state:{state:'liquid'}});
add('body','b-absorb','Where are most digested nutrients absorbed into the blood?', ['Small intestine','Windpipe','Heart'],0,'The small intestine absorbs digested nutrients. The circulatory system then transports them.');
add('body','b-oxygen','Which sequence traces oxygen towards a body cell?', ['Lungs → blood → body cell','Stomach → bones → lungs','Heart → food → stomach'],0,'Oxygen passes from air in the lungs into blood and is transported to body cells.',{level:2,state:{system:'respiratory',part:'lungs'}});
add('body','b-systems','Why do body cells need both digestive and circulatory systems?', ['Digestion breaks down food; circulation carries absorbed nutrients','Blood chews food in the stomach','The heart absorbs all food directly'],0,'The systems have different connected roles: breakdown and absorption, then transport.',{level:3});
add('body','b-assess','A child says food travels through the lungs before reaching the stomach. Which correction is sound?', ['Swallowed food travels through the oesophagus; air travels through the windpipe','All food and air follow the same tube throughout','Food is pumped into the stomach by the heart'],0,'The digestive and respiratory pathways are distinct; the diagram is a simplified map, not a scale anatomy drawing.',{assessment:true,level:2});
function fresh(){return {version:1,attempts:[],notes:[],drafts:{},seenAssess:[],session:null};}
const cleanInk=raw=>(Array.isArray(raw)?raw:[]).slice(-80).map(s=>(Array.isArray(s)?s:[]).slice(0,500).filter(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite)).map(p=>p.map(v=>clamp(v,0,1))));
function validate(raw){const out=fresh();if(!raw||raw.version!==1)return out;
 out.attempts=(Array.isArray(raw.attempts)?raw.attempts:[]).slice(-1000).filter(a=>items.some(q=>q.id===a.item)&&Number.isFinite(a.at)).map(a=>({item:a.item,skill:items.find(q=>q.id===a.item).skill,at:a.at,choice:Number.isInteger(a.choice)?a.choice:-1,correct:a.correct===true&&a.choice===items.find(q=>q.id===a.item).answer,guess:a.guess===true,firstCorrect:a.firstCorrect===true,helped:a.helped===true,assessment:a.assessment===true,explanation:String(a.explanation||'').slice(0,2500),prediction:String(a.prediction||'').slice(0,1000),strokes:cleanInk(a.strokes),independent:a.correct===true&&a.choice===items.find(q=>q.id===a.item).answer&&a.firstCorrect===true&&!a.helped&&!a.guess}));
 out.notes=(Array.isArray(raw.notes)?raw.notes:[]).slice(-100).filter(n=>Object.hasOwn(skills,n.skill)).map(n=>({skill:n.skill,at:Number(n.at)||0,text:String(n.text||'').slice(0,2500),prediction:String(n.prediction||'').slice(0,1000),strokes:cleanInk(n.strokes),trials:(Array.isArray(n.trials)?n.trials:[]).slice(-12).map(t=>({state:copy(t.state||{}),result:copy(t.result||{})}))}));
 out.seenAssess=(Array.isArray(raw.seenAssess)?raw.seenAssess:[]).filter(id=>items.some(q=>q.id===id&&q.assessment));
 // Drafts are limited to authored fields; imported text is never rendered as HTML.
 for(const skill of Object.keys(skills)){const d=raw.drafts?.[skill];if(!d)continue;out.drafts[skill]={prediction:String(d.prediction||'').slice(0,1000),explanation:String(d.explanation||'').slice(0,2500),strokes:(Array.isArray(d.strokes)?d.strokes:[]).slice(-80).map(s=>(Array.isArray(s)?s:[]).slice(0,500).filter(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite)).map(p=>p.map(v=>clamp(v,0,1))))};}
 return out;
}
function evidence(data,skill){const a=data.attempts.filter(x=>x.skill===skill),recent=a.slice(-6),ind=recent.filter(x=>x.independent);return {count:a.length,independent:ind.length,misses:recent.filter(x=>!x.firstCorrect).length,days:new Set(ind.map(x=>new Date(x.at).toISOString().slice(0,10))).size,last:a.at(-1)?.at||0,label:!a.length?'Not checked':ind.length<2?'Building':'Practising'};}
function choose(data,mode='practice',focus=null){let pool=items.filter(q=>!!q.assessment===(mode==='assessment'));if(focus)pool=pool.filter(q=>q.skill===focus);
 if(mode==='assessment')return pool.find(q=>!data.seenAssess.includes(q.id))||null;
 const skillsIn=[...new Set(pool.map(q=>q.skill))];skillsIn.sort((a,b)=>{const score=k=>{const e=evidence(data,k);return !e.count?100:e.misses*4-e.independent+((Date.now()-e.last)>3*86400000?8:0);};return score(b)-score(a);});
 const skill=skillsIn[0];pool=pool.filter(q=>q.skill===skill);const e=evidence(data,skill),max=e.independent>=2?3:2;
 const manageable=pool.filter(q=>q.level<=max);if(manageable.length)pool=manageable;
 const freshItems=pool.filter(q=>!data.attempts.slice(-3).some(a=>a.item===q.id));return (freshItems.length?freshItems:pool)[0];
}
root.MochiScience={skills,defaults,items,copy,circuit,shadow,cooling,force,model,fresh,validate,evidence,choose};
if(typeof module!=='undefined')module.exports=root.MochiScience;
})(typeof globalThis!=='undefined'?globalThis:this);
