/* Original problems requiring combined relationships; tags are not exam calibration. */
(function(root){
'use strict';
const r=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const make=(skill,topic,text,answer,steps,extra={})=>({skill,topic,stars:4,transfer:true,text,answer,steps,...extra});
const generators=[
 function overlappingClubs(){const music=r(12,20),sport=r(12,20),both=r(4,9),neither=r(3,8),total=music+sport-both+neither;return make('model','Connected problems',`A class has ${total} pupils. ${music} attend music club, ${sport} attend sports club, and ${both} attend both. How many attend neither club? Explain why adding the two club counts needs a correction.`,neither,[`Adding ${music} + ${sport} counts each pupil in both clubs twice.`,`At least one club: ${music} + ${sport} − ${both} = ${total-neither}.`,`Neither: ${total} − ${total-neither} = ${neither}. Check the four separate groups.`],{hint:'Separate music only, sports only, both and neither. Where does double counting occur?'});},
 function averageAfterRemoval(){const n=r(5,8),mean=r(12,20),a=mean+r(3,8),b=mean-r(1,5),total=n*mean,answer=(total-a-b)/(n-2);return make('data','Changing averages',`The mean mass of ${n} parcels is ${mean} kg. Two parcels of ${a} kg and ${b} kg are removed. Find the mean mass of the remaining parcels. Give an exact value, using a fraction if needed.`,answer,[`Original total: ${n} × ${mean} = ${total} kg.`,`Remaining total: ${total} − ${a} − ${b} = ${total-a-b} kg.`,`Remaining count: ${n} − 2 = ${n-2}. Mean = ${total-a-b}/${n-2} kg.`],{suffix:'kg',hint:'A mean is not a total. Recover the total first, then change both total and count.'});},
 function insideBorder(){const w=r(16,24),h=r(11,15),b=r(1,3),ans=w*h-(w-2*b)*(h-2*b);return make('area','Composite geometry',`A rectangular garden is ${w} m long and ${h} m wide. A path ${b} m wide runs just inside all four edges. Find the area of the path.`,ans,[`The inner rectangle loses ${b} m on each of two opposite sides.`,`Inner dimensions: ${w-2*b} m by ${h-2*b} m.`,`Path area: ${w} × ${h} − ${w-2*b} × ${h-2*b} = ${ans} m².`,`Check by splitting into strips without counting the corners twice.`],{suffix:'m²',hint:'Draw the inner rectangle. How many path widths are removed from each outer dimension?',fig:`<svg viewBox="0 0 440 260" role="img" aria-label="A rectangular garden with a uniform path inside its boundary, not to scale"><rect x="70" y="45" width="300" height="165" fill="#ead7ff" stroke="#8158a8" stroke-width="3"/><rect x="102" y="77" width="236" height="101" fill="#fff" stroke="#8158a8" stroke-width="2"/><g font-size="23" font-family="system-ui" fill="#583773" text-anchor="middle"><text x="220" y="242">${w} m</text><text x="34" y="139">${h} m</text><text x="220" y="29">Path width ${b} m</text></g></svg>`});},
 function ratioWithFixedPart(){const a=r(2,4),b=r(6,9),drop=r(2,4),k=r(6,14),given=drop*k,answer=(a+b)*k;return make('ratio','Changing ratios',`The ratio of red to blue beads is ${a}:${b}. ${given} blue beads are removed, and the ratio becomes ${a}:${b-drop}. No red beads change. How many beads were there at first?`,answer,[`The unchanged red amount anchors the same ${a} units in both ratios.`,`Blue decreases by ${drop} units, equal to ${given} beads.`,`One unit is ${given} ÷ ${drop} = ${k}.`,`Original total: (${a} + ${b}) × ${k} = ${answer}.`],{hint:'Which quantity remains fixed? Does that let a ratio unit keep the same value?'});},
 function submergedObject(){const l=r(15,25),w=r(10,14),rise=r(2,5),ans=l*w*rise;return make('volume','Volume & displacement',`A tank has an internal rectangular base ${l} cm by ${w} cm. A solid object is fully submerged in the water. The water level rises by ${rise} cm without spilling. What is the volume of the object?`,ans,[`The submerged object displaces an equal volume of water.`,`The rise occupies base area × change in depth.`,`Volume = ${l} × ${w} × ${rise} = ${ans} cm³.`,`This uses full submersion and no spilling; a floating or partly submerged object would need different reasoning.`],{suffix:'cm³',hint:'Think about the extra space occupied up to the new water level. Which depth is relevant?',stretch:true});},
 function successiveDiscounts(){const original=r(4,12)*50,paid=original*.8*.75;return make('percent','Changing reference wholes',`A bag receives a 20% discount. A second discount of 25% is then taken off the reduced price. The final price is $${paid}. What was the original price?`,original,[`After the first discount, 80% of the original price remains.`,`The second discount leaves 75% of that reduced amount.`,`Final fraction = 0.80 × 0.75 = 0.60 of the original price.`,`Original price = ${paid} ÷ 0.60 = $${original}. The discounts do not add to 45%.`],{prefix:'$',hint:'The two percentages refer to different wholes. What fraction survives both reductions?'});},
 function hiddenRectangle(){const short=r(4,10),diff=r(2,7),long=short+diff,p=2*(long+short),ans=long*short;return make('area','Geometry & relationships',`A rectangle has perimeter ${p} cm. Its length is ${diff} cm greater than its width. Find its area.`,ans,[`Length + width = ${p} ÷ 2 = ${long+short}.`,`Remove the difference to make two equal widths: (${long+short} − ${diff}) ÷ 2 = ${short} cm.`,`Length = ${short} + ${diff} = ${long} cm.`,`Area = ${long} × ${short} = ${ans} cm². Check the perimeter.`],{suffix:'cm²',hint:'The perimeter gives twice the sum of the two dimensions. Combine that sum with their difference.'});},
 function repeatedRemainder(){const total=r(4,12)*24,left=total/4;return make('fractionProblem','Work backwards',`Euna spends 1/3 of her money on a book, then 1/4 of what remains on stationery. She gives half of the money left after that to a charity. She now has $${left}. How much money did she start with?`,total,[`Work backwards: before the donation she had ${left} × 2 = $${left*2}.`,`That was 3/4 of the amount before stationery, so that amount was ${left*2} ÷ 3 × 4 = $${total*2/3}.`,`After buying the book, 2/3 remained. Original amount = ${total*2/3} ÷ 2 × 3 = $${total}.`,`Check forwards: the fraction left is 2/3 × 3/4 × 1/2 = 1/4.`],{prefix:'$',hint:'Each fraction acts on a different remaining amount. Reverse the last change first.'});}
];
root.MochiTransfer={generators};
if(typeof module!=='undefined')module.exports=root.MochiTransfer;
})(typeof globalThis!=='undefined'?globalThis:this);
