/* Wide reading: "Did you know?" facts and weekend camp-style investigations.
   NUS High's selection looks for students who read widely in mathematics and the
   sciences and who can solve problems, explain their thinking and stay curious.
   Facts are short multiple-choice items with an explanation that teaches something
   extra; investigations are 20–40 minute open tasks with household materials and
   interview-style prompts for explaining reasoning aloud. Content only: no DOM. */
(function(root){
'use strict';
// Correct-answer positions cycle through a balanced, irregular pattern.
const PATTERN=[2,0,3,1,1,3,0,2,3,1,2,0];
let count=0;
function F(id,subject,topic,level,question,right,wrong,explain){
 const answer=PATTERN[count++%PATTERN.length],choices=wrong.slice();
 choices.splice(answer,0,right);
 return {id,subject,topic,question,choices,answer,explain,level};
}
const M='maths',S='science';
const facts=[
 // ── Maths ──
 F('wm01',M,'big ideas',1,'Which ancient civilisation first wrote down rules for calculating with zero as a number in its own right?','India',['Egypt','Rome','Greece'],
  'Around 1,400 years ago the Indian mathematician Brahmagupta wrote rules such as “a number minus itself is zero”. Roman numerals have no zero at all. Our place-value system needs zero as a placeholder: without it, 15 and 105 would look the same.'),
 F('wm02',M,'big ideas',1,'Pi (π) is what you get when you divide a circle’s circumference by its…','diameter',['radius','arc length','radius squared'],
  'For every circle, big or small, the circumference is a little more than 3 times the diameter, and that “little more than 3” is π ≈ 3.14. Wrap a string around a tin, then lay it across the top, and you can measure π yourself!'),
 F('wm03',M,'big ideas',2,'Which is true about the decimal digits of π?','They never end or repeat',['They stop after 100 places','They repeat every 6 digits','They end in a row of zeros'],
  'π is an irrational number: it cannot be written exactly as a fraction, and its digits go on forever without a repeating pattern. Fractions like 22/7 are handy approximations, not the real thing. Computers have now worked out trillions of its digits.'),
 F('wm04',M,'prime numbers',1,'How many even prime numbers are there?','Exactly one',['None at all','Exactly two','Infinitely many'],
  'The number 2 is the only even prime, because every larger even number can be divided by 2. And 1 is not a prime at all: a prime has exactly two different factors, 1 and itself.'),
 F('wm05',M,'prime numbers',2,'Over 2,000 years ago, which Greek mathematician proved that the prime numbers never run out?','Euclid',['Archimedes','Pythagoras','Ptolemy'],
  'Euclid’s clever idea: multiply any list of primes together and add 1. The new number leaves a remainder of 1 when divided by every prime on the list, so its prime factors must be primes missing from the list. However long your list, there is always another prime.'),
 F('wm06',M,'infinity',3,'Mathematicians compare infinite sets by pairing them up. Are there more counting numbers (1, 2, 3, …) or more even numbers (2, 4, 6, …)?','The same number of each',['More counting numbers','More even numbers','Infinities cannot be compared'],
  'Pair 1 with 2, 2 with 4, 3 with 6, and so on: every counting number gets exactly one even partner, with none left over, so the two sets are the same size. Georg Cantor used pairing ideas like this to prove that some infinities really are bigger than others.'),
 F('wm07',M,'patterns',1,'In the Fibonacci sequence 1, 1, 2, 3, 5, 8, 13, …, how is each new number made?','Add the two numbers before it',['Double the number before it','Add 1 to the number before it','Multiply the two numbers before it'],
  'So the number after 13 is 8 + 13 = 21. Leonardo of Pisa, nicknamed Fibonacci, made the sequence famous in Europe with a puzzle about breeding rabbits. Indian scholars had described the same numbers centuries earlier while studying rhythms in poetry.'),
 F('wm08',M,'patterns in nature',2,'Count the spirals on a sunflower head or a pine cone and you will very often find…','Fibonacci numbers',['Square numbers','Multiples of ten','Numbers that are all prime'],
  'A sunflower might have 34 spirals turning one way and 55 turning the other: two neighbouring Fibonacci numbers. Placing each new seed at a special turning angle packs the seeds tightly with no wasted space, and the Fibonacci numbers appear as a result.'),
 F('wm09',M,'patterns',2,'The golden ratio, often written φ (phi), is approximately…','1.618',['3.142','2.718','1.414'],
  'Divide neighbouring Fibonacci numbers, such as 55 ÷ 34, and the answers get closer and closer to 1.618… The wrong options are famous numbers too: 3.142 is π, 1.414 is the square root of 2, and 2.718 is a number called e.'),
 F('wm10',M,'symmetry',1,'How many lines of symmetry does a square have?','4',['2','8','1'],
  'Two lines join the midpoints of opposite sides and two run along the diagonals. A square also looks the same after a quarter turn, so it has rotational symmetry of order 4. A circle beats them all: it has infinitely many lines of symmetry.'),
 F('wm11',M,'tessellations',2,'Which of these regular shapes CANNOT tile a flat floor on its own without gaps?','Pentagon',['Triangle','Square','Hexagon'],
  'Where tiles meet at a point, their angles must add up to exactly 360°. Each angle of a regular pentagon is 108°, and 360 is not a multiple of 108. Only three regular shapes tile perfectly: equilateral triangles, squares and regular hexagons, the shape bees use for honeycomb.'),
 F('wm12',M,'binary',2,'Computers count in binary, using only 0 and 1. How is the number 5 written in binary?','101',['110','111','100'],
  'In binary the place values are 1, 2, 4, 8, 16, … with each one double the one before. 5 = 4 + 1, so there is a 1 in the fours place, a 0 in the twos place and a 1 in the ones place: 101. Computers use binary because a tiny switch can be either on (1) or off (0).'),
 F('wm13',M,'probability',1,'You roll a fair six-sided dice. What is the probability of rolling a number greater than 4?','1/3',['1/2','1/6','2/3'],
  'Only 5 and 6 are greater than 4, so 2 of the 6 equally likely outcomes work: 2/6 = 1/3. Probability always lies between 0 (impossible) and 1 (certain). The maths of chance grew partly out of letters between Blaise Pascal and Pierre de Fermat about fairly sharing the prize in an unfinished game.'),
 F('wm14',M,'probability',2,'A fair coin has landed heads 5 times in a row. What is the chance it lands heads on the next toss?','Still 1/2',['Less than 1/2','More than 1/2','Exactly zero'],
  'A coin has no memory! Each toss is independent, so the chance of heads is still 1/2. Believing that tails is “due” is such a common mistake that it has a name: the gambler’s fallacy.'),
 F('wm15',M,'Pythagoras',2,'A right-angled triangle has shorter sides of 3 cm and 4 cm. How long is its longest side?','5 cm',['7 cm','6 cm','12 cm'],
  'Pythagoras’ theorem says the squares on the two shorter sides add up to the square on the longest side: 9 + 16 = 25 = 5 × 5. The rule is named after Pythagoras, but Babylonian and ancient Chinese mathematicians knew it too. Builders still use a 3-4-5 triangle to check that a corner is square.'),
 F('wm16',M,'mathematicians',1,'The word “algorithm” comes from the name of which mathematician?','Al-Khwarizmi',['Archimedes','Pythagoras','Leonhard Euler'],
  'Muhammad ibn Musa al-Khwarizmi worked at the House of Wisdom in Baghdad over 1,000 years ago. The word “algebra” comes from “al-jabr” in the title of his book on solving equations. His writing also helped spread the Hindu–Arabic digits 0 to 9 that we use today.'),
 F('wm17',M,'mathematicians',2,'Ada Lovelace is often called the first computer programmer. What did she write?','Steps for a machine to follow',['A map of the stars in the southern sky','A guide to building steam engines','A book of puzzles about chess moves'],
  'She wrote a step-by-step method for Charles Babbage’s Analytical Engine, a mechanical computer that was designed but never fully built. She also imagined that such machines might one day compose music, not just do sums: a remarkable idea for the 1800s.'),
 F('wm18',M,'mathematicians',3,'Srinivasa Ramanujan, a largely self-taught genius from India, said the taxi number 1729 was very interesting. Why?','It is the sum of two cubes in two ways',['It can be divided exactly by every digit','It is the product of 1 to 7','It is a perfect square number'],
  '1729 = 1³ + 12³ = 9³ + 10³, and it is the smallest number that can be made from two cubes in two different ways. Ramanujan pointed this out when his friend G. H. Hardy visited him and called the taxi number dull. Numbers like this are now called “taxicab numbers”.'),
 F('wm19',M,'mathematicians',3,'Emmy Noether proved a famous link between symmetry and…','Conservation laws in physics',['The colours of a rainbow','How magnets attract iron','Why the sky looks blue in daytime'],
  'Noether’s theorem shows that every continuous symmetry in nature matches a quantity that is conserved. For example, the laws of physics working the same way today as tomorrow leads to the conservation of energy. Albert Einstein praised her as a creative mathematical genius.'),
 F('wm20',M,'mathematicians',2,'At NASA, mathematician Katherine Johnson’s calculations were trusted for…','Spacecraft flight paths',['Spacesuit designs','Menus for astronaut meals','Rocket fuel recipes'],
  'Johnson calculated the paths spacecraft would follow, including when to launch and where they would come down. Before astronaut John Glenn orbited the Earth, he asked for her to check the electronic computer’s numbers by hand. She later worked on calculations for the Apollo Moon missions.'),
 F('wm21',M,'mathematicians',3,'About 1,500 years ago in China, Zu Chongzhi found a very accurate fraction for π. Which one?','355/113',['311/99','22/9','1000/317'],
  '355 ÷ 113 = 3.1415929…, which matches π to six decimal places, and no fraction with a smaller denominator comes closer. It is easy to remember: write 113355, then split it into 113 and 355. Zu Chongzhi also showed that π lies between 3.1415926 and 3.1415927.'),
 F('wm22',M,'patterns',2,'In Pascal’s triangle, how is each number found?','Add the two numbers above it',['Double the number above it','Multiply the two numbers above it','Add 1 to the number above it'],
  'The rows begin 1; 1 1; 1 2 1; 1 3 3 1; … In China it is called Yang Hui’s triangle, after a mathematician who wrote about it centuries before Blaise Pascal was born. Hidden inside it are the counting numbers, the triangular numbers and even the Fibonacci numbers.'),
 F('wm23',M,'mathematicians',1,'A famous story says young Carl Friedrich Gauss quickly added all the whole numbers from 1 to 100. What is the total?','5050',['5000','4950','10100'],
  'Pair the numbers from the outside in: 1 + 100, 2 + 99, 3 + 98, … Each pair makes 101, and there are 50 pairs, so the total is 50 × 101 = 5050. The same trick adds any list of evenly spaced numbers.'),
 F('wm24',M,'mathematicians',3,'Archimedes showed that a sphere’s volume is what fraction of the volume of the cylinder that fits snugly around it?','2/3',['1/2','3/4','1/3'],
  'He was so proud of this discovery that he asked for a sphere inside a cylinder to be carved on his tomb. Archimedes also trapped π between two values by drawing shapes with 96 sides inside and outside a circle.'),
 F('wm25',M,'measurement',3,'Over 2,000 years ago, Eratosthenes estimated the size of the whole Earth. What did he use?','Shadows in two different cities',['A very long measuring rope','A ship sailing all the way round','The time a dropped stone fell'],
  'At noon on a midsummer day the Sun shone straight down in Syene, while in Alexandria a pole cast a shadow at about 7°, roughly 1/50 of a full circle. So the distance between the two cities had to be about 1/50 of the way round the Earth. His answer was remarkably close to the true size.'),
 F('wm26',M,'measurement',2,'When the metre was first defined in France, it was based on…','The size of the Earth',['A king’s arm length','The height of a door','The swing of a pendulum'],
  'It was meant to be one ten-millionth of the distance from the North Pole to the Equator. A pendulum that ticks once a second was also considered, but the Earth won. Today the metre is defined using the speed of light, so scientists anywhere can reproduce it exactly.'),
 F('wm27',M,'measurement',1,'In the metric system, what does the prefix “kilo-” mean?','One thousand',['One hundred','One million','One hundredth'],
  'So a kilometre is 1000 metres and a kilogram is 1000 grams. “Milli-” means one thousandth and “centi-” means one hundredth, which is why there are 100 centimetres in a metre. Because metric units are linked by powers of 10, converting is just moving the decimal point.'),
 F('wm28',M,'number systems',1,'Which number is written as XL in Roman numerals?','40',['60','90','400'],
  'When a smaller numeral comes before a larger one, you subtract it: XL means 50 − 10 = 40. The other way round, LX means 60. Roman numerals have no zero, which made long calculations very hard, so people did their sums on an abacus.'),
 F('wm29',M,'number systems',2,'We split an hour into 60 minutes and a minute into 60 seconds. This idea of counting in sixties first came from…','Ancient Mesopotamia',['Ancient Rome','Medieval Scandinavia','The Aztec Empire'],
  'People in ancient Mesopotamia (modern-day Iraq), including the Babylonians, counted in sixties. 60 divides exactly by 1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30 and 60. That is why half, a third, a quarter, a fifth and a sixth of an hour are all whole numbers of minutes.'),
 F('wm30',M,'mathematicians',2,'Hypatia of Alexandria, who lived about 1,600 years ago, is remembered as…','A teacher of maths and astronomy',['The first sailor to reach India by sea','The inventor of paper money','A queen who built a pyramid'],
  'Hypatia taught mathematics, astronomy and philosophy in Alexandria, Egypt, and wrote commentaries explaining the work of earlier mathematicians. She is one of the earliest women mathematicians whose life is well recorded.'),
 F('wm31',M,'shape and space',2,'Draw a line along the middle of a Möbius strip (a paper loop with a half-twist) without lifting your pencil. What happens?','The line covers both sides',['The line stops at an edge','It covers only the inside','It makes two separate loops'],
  'A Möbius strip has only one side and one edge, so your line visits both “sides” before it meets its start. Now try cutting along that line: instead of two loops, you get one longer loop! You can make one from a strip of paper and some tape.'),
 F('wm32',M,'shape and space',3,'For a cube, count the vertices (V), edges (E) and faces (F). What is V − E + F?','2',['0','6','4'],
  'For a cube, 8 − 12 + 6 = 2. Leonhard Euler noticed that V − E + F = 2 for every solid with flat faces and no holes. Test it on a triangular prism (6 − 9 + 5) or a square-based pyramid (5 − 8 + 5).'),
 F('wm33',M,'shape and space',3,'Leonhard Euler studied the Seven Bridges of Königsberg puzzle. What did he prove?','No walk crosses each bridge just once',['The shortest walk uses only four bridges','Each bridge must be crossed in order','The walk must start on the island'],
  'Euler turned the pieces of land into dots and the bridges into lines. A walk using every line exactly once is only possible if no more than two dots have an odd number of lines, and in Königsberg all four did. This idea started a whole branch of maths called graph theory.'),
 F('wm34',M,'patterns',2,'In a 3 × 3 magic square using each of the numbers 1 to 9 once, what must every row, column and diagonal add up to?','15',['12','18','45'],
  '1 + 2 + … + 9 = 45, and the three rows share this total equally, so each row makes 45 ÷ 3 = 15. An ancient Chinese legend tells of this square, the Lo Shu, appearing on the shell of a turtle. In every such square, 5 sits in the centre.'),
 F('wm35',M,'mathematicians',1,'Who invented the equals sign (=), saying that no two things can be more equal than two parallel lines?','Robert Recorde',['Isaac Newton','Leonhard Euler','Blaise Pascal'],
  'Robert Recorde, a Welsh doctor and mathematician, introduced the sign in a book over 450 years ago. Before that, writers had to write “is equal to” in words every time. Even the + and − signs were fairly new in his day.'),
 F('wm36',M,'big numbers',1,'A googol is the number 1 followed by how many zeros?','100',['10','1000','64'],
  'The name was suggested by the young nephew of an American mathematician, Edward Kasner. A googol is even bigger than the estimated number of atoms in the whole observable universe. The company name Google is a play on the word.'),
 // ── Science ──
 F('ws01',S,'scientists',2,'Marie Curie was the first person to win two Nobel Prizes. In which two sciences?','Physics and chemistry',['Chemistry and medicine','Physics and medicine','Biology and chemistry'],
  'She is still the only person to have won Nobel Prizes in two different sciences. With her husband Pierre she discovered two new elements: polonium, named after her home country Poland, and radium. Her notebooks are still slightly radioactive today!'),
 F('ws02',S,'scientists',3,'Physicist Chien-Shiung Wu’s famous experiment surprised scientists by showing that…','Nature is not always mirror-symmetric',['Light always travels in straight lines','Heavy things fall faster than light ones','Atoms can never be split apart'],
  'Physicists had assumed that every process in nature would work exactly the same way in a mirror image. Wu’s careful experiment with radioactive cobalt showed that one kind of radioactive decay prefers one direction. Born in China, she became known as the “First Lady of Physics”.'),
 F('ws03',S,'scientists',2,'Chinese scientist Tu Youyou won a Nobel Prize for discovering a medicine against which disease?','Malaria',['Measles','Smallpox','Diabetes'],
  'Malaria is spread by mosquitoes and kills hundreds of thousands of people each year. Tu Youyou found a clue in an ancient Chinese medical text about the sweet wormwood plant, and extracted a substance called artemisinin from it. She was the first Chinese woman to win a Nobel Prize in science.'),
 F('ws04',S,'scientists',2,'Zhang Heng, an inventor and astronomer in ancient China, built one of the first instruments to detect…','Earthquakes',['Rainfall','Lightning','Thunderstorms'],
  'His bronze device had eight dragons around the outside, each holding a ball above an open-mouthed toad. A tremor made one ball drop, hinting at the direction of the earthquake. He also built a water-powered model to show the movements of the stars.'),
 F('ws05',S,'inventions',2,'When Galileo pointed his telescope at Jupiter, what did he discover?','Four moons circling it',['A ring of ice around it','That it is made of rock','A giant red volcano'],
  'This showed that not everything in the sky goes around the Earth, which supported the idea that the Earth goes around the Sun. Those four moons, Io, Europa, Ganymede and Callisto, are still called the Galilean moons. Many more of Jupiter’s moons were found later with bigger telescopes.'),
 F('ws06',S,'space',1,'Which is the largest planet in our Solar System?','Jupiter',['Saturn','Neptune','Earth'],
  'More than 1,000 Earths could fit inside Jupiter. It is a gas giant with no solid surface to stand on, and its Great Red Spot is a giant storm that astronomers have watched for well over a century.'),
 F('ws07',S,'space',2,'Which planet has the hottest surface?','Venus',['Mercury','Mars','Jupiter'],
  'Venus is hotter than Mercury, even though Mercury is closer to the Sun. Its thick atmosphere of carbon dioxide traps heat like a heavy blanket, a runaway greenhouse effect. The surface is hot enough to melt lead.'),
 F('ws08',S,'space',1,'Why does the Moon seem to change shape during a month?','We see different amounts of its sunlit half',['The Earth’s shadow covers parts of it','Clouds in space block parts of it','The Moon itself shrinks and grows as it moves'],
  'The Sun always lights up half of the Moon. As the Moon orbits the Earth, we see more or less of that bright half, from new moon to full moon and back in about 29½ days. The Earth’s shadow only falls on the Moon during a lunar eclipse.'),
 F('ws09',S,'space',1,'What kind of object is the Sun?','A star, like the ones at night',['A planet that gives off its own light','A huge ball of burning coal','A moon that reflects light'],
  'The Sun is a star made mostly of hydrogen and helium. Deep in its core, hydrogen is squeezed into helium by nuclear fusion, releasing huge amounts of energy. It looks much bigger and brighter than other stars only because it is much closer: its light reaches us in about 8 minutes.'),
 F('ws10',S,'measurement',2,'A light-year is a unit used in astronomy. What does it measure?','A distance',['A length of time','A brightness','A speed'],
  'A light-year is how far light travels in one year: about 9.5 million million kilometres. The nearest star after the Sun is just over 4 light-years away, so the light you see from it set off more than four years ago.'),
 F('ws11',S,'forces',2,'On the Moon, you would weigh about what fraction of your weight on Earth?','One sixth',['One half','Twice as much','Exactly the same'],
  'Your mass, the amount of matter in you, stays the same, but the Moon’s gravity pulls on you only about one sixth as strongly as the Earth’s. That is why astronauts could bounce along in heavy spacesuits. Weight is a force, measured in newtons, named after Isaac Newton.'),
 F('ws12',S,'human body',1,'What is the largest organ of the human body?','The skin',['The liver','The brain','The lungs'],
  'Skin protects you from germs, stops you drying out and helps control your temperature by sweating. You shed tiny flakes of dead skin all the time, and new skin grows from underneath to replace them. The liver is the largest organ inside the body.'),
 F('ws13',S,'human body',1,'Which blood cells carry oxygen around your body?','Red blood cells',['White blood cells','Platelets','Nerve cells'],
  'Red blood cells are packed with haemoglobin, a substance containing iron that picks up oxygen in the lungs and releases it around the body. White blood cells fight germs, and platelets help blood to clot when you cut yourself. Red blood cells have no nucleus, which leaves more room for haemoglobin.'),
 F('ws14',S,'cells',1,'What is the smallest unit that can be called alive?','A cell',['An atom','A molecule','An organ'],
  'Every living thing is made of one or more cells: a bacterium is a single cell, while you are made of trillions. Robert Hooke named cells after looking at thin slices of cork under a microscope, because the tiny boxes reminded him of small rooms.'),
 F('ws15',S,'cells',2,'In plant and animal cells, where is most of the DNA kept?','In the nucleus',['In the cell wall','In the cell membrane','In the cytoplasm'],
  'DNA carries the instructions for building and running a living thing. Its shape, a twisted ladder called a double helix, was worked out with the help of X-ray pictures taken by Rosalind Franklin. Stretched out, the DNA in just one of your cells would be about 2 metres long.'),
 F('ws16',S,'cells',1,'Which of these is found in plant cells but NOT in animal cells?','Chloroplasts',['A nucleus','A cell membrane','Cytoplasm'],
  'Chloroplasts contain the green pigment chlorophyll, which traps light energy for photosynthesis. Plant cells also have a cell wall, which gives them a firm, boxy shape. Animal cells have neither, so they come in all sorts of shapes.'),
 F('ws17',S,'elements',1,'What is the chemical symbol for iron?','Fe',['Ir','I','In'],
  'Fe comes from “ferrum”, the Latin word for iron. Ir is iridium, I is iodine and In is indium. Other symbols also come from Latin names, such as Au for gold (aurum) and Ag for silver (argentum).'),
 F('ws18',S,'elements',1,'A water molecule, H₂O, is made of…','Two hydrogen atoms and one oxygen atom',['One hydrogen atom and two oxygen atoms','Two helium atoms and one oxygen atom','Two hydrogen atoms and two oxygen atoms'],
  'The small 2 after H tells you there are two hydrogen atoms, and no number after O means one oxygen atom. H₂O₂, with two of each, is hydrogen peroxide, a very different substance used as a bleach. Hydrogen and oxygen are both gases, yet together they make a liquid!'),
 F('ws19',S,'elements',2,'Diamond and the graphite in pencils are both made of which element?','Carbon',['Lead','Silicon','Calcium'],
  'In diamond each carbon atom is tightly locked to four others, making it extremely hard. In graphite the atoms form flat sheets that slide over each other, leaving a grey mark on paper. Despite the name, pencil “lead” contains no lead at all!'),
 F('ws20',S,'elements',3,'Dmitri Mendeleev left gaps in his periodic table of the elements. Why?','For elements not yet discovered',['To leave space for adding notes later','For elements too rare to use','For elements made only in labs'],
  'Mendeleev arranged the elements by their properties and saw that some must be missing. He predicted what those missing elements would be like, and when gallium and germanium were discovered, they matched his predictions closely. A good scientific idea makes predictions that can be tested.'),
 F('ws21',S,'states of matter',1,'Tiny droplets form on the outside of a glass of ice water. Which change of state is this?','Condensation',['Evaporation','Melting','Freezing'],
  'Water vapour in the air touches the cold glass, loses heat and turns into liquid water. The water has not leaked through the glass: it came from the air! Clouds form in a similar way when rising air cools.'),
 F('ws22',S,'measurement',3,'The coldest possible temperature, absolute zero, is 0 kelvin (0 K). About how cold is that in degrees Celsius?','−273 °C',['−100 °C','0 °C','−1000 °C'],
  'At absolute zero, particles would have the least possible energy, and nothing can be colder. The Kelvin scale starts there but uses steps the same size as Celsius degrees, so water freezes at about 273 K and boils at about 373 K. Scientists have cooled atoms to a tiny fraction of a degree above absolute zero, but never reached it.'),
 F('ws23',S,'energy',1,'When you rub your hands together quickly, movement energy is changed mainly into…','Heat energy',['Light energy','Electrical energy','Chemical energy'],
  'Friction between your hands converts kinetic (movement) energy into heat, which warms your skin. Energy is never destroyed, only changed from one form to another. That is also why bicycle and car brakes get hot when they slow you down.'),
 F('ws24',S,'electricity',1,'Which of these materials is a good conductor of electricity?','Copper',['Rubber','Plastic','Glass'],
  'Metals such as copper let electric current flow easily, which is why wires are made of copper. The wire is covered in plastic, an insulator, so the current cannot reach your hands. Pure water conducts poorly, but the dissolved substances in everyday water let current pass, so water and electricity are a dangerous mix.'),
 F('ws25',S,'light and sound',1,'In a thunderstorm, why do you see lightning before you hear the thunder?','Light travels much faster than sound',['Thunder is made after lightning ends','Eyes react faster than ears do','Sound must travel around clouds'],
  'Light reaches you almost instantly, but sound takes about 3 seconds to travel 1 kilometre through air. Count the seconds between the flash and the rumble, then divide by 3 to estimate how many kilometres away the storm is. Sound cannot travel through empty space at all, because it needs particles to vibrate.'),
 F('ws26',S,'light and sound',2,'When white sunlight passes through a glass prism, what comes out?','A spectrum of colours',['Only blue light','Black and white bands','A brighter beam of white light'],
  'Isaac Newton showed that white light is a mixture of colours, and that each colour bends by a slightly different amount in glass. Red bends the least and violet the most. A rainbow forms in a similar way when sunlight passes through raindrops.'),
 F('ws27',S,'magnets',1,'Which of these would be attracted to a magnet?','An iron nail',['An aluminium can','A copper wire','A gold ring'],
  'Only a few metals, mainly iron, nickel and cobalt, are attracted to magnets, so not all metals are magnetic! Recycling centres use strong magnets to pull steel cans, which are mostly iron, away from aluminium ones. The Earth itself behaves like a giant magnet, which is why a compass needle points north.'),
 F('ws28',S,'ecosystems',1,'In almost every food chain, where does the energy first come from?','The Sun',['The soil','Rainwater','The predators'],
  'Green plants, the producers, capture the Sun’s light energy and store it in food. Animals that eat plants, and animals that eat those animals, pass this energy along, but much of it is used up or lost as heat at each step. A rare exception is found deep in the ocean, where some food chains start with chemicals from hot vents.'),
 F('ws29',S,'Singapore',2,'Why are mangrove forests along Singapore’s coasts so valuable?','They protect the shore and shelter young fish',['They supply most of Singapore’s drinking water','They grow most of the rice eaten here','They keep mosquitoes away from homes'],
  'Mangrove roots trap mud and slow down waves, protecting the coast from erosion, and their tangled roots make a safe nursery for young fish and crabs. Some mangroves have special roots that poke up out of the mud to take in air. You can see them at places like Sungei Buloh Wetland Reserve.'),
 F('ws30',S,'Singapore',2,'What is NEWater in Singapore?','Used water cleaned until ultra-pure',['Rainwater collected from rooftops','Seawater with the salt taken out','Water piped in from mountain glaciers'],
  'Used water is treated and then passed through very fine membranes and ultraviolet light to make NEWater. It is one of Singapore’s Four National Taps, together with water from local catchments, imported water and desalinated seawater. Much of it goes to factories that need extremely pure water, such as those making computer chips.'),
 F('ws31',S,'Singapore',1,'Singapore lies very close to the equator. Why does it have no winter?','The Sun is high in the sky all year',['It is nearer the Sun than other countries','The warm sea heats the air in winter','It is surrounded by active volcanoes'],
  'Near the equator the midday Sun is always high overhead, so sunlight is strong all year and days are about 12 hours long in every month. Seasons happen because the Earth’s axis is tilted, which matters most far from the equator. Instead of summer and winter, Singapore has wetter and drier monsoon periods.'),
 F('ws32',S,'Singapore',1,'Which of these animals lives wild in Singapore’s forests?','The Sunda pangolin',['The giant panda','The red kangaroo','The Australian koala'],
  'The Sunda pangolin is covered in overlapping scales made of keratin, the same material as your fingernails, and curls into a ball when scared. It eats ants and termites with a very long, sticky tongue. It is critically endangered, so protecting Singapore’s forests really matters.'),
 F('ws33',S,'ecosystems',2,'Coral reefs are built by tiny animals called…','Polyps',['Plankton','Sponges','Jellyfish'],
  'Each coral polyp builds a hard limestone skeleton around itself, and over many years these add up to a reef. Tiny algae living inside the polyps make food from sunlight and give corals their colours. If the sea gets too warm, corals push out their algae and turn white: this is called coral bleaching.'),
 F('ws34',S,'inventions',2,'With his home-made microscopes, Antonie van Leeuwenhoek was one of the first people to see…','Bacteria',['Atoms','Viruses','Molecules'],
  'In the 1600s he made tiny, powerful lenses and saw “little animals” swimming in pond water and even in scrapings from his teeth. Viruses are far too small for an ordinary light microscope and were first seen with electron microscopes. Atoms are smaller still.'),
 F('ws35',S,'inventions',2,'Edward Jenner developed the first vaccine using cowpox. Which disease did it protect against?','Smallpox',['Malaria','Polio','Chickenpox'],
  'Jenner noticed that milkmaids who had caught mild cowpox did not catch deadly smallpox. The word “vaccine” comes from “vacca”, the Latin word for cow. Thanks to vaccination around the world, smallpox became the first human disease to be wiped out completely.'),
 F('ws36',S,'inventions',3,'How does satellite navigation, such as GPS, work out where your phone is?','It times signals from several satellites',['It takes photos of you from space','It measures how warm your phone is','It listens for the sound of your footsteps'],
  'Each satellite carries a very precise atomic clock and keeps sending out its time and position. Your phone measures how long each signal took to arrive, works out its distance from at least four satellites, and calculates where those distances meet. A timing error of just a millionth of a second would put you about 300 metres out.')
];

const I=(o)=>Object.assign({safety:''},o);
const investigations=[
 // ── Maths ──
 I({id:'im01',subject:M,title:'How many nets of a cube?',
  question:'How many different nets can be folded into a cube?',
  materials:['Squared paper (or plain paper and a ruler)','Pencil','Scissors','Sticky tape'],
  steps:['A net is a flat shape of six squares that folds up into a cube. Draw one you already know, such as a cross shape.',
   'Cut it out and fold it to check that it really makes a cube.',
   'Hunt for different nets. Draw each one on squared paper before you cut it out and test it.',
   'Two nets count as the same if one can be turned or flipped over to match the other. Check every new net against your collection.',
   'Sort your nets into groups by their longest row of squares: 4, 3 or 2.',
   'Keep going until you are sure you have found them all.'],
  predict:'Before you start, guess how many different cube nets there are. Write your guess down.',
  record:'A table with columns: net number, sketch, longest row (4, 3 or 2), folds into a cube? (yes/no). Keep the failures too.',
  explain:['How do you know two of your nets are really different, and not the same net turned over?',
   'How can you tell that six squares will NOT fold into a cube, without cutting them out?',
   'How would you convince someone you have found every net? What would happen if you tried the same hunt for a triangular pyramid?'],
  grownUp:'There are exactly 11 nets of a cube: 6 with a row of four squares, 4 whose longest row is three, and 1 “staircase” with rows of two. Good reasoning is systematic (“I kept a row of four and moved the last two squares around”) rather than random guessing. Listen for her explaining why a net fails, such as two squares that would fold onto the same face.',
  safety:'Take care with scissors; ask a grown-up if you need help.'}),
 I({id:'im02',subject:M,title:'Handshakes and diagonals',
  question:'If everyone at a party shakes hands with everyone else exactly once, how many handshakes are there?',
  materials:['Paper','Pencil','Ruler','Coins or buttons to stand for people'],
  steps:['Start small. With 2 people there is 1 handshake. Use coins to act out 3 people, then 4 people.',
   'Draw each group as dots around a circle and join every pair of dots with a straight line. Each line is one handshake.',
   'Count the lines for 2, 3, 4, 5 and 6 people and put the results in a table.',
   'Look at how much the number of handshakes goes up each time. What pattern do you see?',
   'Use your pattern to predict the handshakes for 10 people, then for everyone in your class.',
   'Look at your drawings again: some lines are sides of the shape and some are diagonals. Count only the diagonals for each shape.'],
  predict:'Guess how many handshakes there would be with 10 people. Is it more or less than 50?',
  record:'A table with columns: number of people, handshakes, increase from the row before, sides of the shape, diagonals.',
  explain:['Why does the number of handshakes go up by a bigger amount each time?',
   'Each of 10 people shakes 9 hands, but 10 × 9 = 90 is not the answer. Why must you halve it?',
   'How are the diagonals of a shape linked to the handshakes? What would happen with a 20-sided shape?'],
  grownUp:'For n people there are n × (n − 1) ÷ 2 handshakes, so 10 people make 45. The key insight is that n × (n − 1) counts every handshake twice, once from each person’s side. Diagonals are the handshakes minus the n sides, n × (n − 3) ÷ 2, so a hexagon has 9 and a 20-sided shape has 170.'}),
 I({id:'im03',subject:M,title:'Fold, count, predict',
  question:'Each time you fold a strip of paper in half, what happens to the number of regions and creases?',
  materials:['Several long strips of scrap paper (thin paper works best)','Pencil','Ruler','A fresh sheet of paper'],
  steps:['Fold a long strip of paper in half once, then unfold it. Count the regions (sections) and the creases.',
   'Fold a new strip in half, then in half again, always in the same direction. Unfold it and count again.',
   'Repeat for 3 folds and 4 folds, recording your results in a table each time.',
   'Look for patterns in both columns. How are the regions and the creases connected?',
   'Predict the regions and creases for 5 folds, then try it to check.',
   'Finally, take a fresh sheet and see how many times you can fold it in half at all. Count the layers at each step.'],
  predict:'How many regions do you think there will be after 4 folds? Write down your guess and your reason.',
  record:'A table with columns: number of folds, regions, creases, layers of paper while folded.',
  explain:['Why does the number of regions double each time, instead of going up by 2?',
   'How can you find the number of creases if you know the number of regions?',
   'Why does folding get so hard after a few folds? What would happen to the thickness after 10 folds?'],
  grownUp:'After n folds there are 2ⁿ regions and 2ⁿ − 1 creases, because each fold splits every existing region in two. Listen for her explaining the doubling (“every layer gets folded in half”), not just spotting it. The thickness doubles too: after 10 folds a 0.1 mm sheet would be over 10 cm thick, which is why paper quickly becomes impossible to fold.'}),
 I({id:'im04',subject:M,title:'Design a fair dice game',
  question:'When you roll two dice and add them, are all totals equally likely, and can you design a game that is fair?',
  materials:['Two dice','Paper and pencil','Counters or small objects for scoring','A partner to play against'],
  steps:['List all the possible totals when the numbers on two dice are added (from 2 to 12).',
   'Roll both dice 36 times and tally each total.',
   'Draw a 6 × 6 grid with one dice’s numbers along the top and the other’s down the side. Fill each box with the total, then count how many ways each total can happen.',
   'Compare your tally with your grid. Which totals are most likely and least likely?',
   'Invent a two-player game using two dice that you think is fair. For example, Player A scores on some totals and Player B on others.',
   'Play your game 20 times and record who wins each round.',
   'If your game was not fair, change the rules and test it again.'],
  predict:'Which total do you think will come up most often? Will 2 and 7 be equally likely?',
  record:'A tally table of totals 2 to 12 for your 36 rolls, your 6 × 6 grid, and a game table with columns: round, total rolled, winner.',
  explain:['Why is 7 more likely than 2 when you roll two dice?',
   'How did you make sure your game was fair? How many grid boxes does each player have?',
   'Your 20 games might not split exactly 10–10. Does that mean the game is unfair? What would happen if you used the difference between the dice instead of the total?'],
  grownUp:'There are 36 equally likely outcomes; a total of 7 can happen 6 ways (1 + 6, 2 + 5, …) but 2 only 1 way, so 7 is six times as likely. A fair game gives each player 18 of the 36 boxes, for example odd totals against even totals. Good reasoning separates what happened in a few rolls from what should happen in the long run.'}),
 I({id:'im05',subject:M,title:'Grains of rice in a cup',
  question:'How can you estimate the number of grains of rice in a cup without counting them all?',
  materials:['Uncooked rice','A measuring cup or mug','A teaspoon','Paper and pencil','A kitchen scale (optional)'],
  steps:['Make a first guess for the number of grains in a full cup and write it down.',
   'Fill a level teaspoon with rice. Tip it onto paper and count the grains carefully, in groups of 10.',
   'Count how many level teaspoons it takes to fill the cup.',
   'Multiply to estimate the number of grains in the cup.',
   'Repeat the teaspoon count two more times. Are the counts the same? Use the average.',
   'If you have a kitchen scale, try a second method: weigh 100 grains, weigh the full cup, and scale up.'],
  predict:'Before counting anything, guess the number of grains in a cup. Is it nearer 100, 1000, 10 000 or 100 000?',
  record:'A table with columns: method, grains per teaspoon (trials 1, 2, 3), average, teaspoons per cup, estimate for the cup.',
  explain:['Why is counting a small sample and multiplying a good idea? What could make it go wrong?',
   'Why were your three teaspoon counts different, and how does averaging help?',
   'Which method do you trust more, and why? What would happen if you had to estimate the grains in a whole 5 kg bag?'],
  grownUp:'A cup of uncooked rice usually holds several thousand grains; the exact number depends on the rice and the cup, so any well-reasoned estimate in the thousands is good. The key ideas are sampling and scaling up, and repeating samples to make the estimate more reliable. Listen for her spotting sources of error, such as heaped spoons or broken grains.'}),
 I({id:'im06',subject:M,title:'The biggest box from one sheet',
  question:'If you cut equal squares from the corners of a square sheet and fold up the sides, what corner size makes the box that holds the most?',
  materials:['Six or seven 20 cm × 20 cm squares of paper or thin card','Ruler','Pencil','Scissors','Sticky tape','Dried beans or rice to fill the boxes'],
  steps:['On one 20 cm square, mark a 1 cm square in each corner. Cut them out, fold up the sides to make an open box, and tape the corners.',
   'Make more boxes from fresh squares with corner cuts of 2 cm, 3 cm, 4 cm, 5 cm and 6 cm.',
   'For each box, measure the length, width and height, and work out the volume (length × width × height).',
   'Check by filling the boxes with dried beans. Which box holds the most?',
   'Draw a simple graph of volume against corner size.',
   'Use your graph to decide whether a corner size between two whole numbers might be even better, then test it.'],
  predict:'Which corner size do you think will give the biggest box: small, medium or large? Why?',
  record:'A table with columns: corner size (cm), length (cm), width (cm), height (cm), volume (cm³), rank in the bean test.',
  explain:['Why does a tiny corner cut give a small volume, even though the base is large?',
   'Why does a very big corner cut also give a small volume?',
   'Your best box was somewhere in the middle. Why is there a “best” size? What would happen with a 30 cm sheet?'],
  grownUp:'For a 20 cm sheet, a 3 cm cut gives 14 × 14 × 3 = 588 cm³, beating 2 cm (512 cm³) and 4 cm (576 cm³); the true best is about 3.3 cm. The key idea is a trade-off: a taller box has a smaller base. Listen for her explaining both sides of the trade-off and using her table to justify the best size.',
  safety:'Ask a grown-up to help with scissors.'}),
 // ── Science ──
 I({id:'is01',subject:S,title:'Paper helicopters',
  question:'Does a paper helicopter with longer wings take longer to fall?',
  materials:['Paper','Scissors','Ruler','Paper clips','A stopwatch or phone timer'],
  steps:['Make a helicopter: cut a paper strip about 5 cm wide and 20 cm long. Cut down the middle from the top to halfway to make two wings, then fold the wings in opposite directions.',
   'Fold up the bottom end and add a paper clip to weigh it down.',
   'Hold it at the same height each time, such as your arm stretched up, and let it go. Time how long it takes to reach the floor.',
   'Time three drops and work out the average.',
   'Make helicopters with shorter and longer wings, keeping everything else the same, and test each one.',
   'Compare your results. Then change one other thing, such as adding a second paper clip, and test again.'],
  predict:'Do you think longer wings will make it fall faster, slower, or make no difference? Why?',
  record:'A table with columns: wing length (cm), drop 1 (s), drop 2 (s), drop 3 (s), average (s).',
  explain:['Why did you keep the drop height and the paper clip the same each time?',
   'Why do we time three drops and find the average, instead of trusting just one?',
   'What makes the helicopter spin, and how does spinning slow it down? What would happen with no paper clip at all?'],
  grownUp:'Longer wings usually give a slower fall because the spinning wings push against more air, increasing air resistance, although very long wings may flop or flutter. The key ideas are a fair test (change one thing at a time) and repeating measurements because hand timing is imprecise. Strong answers mention air resistance and controlled variables without prompting.',
  safety:'Use scissors carefully, and never stand on chairs or furniture to drop the helicopters.'}),
 I({id:'is02',subject:S,title:'Paper columns: which shape is strongest?',
  question:'Which shape of paper column, triangle, square or circle, can hold up the most books?',
  materials:['3 sheets of the same kind of paper','Sticky tape','A stack of similar books or exercise books','Ruler'],
  steps:['Roll one sheet into a round tube, fold one into a square tube and fold one into a triangular tube. Make them all the same height and tape the edges.',
   'Stand one column upright on a flat table or floor.',
   'Gently place a book on top, centred. Keep adding books one at a time.',
   'Record how many books it holds just before it collapses.',
   'Repeat for the other two shapes, using the same books in the same order.',
   'If you have spare paper, make a second set and test again to check your results.'],
  predict:'Which shape do you think will hold the most books? Which will hold the least?',
  record:'A table with columns: shape, books held (test 1), books held (test 2), how and where it collapsed.',
  explain:['Why did you use the same paper, height and books for every column?',
   'Where did each column start to bend or crumple first? Why there?',
   'Why might many pillars in buildings be round? What would happen if you rolled two sheets together into one column?'],
  grownUp:'The round column usually holds the most because the weight is shared evenly all the way round, with no folded corners where it can start to buckle. Good reasoning links the result to where and how each column failed, and recognises why the test must be fair. Results vary with how neatly each column is made, which is itself a good point to discuss.'}),
 I({id:'is03',subject:S,title:'Pendulum timing',
  question:'What changes how long a pendulum takes to swing: the length of string, the weight on the end, or how far you pull it back?',
  materials:['String','A few identical metal washers or nuts','Sticky tape','Ruler','A stopwatch or phone timer','A table edge or door frame to hang it from'],
  steps:['Tie a washer to a 40 cm string and tape the top end firmly to a table edge so it can swing freely.',
   'Pull it back a little and let go without pushing. Time 10 complete swings (there and back is one swing), then divide by 10.',
   'Change only the length: try 20 cm and 60 cm. Time 10 swings each.',
   'Change only the weight: hang 2 or 3 washers on the 40 cm string.',
   'Change only the pull-back: try small, medium and larger (but still gentle) starts.',
   'Compare all your results. Which change made the biggest difference?'],
  predict:'Which change do you think will make the biggest difference to the swing time: length, weight or pull-back?',
  record:'A table with columns: what you changed, length (cm), number of washers, pull-back (small/medium/large), time for 10 swings (s), time for 1 swing (s).',
  explain:['Why time 10 swings and divide by 10, rather than timing just one swing?',
   'Which change made a real difference, and which did not? How sure are you?',
   'How could you make a pendulum that takes exactly one second for each swing? What would happen to your pendulum on the Moon?'],
  grownUp:'Only the length makes a big difference: longer strings swing more slowly, while the weight and (for small pull-backs) the starting angle have almost no effect. For one full there-and-back swing per second, the string needs to be about 25 cm, measured to the middle of the weight. On the Moon, with weaker gravity, the same pendulum would swing more slowly.'}),
 I({id:'is04',subject:S,title:'Ice-melting race',
  question:'In which kind of container does an ice cube melt fastest, and which keeps it frozen longest?',
  materials:['4 ice cubes of the same size','4 containers made of different materials, such as a metal tin, a ceramic mug, a plastic cup and a paper or foam cup','A timer','Paper towel'],
  steps:['Before you start, touch each empty container. Do any feel colder than the others, even though they have all been in the same room?',
   'Place the containers side by side in the same spot, away from direct sunlight.',
   'Take the ice cubes from the same tray at the same time and put one in each container.',
   'Start the timer. Every 5 minutes, describe or sketch how much ice is left in each.',
   'Note the time when each cube has completely melted.',
   'Rank the containers from fastest to slowest melting.'],
  predict:'Which container do you think will melt the ice fastest? Which will keep it longest? Give a reason.',
  record:'A table with columns: container material, ice left at 5, 10, 15 and 20 minutes (most/half/little/none), time fully melted.',
  explain:['Where does the heat that melts the ice come from?',
   'Why did the metal container feel cold to touch, even though it was at room temperature?',
   'Which container would you choose to keep a drink cold on a hot day, and why? What would happen if you wrapped it in a towel?'],
  grownUp:'Ice melts by taking in heat from its surroundings. Metal is a good conductor of heat, so it passes heat from the room to the ice quickly and the ice melts fastest; foam and plastic are poor conductors (insulators) and slow melting down. A common misconception is that insulators “keep the cold in”: really they slow the flow of heat, which is why a towel would keep the ice frozen longer, not melt it faster.'}),
 I({id:'is05',subject:S,title:'Dissolving race',
  question:'Does sugar dissolve faster in hot water or cold water?',
  materials:['Sugar cubes (or level teaspoons of sugar)','3 identical clear cups','Cold water from the fridge, room-temperature water and warm water','A measuring jug','A spoon','A timer','A kitchen thermometer (optional)'],
  steps:['Ask a grown-up to prepare the warm water. Pour the same amount (for example, 150 ml) of cold, room-temperature and warm water into the three cups.',
   'If you have a thermometer, measure the temperature of each cup.',
   'Drop one sugar cube into the first cup and start the timer. Stir gently at a steady speed, such as one stir every second.',
   'Stop the timer when you can no longer see any sugar.',
   'Repeat for the other two cups, stirring in exactly the same way.',
   'Extend it: at the same temperature, test whether crushing the cube or not stirring makes a difference.'],
  predict:'Which cup do you think will dissolve the sugar fastest? How much faster than the coldest cup?',
  record:'A table with columns: water (cold/room/warm), temperature (°C), time to dissolve (s), notes.',
  explain:['Why did you use the same amount of water and the same stirring each time?',
   'Why do you think the sugar dissolved faster in the warmer water? Think about the water particles.',
   'Where did the sugar go when it “disappeared”? What would happen if you left a spoonful of the water on a saucer for a day?'],
  grownUp:'Sugar dissolves faster in warmer water because the water particles move faster and collide with the sugar more often and with more energy. The sugar has not vanished: it is spread out among the water particles, which the saucer test shows: as the water evaporates, the sugar is left behind. Listen for her keeping the test fair and using the word “particles” in her explanation.',
  safety:'A grown-up should handle the hot water. Use warm water, not boiling water.'}),
 I({id:'is06',subject:S,title:'Shadow tracker',
  question:'How do the length and direction of a shadow change during the day?',
  materials:['A pencil or stick about 15 cm tall','Plasticine or Blu Tack to stand it up','A large sheet of paper','Stones or tape to hold the paper down','Ruler','A compass or phone compass app (optional)'],
  steps:['Stand the stick upright in the middle of the paper and put it in a spot that stays sunny for most of the day. Mark north on the paper if you can.',
   'Hold the paper down with stones or tape, and do not move it during the day.',
   'Every hour from morning to late afternoon, mark the tip of the shadow with a dot and write the time beside it.',
   'Measure the length of the shadow each time.',
   'At the end of the day, join the dots and look at the pattern they make.',
   'Draw a graph of shadow length against time of day.'],
  predict:'When will the shadow be shortest? Which way will it point in the morning, and which way in the afternoon?',
  record:'A table with columns: time, shadow length (cm), direction the shadow points.',
  explain:['Why does the shadow always point away from the Sun, and why does it move during the day?',
   'Why is the shadow shortest around the middle of the day?',
   'Singapore is very close to the equator. How might your results be different in London in December? What would happen if you repeated this in six months’ time?'],
  grownUp:'The shadow moves because the Earth spins, so the Sun appears to travel across the sky from east to west; morning shadows point roughly west and afternoon shadows roughly east. In Singapore the midday Sun is nearly overhead, so the midday shadow is very short and, depending on the time of year, points slightly north or slightly south. The Sun is highest at around 1 pm by Singapore clocks, not 12 noon, which is a nice surprise to discover.',
  safety:'Never look directly at the Sun.'})
];

const byId=new Map(facts.map(f=>[f.id,f]));
function dayNumber(dateKey){
 if(typeof dateKey!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(dateKey))return null;
 const ms=Date.parse(dateKey+'T00:00:00Z');
 if(!Number.isFinite(ms)||new Date(ms).toISOString().slice(0,10)!==dateKey)return null;
 return Math.floor(ms/86400000);
}
const mod=(a,b)=>((a%b)+b)%b;
// Prefer unseen items of the preferred subject, then unseen of the other subject,
// then cycle through the preferred subject again.
function choose(items,preferred,seen,k){
 const done=new Set(seen||[]),other=preferred===M?S:M;
 const fresh=s=>items.filter(x=>x.subject===s&&!done.has(x.id));
 let pool=fresh(preferred);
 if(!pool.length)pool=fresh(other);
 if(!pool.length)pool=items.filter(x=>x.subject===preferred);
 return pool[mod(k,pool.length)];
}
function factForDay(dateKey,seen=[]){
 const day=dayNumber(dateKey);
 if(day===null)return null;
 return choose(facts,mod(day,2)===0?M:S,seen,Math.floor(day/2));
}
// 1970-01-01 (day 0) was a Thursday; ISO weeks start on Monday.
function isoWeekIndex(day){
 const monday=day-mod(day+3,7);
 return (monday+3)/7;
}
function investigationForWeek(dateKey,done=[]){
 const day=dayNumber(dateKey);
 if(day===null)return null;
 const week=isoWeekIndex(day);
 return choose(investigations,mod(week,2)===0?M:S,done,Math.floor(week/2));
}
function check(id,choice){
 const f=byId.get(id);
 if(!f)return null;
 const index=typeof choice==='string'?f.choices.indexOf(choice):choice;
 return {correct:index===f.answer,explain:f.explain};
}
const api={facts,investigations,factForDay,investigationForWeek,check};
root.MochiWideReading=api;
if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
