const test=require('node:test'),assert=require('node:assert/strict'),E=require('../entrance-core.js'),D=E.D,B=E.B,now=Date.UTC(2026,8,25,18),day=E.DAY;
const taught=(d,id,t=now)=>{for(let p=0;p<3;p++)E.visit(d,id,p,t);E.concept(d,id,E.unit(id).check[2],t+1);assert.equal(E.complete(d,id,t+2),true);};
const answer=(d,id='percent',phase='apply',seed=21,t=now+10000,wrong=false)=>{E.finishPractice(d);const v=E.startPractice(d,id,{phase,seed,now:t}),q=E.question(v);E.touchDraft(d,{answer:wrong?'999999':q.answerLabel,working:'Synthetic reasoning'},t+1);return E.respond(d,t+2).attempt;};
test('new pathway is additive and does not relabel previous practice as DSA evidence',()=>{
 const s={learning:{attempts:[{id:'old',generator:'gst',tries:1,correct:false,firstCorrect:false,at:now},{id:'old2',generator:'gst',tries:1,correct:false,firstCorrect:false,at:now+2}]},coins:87,science:{attempts:[{id:'science'}]},catFriends:{unlocked:['miso']}};const before=JSON.stringify(s);assert.equal(E.recommend(s,now+3).unit,'percent');const {entrance,...rest}=s;assert.equal(JSON.stringify(rest),before);assert.equal(entrance.attempts.length,0);assert.ok(E.report(entrance).units.every(u=>!u.independent));
});
test('lesson exposure requires three sections and a correct conceptual exit, without a performance grade',()=>{const d=E.fresh();E.visit(d,'counting');assert.equal(E.complete(d,'counting'),false);for(let i=0;i<3;i++)E.visit(d,'counting',i,now);assert.equal(E.complete(d,'counting'),false);E.concept(d,'counting',E.unit('counting').check[2],now);assert.equal(E.complete(d,'counting'),true);assert.equal(E.evidence(d,'counting').independent,0);});
test('completed exposure survives later concept revisions and backup trimming',()=>{const d=E.fresh();taught(d,'counting');for(let i=0;i<20;i++)E.concept(d,'counting',(E.unit('counting').check[2]+1)%3,now+i+100);assert.equal(E.validate(d).lessons.counting.completedAt,d.lessons.counting.completedAt);});
test('guided success, revision, guessing and hints never masquerade as independent success',()=>{
 for(const kind of ['guided','wrong','guess','hint','reveal']){const d=E.fresh();taught(d,'percent');const v=E.startPractice(d,'percent',{phase:kind==='guided'?'guided':'apply',seed:31,now:now+100});const q=E.question(v);if(kind==='hint'||kind==='reveal')E.help(d,kind==='reveal');if(kind==='guess')E.touchDraft(d,{guess:true});if(kind==='wrong'){E.touchDraft(d,{answer:'1'});E.respond(d,now+101);}E.touchDraft(d,{answer:q.answerLabel});const a=E.respond(d,now+102).attempt;assert.equal(a.correct,true,kind);assert.equal(a.independent,false,kind);assert.equal(E.validate(d).attempts[0].independent,false,kind);}
});
test('format trouble is not recorded as a mathematical error',()=>{const d=E.fresh();E.startPractice(d,'percent',{seed:15,now});E.touchDraft(d,{answer:'O.35'});const result=E.respond(d,now+5);assert.equal(result.ok,false);assert.match(result.reason,/format/);assert.equal(d.attempts.length,0);});
test('two independent applications invite a structurally different transfer form, not repetition mastery',()=>{const d=E.fresh();taught(d,'percent');answer(d,'percent','apply',22);assert.equal(E.evidence(d,'percent').stage,'Apply');answer(d,'percent','apply',89);assert.equal(E.evidence(d,'percent').stage,'Connect');answer(d,'percent','transfer',123);assert.equal(E.evidence(d,'percent').stage,'Revisit after a week');assert.equal(E.evidence(d,'percent').forms,2);});
test('fingerprints reflect actual text rather than seeds; exposed repeats do not increase transfer evidence',()=>{const d=E.fresh();taught(d,'invariants');const q=B.make('invariants',2,18);d.seen[q.fingerprint]=now;const a={id:'repeated',unit:q.unit,form:q.form,seed:q.seed,at:now+10,mode:'practice',phase:'transfer',seenBefore:true,responses:[{answer:q.answerLabel,at:now+11}]};E.record(d,a);assert.equal(E.evidence(d,'invariants').transfer,0);const duplicate=E.record(d,{...a,id:'second',seenBefore:false});assert.equal(duplicate.seenBefore,true);});
test('recall requires a full week after both independent work and latest teaching exposure',()=>{
 const d=E.fresh();taught(d,'percent');answer(d,'percent','apply',22,now+100);answer(d,'percent','apply',89,now+200);const x=answer(d,'percent','transfer',123,now+300);E.finishPractice(d);assert.equal(E.recommend({entrance:d},x.answeredAt+7*day-1).kind==='recall',false);assert.equal(E.recommend({entrance:d},x.answeredAt+7*day+1).kind,'recall');answer(d,'percent','recall',133,x.answeredAt+7*day+2);assert.equal(E.evidence(d,'percent',now+8*day).delayed,1);
 const c=E.validate(d);E.visit(c,'percent',0,now+20*day);answer(c,'percent','recall',255,now+20*day+100);assert.equal(E.evidence(c,'percent',now+21*day).delayed,1,'a new lesson cannot be immediately counted as delayed recall');
});
test('later solution discussion and reflection preserve the original independent response',()=>{const d=E.fresh();taught(d,'percent');const a=answer(d);E.help(d,true);assert.equal(d.attempts[0].independent,true);a.reflection='Later independent check';a.reflectionInk=[[[.1,.2],[.3,.4]]];a.reflectionAt=now+20000;const v=E.validate(d).attempts[0];assert.equal(v.responses[0].working,'Synthetic reasoning');assert.equal(v.reflection,a.reflection);assert.deepEqual(v.reflectionInk,a.reflectionInk);});
test('two failed first answers route to teaching after the saved draft is finished',()=>{const d=E.fresh();taught(d,'area');answer(d,'area','apply',10,now+100,true);answer(d,'area','apply',20,now+200,true);E.finishPractice(d);const r=E.recommend({entrance:d},now+1000);assert.equal(r.unit,'area');assert.equal(r.kind,'learn');});
test('reserved papers are fixed, balanced and distinct; practice never selects reserved form',()=>{
 const seen=new Set();for(const p of E.paperDefinitions){const qs=E.paperQuestions(p.id);assert.equal(qs.length,p.kind==='paper'?24:6);for(const q of qs){assert.equal(seen.has(q.fingerprint),false,q.id);seen.add(q.fingerprint);if(p.kind==='paper')assert.equal(q.form,3);}assert.deepEqual(qs,E.paperQuestions(p.id));}
 const d=E.fresh();for(const phase of ['guided','apply','transfer','recall']){E.finishPractice(d);assert.ok(E.startPractice(d,'circles',{phase,now}).form<3);}
});
test('opening a paper records exposure, a second start resumes, and a second active paper is blocked',()=>{const d=E.fresh(),p=E.startPaper(d,'mixed-a',now);assert.equal(Object.keys(d.seen).length,24);assert.equal(E.startPaper(d,'mixed-a',now+1000).deadline,p.deadline);assert.throws(()=>E.startPaper(d,'mixed-b',now+1000),/Finish/);assert.equal(E.scorePaper(d,'mixed-a'),null);});
test('paper responses are editable before submission and frozen afterwards',()=>{const d=E.fresh(),p=E.startPaper(d,'mixed-a',now),q=E.paperQuestions(p.id)[0];E.savePaperAnswer(d,p.id,0,{answer:'1',working:'First idea'},now+10);E.savePaperAnswer(d,p.id,0,{answer:q.answerLabel,working:'Revised before submission',strokes:[[[.1,.2]]]},now+20);assert.equal(E.scorePaper(d,p.id),null);E.submitPaper(d,p.id,now+300);assert.equal(E.scorePaper(d,p.id).correct,1);assert.equal(E.savePaperAnswer(d,p.id,0,{answer:'changed'},now+400),false);assert.equal(E.scorePaper(d,p.id).correct,1);assert.equal(d.attempts.filter(a=>!a.skipped).length,1);});
test('restoration keeps the original deadline and blocks late edits',()=>{const d=E.fresh(),p=E.startPaper(d,'mixed-a',now);const copy=E.validate(d);assert.equal(copy.papers[p.id].deadline,now+75*60000);assert.equal(E.savePaperAnswer(copy,p.id,0,{answer:'4'},p.deadline+1),false);E.submitPaper(copy,p.id,p.deadline+5000);assert.equal(E.scorePaper(copy,p.id).timed,false);});
function fillPaper(d,id,t=now){E.startPaper(d,id,t);E.paperQuestions(id).forEach((q,i)=>E.savePaperAnswer(d,id,i,{answer:q.answerLabel,working:'Reasoned test response'},t+100+i));return E.submitPaper(d,id,t+10000);}
test('three unique perfect papers plus reviewed strands reach only an internal training target',()=>{const d=E.fresh();for(const [i,id]of ['mixed-a','mixed-b','mixed-c'].entries()){const score=fillPaper(d,id,now+i*day);assert.equal(score.qualifying,true);assert.equal(score.percent,100);}
 let report=E.report(d);assert.equal(report.qualifyingPapers,3);assert.equal(report.internalTarget,false);for(const strand of Object.keys(D.strands)){const a=d.attempts.find(a=>E.unit(a.unit).strand===strand);E.review(d,a.id,'valid','Adult review',now+4*day);}report=E.report(d);assert.equal(report.internalTarget,true);assert.equal(report.externalReported,false);assert.equal(E.submitPaper(d,'mixed-a',now+10*day).percent,100);assert.equal(E.report(d).qualifyingPapers,3);assert.match(report.limits.join(' '),/not an admissions cutoff/);});
test('a paused, assisted or previously exposed paper cannot count towards the independent target',()=>{for(const flag of ['interrupted','assisted','seenBefore','conflicted']){const d=E.fresh();E.startPaper(d,'mixed-a',now);d.papers['mixed-a'][flag]=true;fillPaper(d,'mixed-a');assert.equal(E.scorePaper(d,'mixed-a').qualifying,false,flag);}});
test('external scores and explanation reviews are sanitised separate evidence',()=>{const d=E.fresh();const a=answer(d);E.review(d,a.id,'valid','Parent note',now+day);E.addExternal(d,{name:'External form',score:88,total:100,unseen:true,independent:true,timed:true});assert.equal(E.report(d).externalChecks,1);assert.equal(E.report(d).qualifyingPapers,0);assert.throws(()=>E.addExternal(d,{name:'Invalid',score:10,total:5}));assert.equal(E.review(d,'__proto__','valid'),false);});
test('backup validation recomputes flags and removes unknown properties and imported code',()=>{const d=E.fresh();const a=answer(d,'percent','apply',44,now+10,true);a.correct=true;a.independent=true;a.evil='SECRET';d.extra='SECRET';const v=E.validate(d);assert.equal(v.attempts[0].correct,false);assert.equal(v.attempts[0].independent,false);assert.doesNotMatch(JSON.stringify(v),/SECRET/);assert.throws(()=>E.validate({version:99}));});
test('merge conservatively preserves a first miss, help, reflections and incompatible revisions',()=>{const d=E.fresh();const a=answer(d,'percent','apply',44,now+10,true);const x=E.validate(d),y=E.validate(d);E.touchDraft(y,{answer:E.question(y.draft).answerLabel},now+20);E.respond(y,now+21);const z=E.merge(x,y);assert.equal(z.attempts[0].correct,true);assert.equal(z.attempts[0].firstCorrect,false);assert.equal(z.attempts[0].independent,false);assert.deepEqual(E.merge(x,y),E.merge(y,x));assert.deepEqual(E.merge(z,z),z);
 const divergent=E.validate(x);divergent.attempts[0].responses[0].answer='2';const conflict=E.merge(divergent,y);assert.equal(conflict.attempts[0].conflicted,true);});
test('paper merge cannot erase an interruption even if the other device has submitted a correct paper',()=>{const d=E.fresh();E.startPaper(d,'mixed-a',now);const x=E.validate(d),y=E.validate(d);E.interruptPaper(x,'mixed-a',now+20);fillPaper(y,'mixed-a');const z=E.merge(x,y);assert.equal(E.scorePaper(z,'mixed-a').independent,false);assert.ok(z.attempts.every(a=>!a.independent));assert.deepEqual(E.merge(x,y),E.merge(y,x));});
test('parent credentials remain local and old cloud states cannot erase the entrance record',()=>{const fs=require('node:fs'),vm=require('node:vm');const ctx={window:{MochiEntrance:E},MochiEntrance:E,document:{addEventListener(){}},JSON};vm.runInNewContext(fs.readFileSync(require.resolve('../cloud-sync.js'),'utf8').replace('if(window.MochiReady)init();','window.testMerge=mergeState;if(window.MochiReady)init();'),ctx);const d=E.fresh();answer(d);const x=ctx.window.testMerge({keys:{openai:'LOCAL'},entrance:d},{keys:{openai:'REMOTE'}},true);assert.equal(x.keys.openai,'LOCAL');assert.equal(x.entrance.attempts.length,1);});
test('learning mirror contains a separate path export without resetting legacy counters or rewards',()=>{const L=require('../learning.js'),R=require('../learning-review.js');const s={learning:L.fresh(),entrance:E.fresh(),coins:45,science:{version:1,attempts:[]}};answer(s.entrance);const keys={...s,keys:{openai:'LOCAL_SECRET'}};const before=s.coins,exported=R.build(keys,'6.0.0');assert.equal(exported.entrance.attempts.length,1);assert.equal(exported.learning.attempts.length,0);assert.equal(s.coins,before);assert.doesNotMatch(JSON.stringify(exported),/LOCAL_SECRET/);});
