const test=require('node:test'),assert=require('node:assert/strict');
const T=require('../today-core.js'),P=require('../planner-core.js'),M=require('../entrance-core.js'),S=require('../science-path-core.js');
const now=new Date(2026,8,25,12).getTime(),DAY=86400000;
const fresh=()=>({planner:P.fresh(),entrance:M.fresh(),sciencePath:S.fresh(),learning:{attempts:[]},science:{attempts:[]},coins:42,worn:{neck:'bell'}});
function worked(s,subject,minutes){s.planner.sessions.push({id:'time-'+subject,subject,day:P.localDay(now),start:now-3600000+(subject==='science'?1800000:0),end:now-3600000+(subject==='science'?1800000:0)+minutes*60000});}
function finish(d,E,id,at){for(let p=0;p<3;p++)E.visit(d,id,p,at);E.concept(d,id,E.unit(id).check[2],at);E.complete(d,id,at);}
function answer(d,E,id,phase,at){E.finishPractice(d);E.startPractice(d,id,{phase,seed:at%100000,now:at});E.touchDraft(d,{answer:E.question(d.draft).answerLabel||E.question(d.draft).answer},at);E.respond(d,at+1);}
test('fresh home has one maths recommendation, two paced blocks and no new records',()=>{const s=fresh(),before=JSON.stringify(s),m=T.model(s,now);assert.equal(m.next.subject,'maths');assert.equal(m.next.kind,'lesson');assert.equal(m.blocks.length,2);assert.equal(m.blocks[0].minutes,15);assert.equal(m.blocks[1].minutes,15);assert.equal(JSON.stringify(s),before);assert.equal(m.completed,0);});
test('even an empty or older backup is read without mutating or inventing mastery',()=>{for(const s of [{},{learning:{attempts:[]},coins:88}]){const before=JSON.stringify(s);assert.equal(T.model(s,now).next.subject,'maths');assert.equal(JSON.stringify(s),before);}});
test('latest unfinished science answer precedes a new maths lesson',()=>{const s=fresh();S.startPractice(s.sciencePath,'fairtest',{now:now-2000,seed:12});S.touchDraft(s.sciencePath,{answer:'c1:r2',working:'Unsent evidence'},now-1000);const before=JSON.stringify(s);const m=T.model(s,now);assert.equal(m.next.subject,'science');assert.equal(m.next.kind,'question');assert.equal(m.next.resume,true);assert.equal(m.order[0].subject,'science');assert.equal(JSON.stringify(s),before);});
test('saved lesson section can be resumed instead of restarting at section one',()=>{const s=fresh();M.visit(s.entrance,'percent',1,now-10);assert.equal(T.model(s,now).next.unit,'percent');assert.equal(T.model(s,now).next.resume,true);assert.equal(s.entrance.lessons.percent.page,1);});
test('a finished draft is kept but is not labelled an unfinished question',()=>{const s=fresh();M.startPractice(s.entrance,'relationships',{now:now-1000,seed:31});M.touchDraft(s.entrance,{answer:M.question(s.entrance.draft).answerLabel},now-900);M.respond(s.entrance,now-800);assert.equal(s.entrance.attempts[0].correct,true);const id=s.entrance.draft.id;assert.notEqual(T.model(s,now).next.kind,'question');assert.equal(s.entrance.draft.id,id);});
test('maths time completion offers science without marking maths mastery or removing work',()=>{const s=fresh();M.startPractice(s.entrance,'volume',{now:now-1000,seed:5});worked(s,'maths',15);const id=s.entrance.draft.id,m=T.model(s,now);assert.equal(m.next.subject,'science');assert.equal(m.completed,1);assert.equal(s.entrance.draft.id,id);assert.equal(s.entrance.attempts.length,0);assert.equal(Object.keys(s.planner.milestones).length,0);});
test('rest days and completed plans create no catch-up tasks; next day uses its own goals',()=>{const s=fresh();for(const day of s.planner.schedule.week)day.maths=day.science=0;assert.equal(T.model(s,now).next,null);assert.equal(T.model(s,now).restDay,true);const a=fresh();worked(a,'maths',15);worked(a,'science',15);assert.equal(T.model(a,now).next,null);assert.equal(T.model(a,now).finished,true);assert.equal(T.model(a,now+DAY).completed,0);assert.equal(T.model(a,now+DAY).next.subject,'maths');});
test('an already-open paper is prioritised even on a rest day, without exposing new papers',()=>{const s=fresh();for(const day of s.planner.schedule.week)day.maths=day.science=0;S.startPaper(s.sciencePath,'mixed-a',now-1000);const before=JSON.stringify(s),m=T.model(s,now);assert.equal(m.next.subject,'science');assert.equal(m.next.kind,'paper');assert.equal(m.next.deadline,now-1000+3600000);assert.equal(JSON.stringify(s),before);assert.equal(Object.keys(s.entrance.papers).length,0);});
test('when two devices left different papers open the earliest real deadline wins',()=>{const s=fresh();M.startPaper(s.entrance,'mixed-a',now-10000);S.startPaper(s.sciencePath,'mixed-a',now-1000);assert.equal(T.model(s,now).next.subject,'science');assert.equal(T.model(s,now).next.paper,'mixed-a');});
test('structured practice never defaults to a reserved mixed paper after lessons are explored',()=>{const s=fresh();for(const u of M.D.units){finish(s.entrance,M,u.id,now-2000);for(let i=0;i<2;i++)answer(s.entrance,M,u.id,'apply',now-1900+i*500);answer(s.entrance,M,u.id,'transfer',now-500);}M.finishPractice(s.entrance);const before=JSON.stringify(s);const t=T.task(s,'maths',now);assert.equal(t.kind,'practice');assert.equal(Object.keys(s.entrance.papers).length,0);assert.equal(JSON.stringify(s),before);});
test('due retrieval can lead today but it remains a request, not an automatic success',()=>{const s=fresh();finish(s.entrance,M,'relationships',now-8*DAY-1000);for(let i=0;i<2;i++)answer(s.entrance,M,'relationships','apply',now-8*DAY-900+i*100);answer(s.entrance,M,'relationships','transfer',now-8*DAY-300);M.finishPractice(s.entrance);const t=T.task(s,'maths',now);assert.equal(t.kind,'recall');assert.equal(M.evidence(s.entrance,'relationships',now).delayed,0);});
test('unknown study subjects are rejected rather than routed to an unrelated lesson',()=>assert.throws(()=>T.task(fresh(),'spelling',now),/Unknown/));
